<?
$border1L = "BORDER: #CCCCCC 1px solid";
$border1R = "BORDER-TOP: #CCCCCC 1px solid; BORDER-RIGHT: #CCCCCC 1px solid; BORDER-BOTTOM: #CCCCCC 1px solid";
$border1B = "BORDER-BOTTOM: #CCCCCC 1px solid";

$border2L = "BORDER-LEFT: #CCCCCC 1px solid; BORDER-BOTTOM: #CCCCCC 1px solid; BORDER-RIGHT: #CCCCCC 1px solid";
$border2R = "BORDER-BOTTOM: #CCCCCC 1px solid; BORDER-RIGHT: #CCCCCC 1px solid";



?>
