<table width=100% cellspacing=0 cellpadding=0 border=1 bordercolor=#777777>
<tr height=22>
  <td colspan=2 align=center>&nbsp;</td>
  <td align=center>판매</td>
  <td align=center>입고</td>
  <td align=center>이동</td>
  <td align=center>손실</td>
  <td align=center>전일재고</td>
  <td align=center>금일재고</td>
  <td align=center>재고합산</td>
</tr>


<!----------- 합계 // --------------------------------------------------------------------->




<!----------- 카테고리별 소계 // ---------------------------------------------------------->

</table>
