<html>
<head>

    <META content="text/html; charset=EUC-KR" http-equiv=Content-Type>
    <title>FEEL BUY ERP (Korean)</title>

<style type="text/css">
body	{ font-family:"Arial","돋움"; font-size:9pt;color:#000000; text-decoration:none;}
td    { font-family:"Arial","돋움"; font-size:9pt;color:#000000; text-decoration:none;}

A:link{color:#222222;text-decoration:None}
A:visited{color:#222222;text-decoration:None}
A:hover{color:#0066CC;text-decoration:None}
A:active{color:#0066CC;text-decoration:None}

A.myA:link{color:#000000;text-decoration:None}
A.myA:visited{color:#000000;text-decoration:None}
A.myA:hover{color:#444444;text-decoration:None}
A.myA:active{color:#444444;text-decoration:None}

A.myB:link{color:#000000;text-decoration:None}
A.myB:visited{color:#000000;text-decoration:None}
A.myB:hover{color:#222222;text-decoration:Underline}
A.myB:active{color:#222222;text-decoration:None}

A.myD:link{color:#005FA9;text-decoration:None}
A.myD:visited{color:#005FA9;text-decoration:None}
A.myD:hover{color:#8C3400;text-decoration:None}
A.myD:active{color:#8C3400;text-decoration:None}

A.myE:link{color:#8C3400;text-decoration:None}
A.myE:visited{color:#8C3400;text-decoration:None}
A.myE:hover{color:#005FA9;text-decoration:None}
A.myE:active{color:#005FA9;text-decoration:None}

A.newsA:link{color:#222222;text-decoration:None}
A.newsA:visited{color:#333333;text-decoration:None}
A.newsA:hover{color:#0066CC;text-decoration:Underline}
A.newsA:active{color:#0066CC;text-decoration:None}

A.smenu:link{color:#666666;text-decoration:None}
A.smenu:visited{color:#666666;text-decoration:None}
A.smenu:hover{color:#000000;text-decoration:None}
A.smenu:active{color:#000000;text-decoration:None}

.mmenuA {  font-family: "돋움","Arial"; font-size:9pt;color:#222222; text-decoration: none;}
.mmenuB {  font-family: "돋움","Arial"; font-size:10pt;color:#000000; text-decoration: none;}
.mmenuH {  font-family: "Verdana", "돋움","Arial"; font-size:10pt;color:#FFFFFF; text-decoration: none;}
.smenuA {  font-family: "돋움","Arial"; font-size:8pt;color:#8C7539; text-decoration: none;}
.smenuB {  font-family: "돋움","Arial"; font-size:8pt;color:#111111; text-decoration: none;}
.footerA {  font-family: "돋움","Arial"; font-size:7pt;color:#777777; text-decoration: none;}
.contentA {  font-family: "돋움","Arial"; font-size:11pt;color:#000000; text-decoration: none;}
.contentD {  font-family: "돋움","Arial"; font-size:8pt;color:#000000; text-decoration: none;}

.mmenuP10 {  font-family: "Verdana", "돋움","Arial"; font-size:10pt;color:#000000; text-decoration: none;}
.mmenuP11 {  font-family: "Verdana", "돋움","Arial"; font-size:11pt;color:#000000; text-decoration: none;}
.mmenuP12 {  font-family: "Verdana", "돋움","Arial"; font-size:12pt;color:#000000; text-decoration: none;}
.mmenuP13 {  font-family: "Verdana", "돋움","Arial"; font-size:13pt;color:#000000; text-decoration: none;}
.mmenuP14 {  font-family: "Verdana", "돋움","Arial"; font-size:14pt;color:#000000; text-decoration: none;}
.mmenuP15 {  font-family: "Verdana", "돋움","Arial"; font-size:15pt;color:#000000; text-decoration: none;}
.mmenuP16 {  font-family: "Verdana", "돋움","Arial"; font-size:16pt;color:#000000; text-decoration: none;}


body {
scrollbar-face-color: #FFFFFF; scrollbar-shadow-color: #6699CC; 
scrollbar-highlight-color: #6699CC; scrollbar-3dlight-color: #FFFFFF; 
scrollbar-darkshadow-color: #FFFFFF; scrollbar-track-color: #FFFFFF; 
scrollbar-arrow-color: #6699CC;
}
</style>


<script type="text/JavaScript">
<!--
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}

function MM_showHideLayers() { //v3.0
  var i,p,v,obj,args=MM_showHideLayers.arguments;
  for (i=0; i<(args.length-2); i+=3) if ((obj=MM_findObj(args[i]))!=null) { v=args[i+2];
    if (obj.style) { obj=obj.style; v=(v=='show')?'visible':(v='hide')?'hidden':v; }
    obj.visibility=v; }
}

function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}
//-->
</script>

<script src="config/javascript/embed_patch-200609.js" type="text/javascript"></script>
</head>
