<?
// Front Desk Menu
$frn1_mmenu_01 = "Barcode";
$frn1_mmenu_02 = "Checking";
$frn1_mmenu_03 = "Correction";
$frn1_mmenu_04 = "Daily Recapitulation";
$frn1_mmenu_05 = "Print";

$frn1_mmenu_06 = "Language"; // 언 어
$frn1_mmenu_06_en = "English"; // 영 어
$frn1_mmenu_06_ko = "Korean"; // 한국어
$frn1_mmenu_06_in = "Indonesian"; // 인도네시아어
$frn1_mmenu_07 = "Don't have an account?"; // 사용자 계정이 없나요?
$frn1_mmenu_08 = "Login"; // 로그인
$frn1_mmenu_08b = "Sign In"; // 로그인
$frn1_mmenu_09 = "Member Login"; // 회원 로그인
$frn1_mmenu_10 = "Please provide your details."; // 사용자 정보를 입력하세요.
$frn1_mmenu_11 = "Company ID"; // 회사 ID
$frn1_mmenu_119 = "Church ID"; // 교회 ID
$frn1_mmenu_12 = "User ID"; // 사용자 ID
$frn1_mmenu_12e = "User ID or Email"; // 사용자 ID 또는 Email
$frn1_mmenu_13 = "Password"; // 비밀번호
$frn1_mmenu_14 = "Keep me signed in"; // 로그인 상태 유지
$frn1_mmenu_15 = "Signup for Account"; // 가입하기
$frn1_mmenu_16 = "Login to Trial Version"; // 데모 버전 로그인
$frn1_mmenu_17 = "Create your free trial account:"; // 무료 데모 계정을 발급받으세요:
$frn1_mmenu_18 = "Company Name"; // 회사 이름
$frn1_mmenu_189 = "Church Name"; // 교회 이름
$frn1_mmenu_19 = "Name"; // 이름
$frn1_mmenu_20 = "Phone No."; // 전화번호
$frn1_mmenu_21 = "Agree with the Terms & Conditions."; // 사용자 약관에 동의합니다.
$frn1_mmenu_22 = "Register"; // 등록하기
$frn1_mmenu_23 = "Already have an account?"; // 이미 계정이 있나요?
$frn1_mmenu_24 = "Login to your account"; // 사용자 로그인
$frn1_mmenu_25 = "ERP Dashboard";
$frn1_mmenu_26 = "Back to Homepage"; // 홈페이지로 가기
$frn1_mmenu_27 = "Per Month"; // 매월
$frn1_mmenu_28 = "Signup Now"; // 지금 가입하기


// Hangeul Jamo
$ko01 = "ㄱ";
$ko02 = "ㄴ";
$ko03 = "ㄷ";
$ko04 = "ㄹ";
$ko05 = "ㅁ";
$ko06 = "ㅂ";
$ko07 = "ㅅ";
$ko08 = "ㅇ";
$ko09 = "ㅈ";
$ko10 = "ㅊ";
$ko11 = "ㅋ";
$ko12 = "ㅌ";
$ko13 = "ㅍ";
$ko14 = "ㅎ";


// Church Community Name
$ch_comm_dir1 = "Parish"; // 교 구
$ch_comm_dir11 = "Parish Priest"; // 담당 교역자
$ch_comm_dir2 = "Rigion"; // 지 역
$ch_comm_dir20 = "Rigion"; // 지역
$ch_comm_dir21 = "Head of Rigion"; // 지역장
$ch_comm_cug2 = "New Family"; // 새가족반


// Menu Sets - Modules
$title_module_01 = "Purchasing"; // 구매 관리
	$title_module_01_type1 = "Local"; // 국내
	$title_module_01_type2 = "Overseas"; // 헤외
$title_module_0101 = "Product Search"; // 구매 상품 검색
$title_module_0102 = "Purchase Order"; // 상품구매 주문 관리
  $title_module_0102A = "In Process"; // 상품구매 주문 관리
  $title_module_0102B = "Completed"; // 상품구매 주문 관리
$title_module_0103 = "Purchase Approval"; // 구매 주문 승인 및 발송
$title_module_0104 = "Physical Check"; // 상품 수령 확인
$title_module_0105 = "Warehousing"; // 입고
$title_module_0106 = "Warehousing Check"; // 입고 확인

$title_module_01B = "Purchase Request"; // 주문 관리
$title_module_01B01 = "Product Search (PR)"; // 상품 검색 (PR)
$title_module_01B02 = "Purchase Request (PR)"; // 주문 관리 (PR)
$title_module_01B03 = "Request Approval"; // 주문 승인 및 인도

$title_module_01C = "Warehouse"; // 주문 관리
$title_module_01C01 = "Sales Order (WMS)"; // 상품 검색 (WMS)
$title_module_01C02 = "Purchasing Order (WMS)"; // 상품 검색 (WMS)
$title_module_01C03 = "Delivery Order (WMS)"; // 상품 검색 (WMS)
$title_module_01C04 = "Surat Jalan (WMS)"; // 상품 검색 (WMS)

$title_module_02 = "Inventory"; // 재고 관리
$title_module_0201 = "Stock Input"; // 상품 등록/수정
$title_module_0201on = "Stock Update - Online"; // 상품 수정 - 온라인
$title_module_0202 = "Payment (PP)"; // 상품구매 후지불결제 (PP)
$title_module_0203 = "Payment Confirmation"; // 구매 지불마감 관리

$title_module_0204 = "Stock Output"; // 출고 관리
$title_module_0205 = "Delivery Check"; //  화물 인도 지시 검토
	$title_module_0206 = "Surat Jalan"; // 화물 인도 지시서
	$title_module_0207 = "Billing Management"; // 대금 청구 관리
$title_module_0208 = "Return"; // 재고 반품 관리
$title_module_0209 = "Product Pick-up"; // 상품 수령
$title_module_0210 = "Stock Opname"; // 재고 실사
$title_module_0220 = "Stock Closing"; // 재고 마감

$title_module_0211 = "Product Options"; // 상품 옵션 항목 관리
$title_module_0212 = "Product Units"; // 상품 단위 관리
$title_module_0213 = "Product Packages"; // 상품 포장 단위 수정
$title_module_0214 = "Product Prices"; // 상품 가격 수정

$title_module_03 = "Logistics"; // 물류 관리
$title_module_0301 = "Check Surat Jalan"; // 화물 인도 지시서 확인
$title_module_0302 = "Logistics Progress"; // 화물 인도 관리

$title_module_03A = "Shipment"; // 배송 관리
$title_module_03A01 = "Shipment Booking"; // 배송 예약
$title_module_03A011 = "+ Closing"; // + 마감
$title_module_03A012 = "+ Remittance"; // + 송금
$title_module_03A02 = "Shipment Reconcile"; // 배송비 정산
$title_module_03A03 = "+ Confirmation"; // + 정산 확인
$title_module_03A04 = "Pickup"; // 집배 관리
$title_module_03A05 = "+ Pickup Manifest"; // + 집배 확인

$title_module_04 = "Asset Management"; // 자산 관리
$title_module_0401 = "Assets"; // 자산
$title_module_04012 = "+ Vehicle"; // + 차량
$title_module_0402 = "Depreciation"; // 감가상각
$title_module_0403 = "Cost of Goods Sold"; // 원가
$title_module_0404 = "Amortization";

$title_module_05 = "Sales (Branch Shop)"; // 판매 관리 (Branch Shop)
$title_module_0501 = "Sales Entry"; // 판매 입력
$title_module_0502 = "Payment Collection"; // 수금 관리
$title_module_0503 = "Stock Input"; // 상품 등록/수정

$title_module_0506 = "Product Pick-up"; // 상품 수령
$title_module_0507 = "Stock Opname"; // 재고 실사
$title_module_0508 = "Point of Sales [POS]";
$title_module_0509 = "POS Monitoring";

$title_module_06 = "Sales (Consignment)"; // 판매 관리 (Consignment Store)
$title_module_0601 = "Sales Entry"; // 판매 입력
$title_module_0602 = "Payment Collection"; // 수금 관리
$title_module_0603 = "Product Search"; // 상품 검색
$title_module_0604 = "Product Request"; // 주문(PR) 관리
$title_module_0605 = "Request Approval"; // 주문 승인 및 화물 인도
$title_module_0606 = "Product Pick-up"; // 상품 수령
$title_module_0607 = "Stock Opname"; // 재고 실사

$title_module_07 = "Sales (Direct Sales)"; // 판매 관리 (Direct Sales)
$title_module_0701 = "Sales Entry"; // 판매 입력
$title_module_0702 = "Payment Collection"; // 수금 관리
$title_module_0703 = "Product Search"; // 상품 검색
$title_module_0704 = "Product Request"; // 주문(PR) 관리
$title_module_0705 = "Request Approval"; // 주문 승인 및 화물 인도

$title_module_0707 = "Stock Opname"; // 재고 실사

$title_module_08 = "CRM/HR"; // 고객/인사 관리
$title_module_0801 = "Customer"; // 고객 관리
$title_module_0802 = "Distributor"; // 대리점
$title_module_0803 = "Employee"; // 사원 관리
$title_module_0804 = "Mailing List"; // 메일링 리스트
	$title_module_08041 = "Mailing List (Employee)"; // 메일링 리스트 (사원)
	$title_module_08042 = "Mailing List (Member)"; // 메일링 리스트 (회원)
	$title_module_08043 = "Mailing List (--)"; // 메일링 리스트 (비회원)
$title_module_0805 = "News Letter"; // 뉴스 레터

$title_module_09 = "Finance"; // 재무 관리
$title_module_0901 = "General Expenses"; // 일반 비용 관리
$title_module_0902 = "Purchase Cost"; // 구매 비용 관리
$title_module_0903 = "General Income"; // 일반 수익 관리
$title_module_0904 = "Sales Income"; // 판매 수익 관리
$title_module_0905 = "Invoices"; // 인보이스
$title_module_0906 = "Income Statement"; // 수지분석표
$title_module_0907 = "Kurs Balance"; // 수지분석표

$title_module_10 = "Accounting"; // 회계 관리
$title_module_1001 = "General Accounting"; // 일반 회계
$title_module_1002 = "Financial Accounting"; // 재무 회계
$title_module_1003 = "Managerial Accounting"; // 관리 회계
$title_module_1004 = "Tax Accounting"; // 세무 회계

$title_module_11 = "CMS (Website)"; // CMS (홈페이지 관리)
$title_module_1101 = "Menu Editor"; // 메뉴 관리
$title_module_1102 = "Contents Editor"; // 콘텐츠 편집
$title_module_1103 = "Banner Files"; // 배너 파일 관리
$title_module_1104 = "Banner Display"; // 배너 게시 관리
$title_module_1105 = "Page Stuff"; // 기타 페이지 편집
$title_module_1106 = "Website Layout"; // 홈페이지 레이아웃

$title_module_98 = "Financial Institution"; // 금융 기관
$title_module_99 = "Insurance"; // 보험


// Reports
$title_report = "Reports"; // 리포트
$title_report_08 = "Customer"; // 고객 현황
	$title_report_0801 = "Customer List"; // 고객 리스트
	$title_report_0802 = "Customer List Details"; // 고객 리스트 - 세부
	$title_report_0803 = "Customer List - B2B"; // 고객 리스트 - B2B
	$title_report_0804 = "Customer List - Direct Sales"; // 고객 리스트 - Direct Sales
	$title_report_0805 = "Customer List - Distributor"; // 고객 리스트 - 대리점
	$title_report_0806 = "Customer List - Branch Shop"; // 고객 리스트 - 독립 매장
	$title_report_0811 = "Customer Stores - B2B"; // 업체별 매장 현황 - B2B
	$title_report_0812 = "Customer Stores - Retail"; // 업체별 매장 현황 - Retail
	$title_report_0813 = "Store Customers"; // 매장별 구매 고객 현황
	
$title_report_08B = "HR"; // 사원 현황
	$title_report_08B01 = "Attendance Book"; // 직원 출퇴근 현황
	
$title_report_01 = "Purchasing"; // 구매 현황
	$title_report_0101 = "Monthly Purchasing"; // 월간 구매 현황

$title_report_02 = "Inventory"; // 재고 현황
	$title_report_0201 = "Strategy for Stock Out"; // 적정 물량 출고 기준
	$title_report_0205 = "Stock Out into Shops"; // 물품 출고 현황
		$title_report_020501 = "Stock Out into Shops - by Region"; // 물품 출고 현황 -지역별
		$title_report_020502 = "Stock Out into Shops - by Shop"; // 물품 출고 현황 -영업점별
		$title_report_020503 = "Stock Out into Shops - by Warehouse"; // 물품 출고 현황 -카테고리별
    $title_report_020504 = "Stock Out into Shops - by Corporate"; // 물품 출고 현황 -카테고리별

	$title_report_0211 = "Stock & Display in Shops"; // 매장별 판매제품 전시 현황
	$title_report_0221 = "Return"; // 반품 현황
		$title_report_022101 = "Return in Departments"; // 반품 현황 - 영업부별
		$title_report_022102 = "Return in Items"; // 반품 현황 - 아이템별

$title_report_31 = "Marketing"; // 마케팅
	$title_report_3101 = "Promotion Effect Evaluation"; // 제품별 프로모션 효율표

$title_report_05 = "Sales Income"; // 매출 현황
	$title_report_0501 = "Group Sales Income"; // 그룹 영업 현황
	$title_report_0502 = "Sales Income by Branch Shop"; // 독립 매장 영업 현황
	$title_report_0503 = "Sales Income by Department"; // 부서별 영업 현황
	$title_report_0511 = "Monthly Sales Income"; // 월간 매출 현황
		$title_report_051101 = "Monthly Sales Income by Branch Shop"; // 월간 매출 현황 - 독립 매장
		$title_report_051102 = "Monthly Sales Income by Consignment Store"; // 월간 매출 현황 - 위탁 매장
		$title_report_051103 = "Monthly Sales Income by Consignment Customer"; // 월간 매출 현황 - 독립 업체
		$title_report_051104 = "Monthly Sales Income by Consignment Group"; // 월간 매출 현황 - 독립 그룹
		$title_report_051105 = "Monthly Sales Income by Department"; // 월간 매출 현황 - 부서별

$title_report_05B = "Sales Projection by Shop"; // 판매점별 매출 현황 *

$title_report_04 = "Asset"; // 자산 현황
	$title_report_0401 = "Group Asset"; // 그룹 자산 현황
	$title_report_0402 = "Automobile"; // 차량 리즈 현황
	
$title_report_09 = "Finance"; // 재무 현황
	$title_report_0901 = "Daily Financial Report"; // 일일 자금 보고
	$title_report_0902 = "Payables"; // 미지급금 현황
		$title_report_090201 = "Payables in Distributors"; // 미지급금 현황 - 업체별
		$title_report_090202 = "Payables in Transactions"; // 미지급금 현황 - 거래별
	$title_report_0903 = "Payables & Installment for Automobile"; // 차량 분할 상환 현황
	$title_report_0904 = "Payables for Bank Loan"; // 은행 대출 상환 현황
	$title_report_0905 = "Payables & Transactions in Distributors"; // 업체별 거래 현황 - B2B
	$title_report_0906 = "Payables & Transactions in Consignment Stores"; // 업체별 거래 현황 - 위탁 매장
	$title_report_0931 = "Asset & Cash Flow"; // 자산 및 자금 변동 현황
	$title_report_0951 = "Financial Statements"; // 자금 현황

  $title_report_10A = "Warehouse Sales Order"; //창고 - 판매 주문
  $title_report_10B = "Warehouse Purchasing Order"; //창고 - 판매 주문
	


// Menu
$hmm_name_01 = "Home";
$hmm_name_02 = "Sales"; // 판매 관리
  $hsm_name_02_01 = "Sales Entry"; // 판매 입력
  $hsm_name_02_02 = "Purchase Request"; // 주문 관리 *feelbuy Ordersheet
  $hsm_name_02_02a = "Product Search"; // 상품 검색
  $hsm_name_02_02b = "Request Approval"; // 주문 승인 및 화물 인도
  $hsm_name_02_021 = "Product Pick-up"; // 상품 수령
  $hsm_name_02_022 = "Stock Opname"; // 재고 실사
  $hsm_name_02_03 = "Delivery"; // 배송 관리
  $hsm_name_02_04 = "Billing Management"; // 대금 청구 관리
  $hsm_name_02_041 = "Payment Collection"; // 수금 관리
  $hsm_name_02_05 = "Invoices"; // 인보이스 관리
  $hsm_name_02_09 = "Products"; // 상품 관리
  $hsm_name_02_POS = "Point of Sales [POS]"; // 판매 관리
 
$hmm_name_03 = "";

$hmm_name_03ch = "Members"; // 교적 관리
  $hsm_name_03ch_01 = "Clergymen"; // 교역자 정보
  $hsm_name_03ch_02 = "Individuals"; // 개인 정보
  $hsm_name_03ch_03 = "Family Heads"; // 세대 정보
  $hsm_name_03ch_04 = "$ch_comm_dir20";
  $hsm_name_03ch_05 = "$ch_comm_cug1";
  $hsm_name_03ch_06 = "$ch_comm_cug10"." Attendances";
  $hsm_name_03ch_06t = "Attandances"; // 출결 관리

$hmm_name_04 = "Inventory"; // 구매/재고 관리 -- 상품 관리 현황
  $hsm_name_04_01 = "Stock Input"; // 구매/입고 관리 -- 상품 등록/수정
  $hsm_name_04_02 = "Stock Output"; // 출고 관리
  $hsm_name_04_021 = "Product Pick-up"; // 상품 수령
  $hsm_name_04_022 = "Stock Opname"; // 재고 실사
  $hsm_name_04_023 = "Billing Management"; // 대금 청구 관리
  $hsm_name_04_03 = "Inventory Confirmation"; // 재고 수정/마감 관리
  $hsm_name_04_03_2 = "Return"; // 재고 반품 관리
  $hsm_name_04_04 = "Payment"; // 상품구매 지불결제 관리
  $hsm_name_04_041 = "Payment Check"; // 지불결제 확인
  $hsm_name_04_05 = "Payment Confirmation"; // 구매 지불마감 관리
  $hsm_name_04_06 = "Purchase Order"; // 상품구매 주문 관리
  $hsm_name_04_061 = "Product Search"; // 구매 상품 검색
  $hsm_name_04_062 = "Purchase Approval"; // 구매 주문 승인 및 발송
  $hsm_name_04_07 = "Physical Check"; // 상품 수령 확인
  $hsm_name_04_071 = "Warehousing"; // 입고
  $hsm_name_04_072 = "Warehousing Check"; // 입고 확인
  $hsm_name_04_08 = "Invoice"; // 인보이스
  $hsm_name_04_21 = "Product Options"; // 상품 옵션 항목 관리
  $hsm_name_04_22 = "Product Units"; // 상품 단위 관리

$hmm_name_041 = "Logistics"; // 물류 관리
  $hsm_name_041_01 = "Check Surat Jalan"; // 화물 인도 지시서 확인
  $hsm_name_041_02 = "Logistics Progress"; // 화물 인도 관리

$hmm_name_05 = "Finance"; // 재무/회계 관리
  $hsm_name_05_01 = "Management Cost"; // 비용 관리
  $hsm_name_05_01_2 = "Purchasing Cost"; // 구매 비용 관리
  $hsm_name_05_02 = "Management Income"; // 수익 관리
  $hsm_name_05_02_2 = "Sales Income"; // "판매 수익 관리
  
  $hsm_name_05ch_02_2 = "Tawaran Masuk"; // 헌금 계수 관리 // ^
  $hsm_name_05ch_offering = "Tawaran Data Entri"; // 헌금 계수
  
  $hsm_name_05_03 = "Lembar Keseimbangan"; // 상세 수익/비용 분석
  $hsm_name_05_04 = "Budget & Outgoing"; // 예산 사용 현황

$hmm_name_06 = "Customer"; // 고객 관리
  $hsm_name_06_01 = "Customer"; // 고객 관리
  $hsm_name_06_010 = "Consignment Store"; // 위탁 매장
  $hsm_name_06_011 = "Reseller (Shop)"; // 리셀러 (상점)
  $hsm_name_06_012 = "Reseller (Individual)"; // 리셀러 (개인)
  $hsm_name_06_013 = "Direct Sales"; // 일반 고객 (기업)
  $hsm_name_06_014 = "Individual"; // 일반 고객 (개인)
  $hsm_name_06_015 = "Business to Business";
  $hsm_name_06_02 = "Distributor"; // 대리점
  $hsm_name_06_021 = "Distributor"; // 대리점 (지역총판)
  $hsm_name_06_022 = "Sub-distributor"; // 대리점 (지역지점)
  $hsm_name_06_03 = "Mailing List"; // 메일링 리스트
  $hsm_name_06_04 = "News Letter"; // 뉴스 레터

$hmm_name_07 = "HR"; // 인력 관리
  $hsm_name_07_01 = "Employee"; // 사원 관리
  $hsm_name_07_02 = "Contractor (SA)"; // 용역 (SA) 관리

$hmm_name_08 = "Website"; // 홈페이지 관리
  $hsm_name_08_01 = "Menu Editor"; // 메뉴 관리
  $hsm_name_08_02 = "Contents Editor"; // 콘텐츠 편집
  $hsm_name_08_03 = "Banner Manager"; // 배너 관리
  $hsm_name_08_031 = "Banner Files"; // 배너 파일 관리
  $hsm_name_08_032 = "Banner Display"; // 배너 게시 관리
  $hsm_name_08_04 = "Page Stuff"; // 기타 페이지 편집
  $hsm_name_08_05 = "Mailing List"; // 메일링 리스트
  $hsm_name_08_05A = "Mailing List (Member)"; // 메일링 리스트 A (회원)
  $hsm_name_08_05B = "Mailing List (Non-member)"; // 메일링 리스트 B (비회원)
  $hsm_name_08_06 = "News Letter"; // 뉴스 레터
  $hsm_name_08_09 = "Website Layout"; // 홈페이지 레이아웃
  $hsm_name_08_10 = "Online Shop Layout"; // 쇼핑몰 레이아웃
  $hsm_name_08_goto = "Go to the website"; // 홈페이지 바로가기
  
$hmm_name_09 = "System Settings"; // 시스템 관리
  $hsm_name_09_01 = "Systems"; // 시스템 관리
  $hsm_name_09_02 = "System Managers"; // 시스템 Manager 관리
  $hsm_name_09_01d = "Departments"; // 부서 관리
  $hsm_name_09_031 = "Shops"; // 매장 관리
  $hsm_name_09_032 = "Shop Managers"; // 매장 Manager 관리
  $hsm_name_09_03C = "Currency"; // Currency
  $hsm_name_09_04 = "Suppliers"; // 공급자 관리
  $hsm_name_09_04A = "Brands"; // 브랜드
  $hsm_name_09_05 = "Product Category"; // 상품 카테고리 관리
  $hsm_name_09_06 = "Mileage Settings"; // 마일리지
  $hsm_name_09_07 = "Discount Rates"; // 리셀러 할인율
  $hsm_name_09_08 = "Vouchers"; // 바우처 발행관리
  $hsm_name_09_081 = "YARNEN"; // YARNEN 관리
  $hsm_name_09_09 = "Special Pricing"; // 특별 행사가
  $hsm_name_09_10 = "Initial Cash"; // 현금시제 초기값
  $hsm_name_09_11 = "Bank Accounts"; // 결제은행 계좌관리
  $hsm_name_09_12 = "Card Switchings"; // 신용카드 결제기 관리
  $hsm_name_09_12a = "Insurance Agents"; // 보험사 관리
  $hsm_name_09_13 = "Accounting Codes"; // 계정항목 관리
  $hsm_name_09_132 = "Cost"; // 부서별 지출항목
  $hsm_name_09_133 = "Budget"; // 부서별 예산
  $hsm_name_09_14 = "Bank Loans"; // 은행대출
  $hsm_name_09_20 = "Foreign Exchange"; // 환율 관리
  $hsm_name_09_15 = "Regions"; // 지역 관리
  $hsm_name_09_16 = "Ports"; // 선적항
  $hsm_name_09_17 = "Warehouses"; // 창고 관리
		$hsm_name_09_1701 = "Location Category"; // 적재소 카테고리
		$hsm_name_09_1702 = "Location Management"; // 적재소 관리
  $hsm_name_09_18 = "Consignment Group"; // 위탁판매 그룹 관리
  $hsm_name_09_21 = "Client DB Merge"; // 연동 Client DB 계정
  $hsm_name_09_22 = "Coporates"; // 회사 계정
  $hsm_name_09_23 = "Loan Providers"; // 펀드 제공은행
  $hsm_name_09_34 = "Training/Activity"; // 훈련/활동 과정 관리
  $hsm_name_09_341 = "Training Category"; // 훈련/활동 카테고리
  $hsm_name_09_342 = "Training Course"; // 훈련/활동 과정
  $hsm_name_09_41 = "Job Class"; // 직급 코드
  $hsm_name_09_42 = "Salary Class"; // 호봉
  $hsm_name_09_43 = "Yearly Payroll Baseline"; // 연간 임금기준표
  
  $hsm_name_09ch_31 = "Group Category"; // 그룹 카테고리
  $hsm_name_09ch_311 = "Districts"; // 교구와 지역 구분
  $hsm_name_09ch_312 = "Departments"; // 부 서
  $hsm_name_09ch_313 = "Missionaries"; // 선교회
  $hsm_name_09ch_32 = "$ch_comm_cug1";
  $hsm_name_09ch_33 = "Avocation"; // 직위 및 직분
  $hsm_name_09ch_331 = "Position"; // 직 위
  $hsm_name_09ch_332 = "Post"; // 직 분
  $hsm_name_09ch_333 = "Occupation"; // 직 업
  $hsm_name_09ch_34 = "Training/Activity"; // 훈련/활동 과정 관리
  $hsm_name_09ch_341 = "Training Category"; // 훈련/활동 카테고리
  $hsm_name_09ch_342 = "Training Course"; // 훈련/활동 과정

$hmm_name_10 = "Settings"; // user // 환경 설정
  $hsm_name_10_01 = "Language"; // 언어선택
  $hsm_name_10_02 = "Profile"; // 계정정보 변경
  $hsm_name_10_03 = "Change Your Password"; // 비밀번호 변경
  $hsm_name_10_04 = "Sign Up"; // 사용자 등록
  $hsm_name_10_05 = "Log In"; // 로그인
  $hsm_name_10_06 = "Log Out"; // 로그아웃


// 입출력 폼 - 공통
$txt_comm_frm01 = "Submit"; // 입 력
$txt_comm_frm01s = "Enter"; // 입력
$txt_comm_frm02 = "Submit"; // 확 인
$txt_comm_frm03 = "Post"; // 등 록
$txt_comm_frm04 = "Change"; // 변 경
$txt_comm_frm05 = "Update"; // 수정하기
$txt_comm_frm051 = "Submit"; // 추가하기
$txt_comm_frm051s = "Add"; // 추 가
$txt_comm_frm052 = "Delete"; // 삭제하기
$txt_comm_frm06 = "Cancel"; // 취 소
$txt_comm_frm07 = "Reset"; // 재입력
$txt_comm_frm08 = "Delete"; // 삭 제
$txt_comm_frm09 = "Reply"; // 답 변
$txt_comm_frm10 = "Print"; // 출 력
$txt_comm_frm11 = "Print"; // 인 쇄
$txt_comm_frm12 = "Upd"; // 수정
$txt_comm_frm13 = "Del"; // 삭제
$txt_comm_frm14 = "Order by"; // 정렬 순서
$txt_comm_frm15 = "See All"; // 전체 보기
$txt_comm_frm16 = "Data Update"; // 자료 업데이트
$txt_comm_frm17 = "Update"; // 업데이트
$txt_comm_frm18 = "Next"; // 다 음
$txt_comm_frm19 = "Select"; // 선 택
$txt_comm_frm20 = "All Systems"; // 전체 System
$txt_comm_frm21 = "Pin Key"; // 인증번호
$txt_comm_frm22 = "Enter the pin key:"; // 다음 번호를 입력하세요:
$txt_comm_frm23 = "Corporate"; // 회사 코드
$txt_comm_frm24 = "Select System"; // System 선택
$txt_comm_frm240 = "Select Department"; // 부서 선택
$txt_comm_frm241 = "Select Shop"; // Shop 선택
$txt_comm_frm242 = "Select Shop Manager"; // Shop Manager 선택
$txt_comm_frm25 = "See All Corporates"; // 전체 회사 보기
$txt_comm_frm251 = "See All Departments"; // 전체 부서 보기
$txt_comm_frm26 = "Search"; // 검 색
$txt_comm_frm261 = "Search Settings"; // 상세 검색
$txt_comm_frm262 = "Reset Settings"; // 검색 조건 초기화
$txt_comm_frm27 = "Save"; // 저장하기
$txt_comm_frm28 = "Submit"; // 처리하기
$txt_comm_frm29 = "Product Update"; // 상품 업데이트
$txt_comm_frm30 = "All Corporates"; // 전체 회사
$txt_comm_frm31 = "All Shops"; // 전체 Shop
$txt_comm_frm32 = "Select Corporate"; // 회사 선택
$txt_comm_frm33 = "Create Table"; // 테이블 생성
$txt_comm_frm331 = "Please click the button below to create Table here."; // 아래 버튼을 클릭하세요.
$txt_comm_frm34 = "Date"; // 날짜
$txt_comm_frm40 = "All Brands"; // 전체 브랜드
$txt_comm_frm41 = "Customer"; // 고객사
$txt_comm_frm411 = "Select Customer"; // 고객사 선택
$txt_comm_frm42 = "Area Group"; // 지역 대별
$txt_comm_frm43 = "Warehouse"; // 창고
$txt_comm_frm431 = "Select Warehouse"; // 창고 선택

$txt_comm_lang_en = "English"; // 영 어
$txt_comm_lang_in = "Indonesian"; // 인도네시아어
$txt_comm_lang_ko = "Korean"; // 한 글

$txt_comm_month = "Month"; // 월
$txt_comm_month_01 = "January"; // 1월
$txt_comm_month_02 = "February"; // 2월
$txt_comm_month_03 = "March"; // 3월
$txt_comm_month_04 = "April"; // 4월
$txt_comm_month_05 = "May"; // 5월
$txt_comm_month_06 = "June"; // 6월
$txt_comm_month_07 = "July"; // 7월
$txt_comm_month_08 = "August"; // 8월
$txt_comm_month_09 = "September"; // 9월
$txt_comm_month_10 = "October"; // 10월
$txt_comm_month_11 = "November"; // 11월
$txt_comm_month_12 = "December"; // 12월

$txt_comm_report_01 = "Daily Report"; // 일일 보고
$txt_comm_report_02 = "Weekly Report"; // 주간 보고
$txt_comm_report_03 = "Periodic Report"; // 기간별 보고
$txt_comm_report_04 = "Monthly Report"; // 월간 보고
$txt_comm_report_05 = "Quarterly Report"; // 분기 보고
$txt_comm_report_06 = "Yearly Report"; // 연간 보고
$txt_comm_report_21 = "Sales Projection"; // 판매 현황 보고
$txt_comm_report_41 = "Inventory Projection"; // 재고 현황 보고
$txt_comm_report_51 = "Financial Projection"; // 재무 현황 보고
$txt_comm_report_71 = "Period"; // 검색 기간
$txt_comm_report_81 = "Daily"; // 일일
$txt_comm_report_82 = "Weekly"; // 주간
$txt_comm_report_83 = "Monthly"; // 월간
$txt_comm_report_84 = "Quarterly"; // 분기
$txt_comm_report_85 = "Yearly"; // 연간


// church sermon & weekly bulletin
$txt_ch_blog_01 = "Subject"; // 설교 제목
$txt_ch_blog_02 = "Bible Text"; // 성경 말씀
$txt_ch_blog_03 = "Date"; // 설교일
$txt_ch_blog_04 = "Preacher"; // 설교자
$txt_ch_blog_05 = "Media Display"; // 동영상 재생
$txt_ch_blog_06 = "Media Link URL"; // 동영상 URL
$txt_ch_blog_07 = "Summary"; // 설교 요약
$txt_ch_blog_08 = "Weekly Bulletin"; // 주보


// VOD
$txt_vod_blog_01 = "Title"; // 제목
$txt_vod_blog_02 = "Reference"; // 참조
$txt_vod_blog_03 = "Date"; // 녹화일
$txt_vod_blog_04 = "Writer"; // 작성자
$txt_vod_blog_05 = "Media Display"; // 동영상 재생
$txt_vod_blog_06 = "Media Link URL"; // 동영상 URL
$txt_vod_blog_07 = "Summary"; // 요약


// sales > order, sales
$txt_sales_sales_01 = "Stock"; // 재 고
$txt_sales_sales_02 = "Gate"; // 입고지
$txt_sales_sales_03 = "Sell"; // 판 매
$txt_sales_sales_04 = "Add to Cart"; // 장바구니에 담기
$txt_sales_sales_05 = "Shopping Cart"; // 장바구니
$txt_sales_sales_06 = "Pay now"; // 결 제 하 기
$txt_sales_sales_07 = "Go shopping"; // 다른 상품 검색
$txt_sales_sales_08 = "Soldout"; // 매 진
$txt_sales_sales_09 = "Unit Price"; // 단 가
$txt_sales_sales_10 = "Total"; // 합 계
$txt_sales_sales_11 = "Total Amount"; // 총 주문 합계
$txt_sales_sales_12 = "Cashier"; // 계산하기
$txt_sales_sales_13 = "Cust. Name"; // 고객 이름
$txt_sales_sales_14 = "Cust. Type"; // 고객 분류
$txt_sales_sales_14_1 = "Memebr"; // 회 원
$txt_sales_sales_14_2 = "Non-member"; // 비회원
$txt_sales_sales_15 = "Product Type"; // 상품 유형
$txt_sales_sales_16 = "Total Amount"; // 총 판매액
$txt_sales_sales_17 = "Due Date"; // 수불 기일
$txt_sales_sales_18 = "Model Fee"; // 모델 Fee
$txt_sales_sales_19 = "Note"; // 메 모
$txt_sales_sales_20 = "Issue Invoice"; // 인보이스 발행
$txt_sales_sales_21 = "Invoice List"; // 인보이스 리스트
$txt_sales_sales_211 = "Invoice No."; // 인보이스 번호
$txt_sales_sales_212 = "Billing No."; // 청구 번호
$txt_sales_sales_213 = "Payment No."; // 결제 번호
$txt_sales_sales_214 = "Make Invoice"; // 인보이스 만들기
$txt_sales_sales_215 = "Send Invoice"; // 인보이스 발송
$txt_sales_sales_2161 = "Made"; // 작성일
$txt_sales_sales_2162 = "Sent"; // 발송일
$txt_sales_sales_2163 = "Confirmed"; // 확정일
$txt_sales_sales_2164 = "Collected"; // 수금일
$txt_sales_sales_217 = "Collection"; // 수금 현황
$txt_sales_sales_2171 = "Collected"; // 수금 완료
$txt_sales_sales_2172 = "Unollected"; // 미수
$txt_sales_sales_218 = "Customer"; // 고객
$txt_sales_sales_219 = "Recipient"; // 수취인
$txt_sales_sales_22 = "Print Invoice"; // 인보이스 인쇄
$txt_sales_sales_23 = "With Voucher"; // 바우처 결제
$txt_sales_sales_24 = "Special Sale-off"; // 특별 행사가
$txt_sales_sales_25 = "Include VAT"; // 부가세 포함
$txt_sales_sales_26 = "VAT"; // 부가세
$txt_sales_sales_27 = "Date of Order"; // 주문일
$txt_sales_sales_30 = "Non-member"; // 비회원
$txt_sales_sales_31 = "Individual"; // 개인 회원
$txt_sales_sales_32 = "Corporate"; // 기업 회원
$txt_sales_sales_40 = "Order"; // 주문하기
$txt_sales_sales_41 = "Order now"; // 지금 주문하기
$txt_sales_sales_42 = "Order No."; // 주문번호
$txt_sales_sales_43 = "Confirm/Cancel Order"; // 주문 확인/취소
$txt_sales_sales_44 = "Collected"; // 수금 완료
$txt_sales_sales_50 = "Add POS"; // POS 추가
$txt_sales_sales_51 = "Update POS"; // POS 수정
$txt_sales_sales_52 = "Delete POS"; // POS 삭제
$txt_sales_sales_53 = "No POS Registered"; // 등록된 POS가 없음
$txt_sales_sales_54 = "Registered POS Systems"; // 등록된 POS 시스템
$txt_sales_sales_55 = "Add New POS"; // 새 POS 추가
$txt_sales_sales_56 = "Please select POS."; // POS를 선택하세요.

$txt_sales_sales_chk01 = "Your selection already exists in Cart."; // 이미 선택하신 상품입니다.
$txt_sales_sales_chk02 = "Please select Client Name."; // 고객 이름을 선택하세요.
$txt_sales_sales_chk03 = "Please select Product Type."; // 상품 유형을 선택하세요.
$txt_sales_sales_chk04 = "Please select Total Amount."; // 총 판매액을 입력하세요.
$txt_sales_sales_chk05 = "Please select the other product in the same Shop."; // 동일한 Shop의 상품만 선택하실 수 있습니다.
$txt_sales_sales_chk06 = "Please input POS Number."; // POS의 고유한 번호를 입력하세요.
$txt_sales_sales_chk07 = "Please input POS Name."; // POS 시스템 이름을 입력하세요.
$txt_sales_sales_chk08 = "Your submission already exists in POS list."; // 등록된 것과 동일한 POS가 이미 있습니다.


// inventory > stock_in
$txt_invn_stockin_01 = "Inventory"; // 품목/상품 리스트
$txt_invn_stockin_02 = "Item"; // 품 목
$txt_invn_stockin_03 = "Product"; // 상 품
$txt_invn_stockin_04 = "Category"; // 카테고리
$txt_invn_stockin_05 = "Product Name"; // 상품명
$txt_invn_stockin_06 = "Prd. Code"; // 상품 코드
$txt_invn_stockin_051 = "Item/Brand"; // 품목명(브랜드)
$txt_invn_stockin_061 = "Item Code"; // 품목 코드
$txt_invn_stockin_07 = "Purchase Price"; // 매입단가
$txt_invn_stockin_07s = "Purchase"; // 매입단가
$txt_invn_stockin_08 = "Purchase Price"; // 입고단가
$txt_invn_stockin_09 = "Original Price"; // 원 가
$txt_invn_stockin_10 = "Market Price"; // 시장가 [Kios Price]
$txt_invn_stockin_11 = "Tag Price"; // 정 가 [Kios Price]
$txt_invn_stockin_12 = "Sale Price"; // 판매가
$txt_invn_stockin_121 = "Price"; // 가격
$txt_invn_stockin_122 = "Unit Price"; // 단가
$txt_invn_stockin_13 = "D/C Price"; // 할인가
$txt_invn_stockin_13i = "Invoice Price"; // 인보이스 금액
$txt_invn_stockin_14 = "Margin"; // 이 익
$txt_invn_stockin_15 = "Margin"; // 마 진
$txt_invn_stockin_16 = "Unit Margin"; // 개당이익
$txt_invn_stockin_17 = "Qty"; // 수 량
$txt_invn_stockin_18 = "Post Date"; // 입고일
$txt_invn_stockin_19 = "Add Item"; // 품목 추가
$txt_invn_stockin_20 = "Add Product"; // 상품 추가
$txt_invn_stockin_21 = "Select Category"; // 카테고리 선택
$txt_invn_stockin_22 = "Add"; // 추가
$txt_invn_stockin_23 = "Product Update"; // 상품정보 변경
$txt_invn_stockin_24 = "Item Update"; // 품목정보 수정
$txt_invn_stockin_25 = "Total Price"; // 총매입액
$txt_invn_stockin_26 = "Total Price"; // 총출고액
$txt_invn_stockin_27 = "Remove Product"; // 상품 삭제하기
$txt_invn_stockin_28 = "Color"; // 색 상
$txt_invn_stockin_29 = "Size"; // 크 기
$txt_invn_stockin_30 = "Original Code"; // 공급자 상품 코드
$txt_invn_stockin_31 = "Stock In"; // 입고 수량
$txt_invn_stockin_32 = "Stock Out"; // 출고 수량
$txt_invn_stockin_32s = "Sold"; // 판매 수량
$txt_invn_stockin_33 = "Stock"; // 재고 수량
$txt_invn_stockin_34 = "Stock Expired"; // 유효기간 만료
$txt_invn_stockin_35 = "Stock Remains"; // 남은 재고
$txt_invn_stockin_36 = "Unit"; // 단위
$txt_invn_stockin_37 = "Unit Name"; // 단위명
$txt_invn_stockin_38 = "Quantity per Unit"; // 단위당 수량
$txt_invn_stockin_40 = "Register Unit"; // 단위 추가하기
$txt_invn_stockin_41 = "Update Unit"; // 단위 수정하기
$txt_invn_stockin_42 = "Delete Unit"; // 단위 삭제하기
$txt_invn_stockin_43 = "Description"; // 개요
$txt_invn_stockin_44 = "Product Units"; // 상품 단위
$txt_invn_stockin_44p = "Package Units"; // 포장 단위
$txt_invn_stockin_45 = "Purchase Approval Form"; // 구매 승인 요청서
$txt_invn_stockin_46 = "Input your selection into Stock"; // 선택한 구매 항목을 입고함
$txt_invn_stockin_47 = "Approval"; // 승인
$txt_invn_stockin_48 = "Approved"; // 승인됨
$txt_invn_stockin_49 = "Send PO"; // PO 발송
$txt_invn_stockin_50 = "Print PO"; // PO 인쇄
$txt_invn_stockin_60 = "Pick-up Date"; // 수령확인일
$txt_invn_stockin_61 = "Quantity Check"; // 수량 확인
$txt_invn_stockin_611 = "Order"; // 발주시
$txt_invn_stockin_612 = "Pick-up"; // 수령시
$txt_invn_stockin_613 = "Loss"; // 손실
$txt_invn_stockin_6131 = "Lost"; // 분실
$txt_invn_stockin_6132 = "Broken"; // 파손
$txt_invn_stockin_6133 = "Expired"; // 기한 만료
$txt_invn_stockin_6134 = "Defection"; // 제품 결함
$txt_invn_stockin_6135 = "Msc."; // 기타
$txt_invn_stockin_614 = "Remarks"; // 비고
$txt_invn_stockin_62 = "Checked"; // 수령 확인
$txt_invn_stockin_63 = "Check"; // 확인
$txt_invn_stockin_64 = "Update Stock"; // 재고 확인
$txt_invn_stockin_65 = "Stock Updated"; // 재고 확인 완료
$txt_invn_stockin_66 = "Estimated"; // 추정치
$txt_invn_stockin_70 = "Close Stock"; // 재고 마감
$txt_invn_stockin_71 = "Beginning"; // 기초
$txt_invn_stockin_72 = "Ending"; // 기말
$txt_invn_stockin_73 = "Grand Total"; // 총 합계
$txt_invn_stockin_74 = "Total"; // 합계

$txt_invn_stockin_chk01 = "Enter Product Code."; // 상품 코드를 입력하세요.
$txt_invn_stockin_chk02 = "Enter Product Name."; // 상품명을 입력하세요.
$txt_invn_stockin_chk03 = "Please select Shop above."; // 좌측 상단에서 Shop을 선택하세요.
$txt_invn_stockin_chk04 = "Please select Category."; // 카테고리를 선택하세요.
$txt_invn_stockin_chk05 = "You cannot remove the item with products"; // 상품이 있는 품목은 삭제할 수 없습니다.
$txt_invn_stockin_chk06 = "Please remove the producst before remove item."; // 먼저 상품 리스트에서 삭제후 다시 품목을 삭제하십시오.
$txt_invn_stockin_chk07 = "Please select Warehouse."; // 창고를 선택하세요.


// inventory > stock_out
$txt_invn_stockout_01 = "Shop"; // 출고지(매장)
$txt_invn_stockout_02 = "Save Shop"; // 출고지(매장) 저장
$txt_invn_stockout_03 = "Return"; // 반 품
$txt_invn_stockout_04 = "Define Shop"; // 출 고
$txt_invn_stockout_05 = "Shop"; // 출고지
$txt_invn_stockout_06 = "Undefined"; // 미 정
$txt_invn_stockout_07 = "Defined"; // 지 정
$txt_invn_stockout_08 = "Cancel"; // 출고 취소
$txt_invn_stockout_09 = "Confirm"; // 출고 완료
$txt_invn_stockout_10 = "Partial Outlet"; // 일부 출고
$txt_invn_stockout_11 = "Partial Outlet"; // 분할 출고
$txt_invn_stockout_12 = "Outlet update"; // 출고 수정
$txt_invn_stockout_13 = "Confirm Stock"; // 재고 마감
$txt_invn_stockout_14 = "Change Stock"; // 재고 수정
$txt_invn_stockout_15 = "Original Stock"; // 변경전 재고
$txt_invn_stockout_16 = "Process"; // 처리 구분
$txt_invn_stockout_17 = "Confirm Stock"; // 재고 수정 및 마감
$txt_invn_stockout_18 = "Cancel Confirm"; // 재고 마감 취소
$txt_invn_stockout_19 = "Update Inventory"; // 재고 변동 관리
$txt_invn_stockout_20 = "Refund List"; // 반품 리스트
$txt_invn_stockout_21 = "Change Shop"; // 출고지(Shop) 변경
$txt_invn_stockout_22 = "Add Stock"; // 재고 추가
$txt_invn_stockout_23 = "Create New Code"; // 신규 상품 생성
$txt_invn_stockout_24 = "Date of Update"; // 재고 변동일
$txt_invn_stockout_25 = "Undefined"; // 미출고
$txt_invn_stockout_26 = "Shop"; // 출고
$txt_invn_stockout_27 = "New Take-out"; // 추가 출고
$txt_invn_stockout_28 = "Select Shop"; // 출고지(매장) 선택
$txt_invn_stockout_29 = "Please Select Shop."; // 매장을 선택하세요.

$txt_invn_stockout_30 = "Delivery Check"; // 화물 인도 지시 검토 *feelbuy Delivery Check
$txt_invn_stockout_31 = "Surat Jalan"; // 화물 인도 지시서 *feelbuy Delivery Order
$txt_invn_stockout_32 = "Surat Jalan"; // 화물 인도 지시서 양식 *feelbuy Delivery Order Form
$txt_invn_stockout_33 = "Make a Surat Jalan of your selection"; // 선택한 품목에 대하여 화물 인도 지시를 합니다 *feelbuy Make a Delivery Order of your selection
$txt_invn_stockout_34 = "PIC of Delivery"; // 화물 인도 담당자
$txt_invn_stockout_35 = "Order Details"; // 상세 지시서
$txt_invn_stockout_36 = "Ordered"; // 인도 지시일
$txt_invn_stockout_361 = "Sent"; // DO 발송일
$txt_invn_stockout_37 = "Checked"; // 인도 지시 확인일
$txt_invn_stockout_38 = "Done"; // 인도 완료일
$txt_invn_stockout_39 = "Process"; // 처리 상태
$txt_invn_stockout_390 = "Undelivered"; // 미인도
$txt_invn_stockout_391 = "Order Checked"; // 인도 지시중
$txt_invn_stockout_392 = "In Process"; // 인도 처리중
$txt_invn_stockout_393 = "Delivered"; // 인도 완료
$txt_invn_stockout_39x = "Cancel"; // 인도 취소
$txt_invn_stockout_40 = "Recipient"; // 수령자
$txt_invn_stockout_41 = "No Shop Selected"; // 매장 미지정
$txt_invn_stockout_42 = "Departure"; // 출발지
$txt_invn_stockout_421 = "Take-off"; // 출발
$txt_invn_stockout_43 = "Destination"; // 도착지
$txt_invn_stockout_431 = "Arrival"; // 도착
$txt_invn_stockout_44 = "Under Way"; // 인도중
$txt_invn_stockout_45 = "Average Wait"; // 평균 소요 시간
$txt_invn_stockout_46 = "Wait"; // 소요 시간
$txt_invn_stockout_47 = "Handling Charges"; // 소요 비용
$txt_invn_stockout_48 = "Surat Jalan Sent";
$txt_invn_stockout_49 = "Send Surat Jalan";
$txt_invn_stockout_50 = "Print Surat Jalan";

$txt_invn_stockout_chk01 = "Please select Shop for Stock output."; // 출고지(매장)를 선택하세요.


// inventory > return
$txt_invn_return_01 = "Total Price"; // 총반품액
$txt_invn_return_02 = "Date of Return"; // 반품일
$txt_invn_return_02s = "Return Date"; // 반품일
$txt_invn_return_03 = "Process"; // 처 리
$txt_invn_return_04 = "Paid"; // 수금 완료
$txt_invn_return_05 = "Return"; // 반 품
$txt_invn_return_06 = "Lost"; // 분 실
$txt_invn_return_07 = "Broken"; // 파 손
$txt_invn_return_08 = "Others"; // 기 타
$txt_invn_return_09 = "In Prc."; // 처리중
$txt_invn_return_09s = "In Prc."; // 처리중
$txt_invn_return_10 = "Unpaid"; // 미 수
$txt_invn_return_11 = "Submit"; // 반품 처리
$txt_invn_return_12 = "Submit"; // 수금 처리
$txt_invn_return_13 = "Date of Payment"; // 수금일
$txt_invn_return_14 = "Why"; // 반품 사유


// inventory > payment
$txt_invn_payment_01 = "Payment"; // 지불결제 리스트
$txt_invn_payment_02 = "Total"; // 총 결제액
$txt_invn_payment_03 = "Date of Payment"; // 결제일
$txt_invn_payment_03s = "Pay. Date"; // 결제일
$txt_invn_payment_04 = "Cancel"; // 결제 취소
$txt_invn_payment_05 = "Unpaid"; // 미지불
$txt_invn_payment_05s = "Unpaid"; // 미지불
$txt_invn_payment_06 = "Paid"; // 지불완료
$txt_invn_payment_07 = "Pay your selection"; // 선택한 항목 지불결제하기
$txt_invn_payment_08 = "Payment"; // 지불 처리
$txt_invn_payment_09 = "Payment"; // 지불하기
$txt_invn_payment_10 = "Method of Payment"; // 결제 유형
$txt_invn_payment_10s = "Pay. Method"; // 결제 유형
$txt_invn_payment_10_1 = "Cash"; // 현금
$txt_invn_payment_10_2 = "Bank Transfer"; // 은행 송금
$txt_invn_payment_10_3 = "Bank Account"; // 계좌 이체
$txt_invn_payment_10_4 = "Credit Card"; // 신용 카드
$txt_invn_payment_10_5 = "Voucher"; // 바우처
$txt_invn_payment_10_6 = "Others"; // 기 타
$txt_invn_payment_11 = "Bank"; // 결제 은행
$txt_invn_payment_12 = "Cust. Bank"; // 고객 은행
$txt_invn_payment_13 = "Remit. No."; // 송금 번호
$txt_invn_payment_14 = "Update"; // 결제 정보 변경
$txt_invn_payment_15 = "Pay. Code"; // 결제 코드
$txt_invn_payment_16 = "Remit. Bank"; // 송금 은행
$txt_invn_payment_17 = "Select Bank"; // 은행 선택
$txt_invn_payment_18 = "Credit Card"; // 카드 선택
$txt_invn_payment_19 = "Submit"; // 수불 처리
$txt_invn_payment_20 = "Select Switching"; // 카드 결제기 선택
$txt_invn_payment_21 = "To Bank"; // 수신 은행 계좌
$txt_invn_payment_22 = "In Money"; // 실 결제액
$txt_invn_payment_23 = "Uncollected"; // 미수금
$txt_invn_payment_24 = "Receivable"; // 미수금
$txt_invn_payment_25 = "Settlement"; // 정산
$txt_invn_payment_26 = "Settled"; // 수금
$txt_invn_payment_27 = "Collected"; // 수금
$txt_invn_payment_28 = "Transfer"; // 송금


// inventory > purchase
$txt_invn_purchase_01 = "Purchase Orders"; // 상품구매 주문 리스트
$txt_invn_purchase_02 = "Place Purchase Order"; // 상품구매 주문 작성
$txt_invn_purchase_03 = "Update Purchase Order"; // 상품구매 주문 수정
$txt_invn_purchase_04 = "Remove Purchase Order"; // 상품구매 주문 삭제
$txt_invn_purchase_05 = "Print Purchase Order"; // 상품구매 주문서 인쇄
$txt_invn_purchase_06 = "Purchase Order No."; // 발주 번호
$txt_invn_purchase_06s = "PO No."; // 발주 번호
$txt_invn_purchase_07 = "Total Amount"; // 발주 총액
$txt_invn_purchase_08 = "Date of Order"; // 발주일
$txt_invn_purchase_08s = "Ord. Date"; // 발주일
$txt_invn_purchase_09 = "Order"; // 주문하기
$txt_invn_purchase_10 = "New"; // 신규 추가
$txt_invn_purchase_11 = "Submit Purchase Order"; // 상품구매 주문서 발송
$txt_invn_purchase_11pr = "Submit PR Order"; // PR 주문서 발송
$txt_invn_purchase_12 = "Add to Purchase Order List"; // 상품구매 주문 리스트에 추가
$txt_invn_purchase_12pr = "Add to PR List"; // PR 리스트에 추가
$txt_invn_purchase_13 = "Purchase Order List"; // 상품구매 주문 리스트
$txt_invn_purchase_13pr = "PR List"; // PR 리스트


// inventory > zone_option
$txt_invn_zonopt_01 = "Product Options"; // 상품 옵션 항목 리스트
$txt_invn_zonopt_02 = "Create Table"; // 테이블 생성
$txt_invn_zonopt_03 = "Option Name"; // 옵션 이름
$txt_invn_zonopt_04 = "Option Fields"; // 옵션 항목
$txt_invn_zonopt_05 = "Use comma(,) as a separator."; // 콤마(,)를 구분자로 이용하세요.

$txt_invn_zonopt_chk01 = "Please create Table."; // 관련 테이블을 생성하셔야 합니다.


// inventory > zone_gudang
$txt_invn_gudang_01 = "Warehouses"; // 창고 리스트
$txt_invn_gudang_02 = "Add Warehouse"; // 창고 등록하기
$txt_invn_gudang_03 = "Update Warehouse"; // 창고 수정하기
$txt_invn_gudang_04 = "Remove Warehouse"; // 창고 삭제하기
$txt_invn_gudang_05 = "W. Code"; // 창고 코드
$txt_invn_gudang_06 = "Warehouse Name"; // 창고 이름
$txt_invn_gudang_07 = "Warehouse Manager"; // 창고 관리자

$txt_invn_gudang_chk01 = "Please enter Warehouse Name."; // 창고 이름을 입력하세요.


// finance > cost
$txt_fin_cost_01 = "Request to Pay"; // 지출 결의
$txt_fin_cost_02 = "Select Field"; // 계정항목 선택
$txt_fin_cost_03 = "Amount"; // 지출 금액
$txt_fin_cost_04 = "Description"; // 지출 내역
$txt_fin_cost_05 = "Remarks"; // 참 고
$txt_fin_cost_06 = "Date"; // 날 짜
$txt_fin_cost_07 = "Acc Code"; // 계정코드

$txt_fin_cost_chk01 = "Please select Accounting Data Field"; // 계정항목을 선택하세요.
$txt_fin_cost_chk02 = "Please insert Amount."; // 금액을 입력하세요.
$txt_fin_cost_chk03 = "Please insert Accounting Data Definition."; // 내역을 입력하세요.


// finance > income
$txt_fin_income_01 = "Into Revenue"; // 수익 처리
$txt_fin_income_03 = "Amount"; // 수익 금액
$txt_fin_income_04 = "Description"; // 수익 내역


// finance > balance
$txt_fin_balance_01 = "Credit"; // 수 입
$txt_fin_balance_02 = "Debit"; // 지 출
$txt_fin_balance_03 = "Balance"; // 잔 액
$txt_fin_balance_04 = "Accumulated Total"; // 누적 합계
$txt_fin_balance_05 = "Total"; // 합 계
$txt_fin_balance_06 = "Accounting Data Fields"; // 계정항목


// hr > member (basic)
$txt_hr_member_01 = "Employees"; // 사원 리스트
$txt_hr_member_02 = "Register Employee"; // 사원 등록하기
$txt_hr_member_03 = "Update Employee Profile"; // 사원 수정하기
$txt_hr_member_04 = "Remove Employee Profile"; // 사원 삭제하기
$txt_hr_member_05 = "Mb. Code"; // 사원 코드
$txt_hr_member_06 = "Website ID"; // 웹사이트 ID
$txt_hr_member_07 = "Member Level"; // 사원 등급
$txt_hr_member_08 = "Company/Organization"; // 회사/단체명
$txt_hr_member_09 = "Sync to Website"; // 웹사이트 DB 연동 여부
$txt_hr_member_10 = "Unlinked"; // 단 절
$txt_hr_member_11 = "Duplicated"; // 중 복
$txt_hr_member_12 = "Merged"; // 통 합
$txt_hr_member_13 = "Mileage Point"; // 마일리지 포인트
$txt_hr_member_14 = "Reseller"; // 리셀러
$txt_hr_member_15 = "Non-reseller"; // 일반 사원
$txt_hr_member_16 = "News Letter"; // 뉴스 레터
$txt_hr_member_17 = "Join"; // 가 입
$txt_hr_member_18 = "Cancel"; // 해 제
$txt_hr_member_31 = "Nick Name"; // 영문 이름
$txt_hr_member_32 = "Marital Status"; // 결혼 여부
$txt_hr_member_321 = "Single"; // 미 혼
$txt_hr_member_322 = "Married"; // 기 혼
$txt_hr_member_323 = "Divorced"; // 이 혼
$txt_hr_member_324 = "Bereaved"; // 사 별
$txt_hr_member_325 = "Remarried"; // 재 혼
$txt_hr_member_3291 = "Retirement Date"; // 퇴사일
$txt_hr_member_3292 = "Remarks"; // 비 고
$txt_hr_member_3293 = "Passed Away"; // 소 천
$txt_hr_member_3294 = "Reason of Retirement"; // 퇴직 사유
$txt_hr_member_3295 = "Retirement"; // 퇴직

$txt_hr_member_33 = "Family Head"; // 세대주 여부
$txt_hr_member_331 = "Head"; // 세대주
$txt_hr_member_332 = "Member"; // 세대원
$txt_hr_member_333 = "Single"; // 단독 세대주
$txt_hr_member_334 = "Another Head"; // 세대 분리
$txt_hr_member_335 = "Number"; // 세대원수
$txt_hr_member_336 = "Person(s)"; // 명
$txt_hr_member_34 = "Department"; // 소 속
$txt_hr_member_341 = "Adult"; // 장년부
$txt_hr_member_342 = "Young"; // 청년부
$txt_hr_member_343 = "Collegeate"; // 대학부
$txt_hr_member_344 = "Schooler"; // 주일학교
$txt_hr_member_345 = "Unknown"; // 기 타
$txt_hr_member_346 = "Undefined"; // 미소속
$txt_hr_member_35 = "Community"; // 공동체 모임
$txt_hr_member_36 = "New Family"; // 새가족 모임
$txt_hr_member_37 = "Faith Level"; // 신 급
$txt_hr_member_371 = "Baptized"; // 세 례
$txt_hr_member_372 = "B. Suckling"; // 영아세례
$txt_hr_member_373 = "B. Infant"; // 유아세례
$txt_hr_member_374 = "Converted"; // 입 교
$txt_hr_member_375 = "B. Immersion"; // 침 례
$txt_hr_member_376 = "Learned"; // 학 습
$txt_hr_member_38 = "Date of Regis."; // 입사 등록일
$txt_hr_member_380 = "Retired"; // 퇴사
$txt_hr_member_381 = "Non-regular"; // 비정규직
$txt_hr_member_382 = "Regular"; // 정규직
$txt_hr_member_383 = "Temporary"; // 
$txt_hr_member_39 = "Passport No."; // 여권 번호
$txt_hr_member_40 = "Expiry Date"; // 만료여권 만료일
$txt_hr_member_41 = "Nationality"; // 국 적
$txt_hr_member_42 = "Visa"; // 비자 종류
$txt_hr_member_43 = "Spouse"; // 배우자
$txt_hr_member_44 = "Photo"; // 사진
$txt_hr_member_45 = "Division"; // 부 서

$txt_hr_member_60 = "Weekly Report"; // 순장 주간 보고서
$txt_hr_member_611 = "Sunday"; // 주일 출석
$txt_hr_member_612 = "Weekday"; // 순예배 출석
$txt_hr_member_621 = "Roll"; // 여부
$txt_hr_member_6211 = "Yes"; // 출석
$txt_hr_member_6212 = "No"; // 결석
$txt_hr_member_622 = "Why"; // 사유
$txt_hr_member_63 = "Remarks"; // 조치사항
$txt_hr_member_631 = "by Head"; // 순장 조치사항
$txt_hr_member_632 = "by Pastor"; // 담당 교역자 조치사항
$txt_hr_member_64 = "Prayer"; // 기도 제목
$txt_hr_member_65 = "Submit"; // 전 송

$txt_hr_member_chk01 = "Please select System."; // 시스템을 선택하세요.


// hr > member (detail)
$txt_tab_hr_member_01 = "General"; // 일 반

$txt_tab_hr_member_C = "Join/Retirement"; // 입사/퇴직
$txt_tab_hr_member_C01 = "Retirement Allowance"; // 퇴직금
$txt_tab_hr_member_C02 = "Join Date"; // 입사일
$txt_tab_hr_member_C03 = "Retirement Date"; // 퇴사일
$txt_tab_hr_member_C04 = "Pay Date"; // 지급일
$txt_tab_hr_member_C05 = "Special Allowance"; // 특별 퇴직금
$txt_tab_hr_member_C06 = "Total Allowance"; // 총 퇴직금

$txt_tab_hr_member_A = "Address"; // 주 소
$txt_tab_hr_member_A01 = "Family Address"; // 가족단위로 수정

$txt_tab_hr_member_02 = "Family"; // 가 족
$txt_tab_hr_member_0201 = "Rel."; // 관 계
$txt_tab_hr_member_0202 = "Age"; // 나 이
$txt_tab_hr_member_0203 = "Edu."; // 학 력
$txt_tab_hr_member_0204 = "Religion"; // 종 교
$txt_tab_hr_member_0210 = "Relation"; // 세대주와의 관계
$txt_tab_hr_member_0210M = "Husband"; // 남 편
$txt_tab_hr_member_0210F = "Wife"; // 아 내
$txt_tab_hr_member_0211 = "Parent"; // 부 모
$txt_tab_hr_member_0211M = "Father"; // 부
$txt_tab_hr_member_0211F = "Mother"; // 모
$txt_tab_hr_member_0212 = "Child"; // 자 녀
$txt_tab_hr_member_0212M = "Son"; // 아 들
$txt_tab_hr_member_0212F = "Daughter"; // 딸
$txt_tab_hr_member_0213 = "Relative"; // 친 지
$txt_tab_hr_member_0214 = "Friend"; // 친 구
$txt_tab_hr_member_0219 = "Undefined"; // 기 타
$txt_tab_hr_member_02x = "Enter"; // 직접 입력
$txt_tab_hr_member_03 = "Vocation/School"; // 직장/학교
$txt_tab_hr_member_0301 = "Vocation"; // 직 장
$txt_tab_hr_member_0302 = "Work Type"; // 직 종
$txt_tab_hr_member_0303 = "Job"; // 직 업
$txt_tab_hr_member_0304 = "Company"; // 직장명
$txt_tab_hr_member_0305 = "Introduction"; // 회사 소개
$txt_tab_hr_member_0306 = "From"; // 입 사
$txt_tab_hr_member_0307 = "Until"; // 퇴 사
$txt_tab_hr_member_0308 = "Contractor"; // 용역

$txt_tab_hr_member_0351 = "School"; // 학 교
$txt_tab_hr_member_0352 = "School Name"; // 학교명
$txt_tab_hr_member_0353 = "Degree"; // 구 분
$txt_tab_hr_member_03531 = "Kinder G"; // 유치원
$txt_tab_hr_member_03532 = "Primary S"; // 초등학교
$txt_tab_hr_member_03533 = "Middle S"; // 중학교
$txt_tab_hr_member_03534 = "High S"; // 고등학교
$txt_tab_hr_member_03535 = "College (2Y)"; // 대학(2년)
$txt_tab_hr_member_03536 = "College (3Y)"; // 대학(2년)
$txt_tab_hr_member_03537 = "Univ. (Bc)"; // 대학교(학사)
$txt_tab_hr_member_03538 = "Univ. (Ms)"; // 대학원(석사)
$txt_tab_hr_member_03539 = "Univ. (Dr)"; // 대학원(박사)
$txt_tab_hr_member_0354 = "Location"; // 학교소재지
$txt_tab_hr_member_0355 = "Major/Dept"; // 전공/과
$txt_tab_hr_member_0356 = "Entered"; // 입 학
$txt_tab_hr_member_0357 = "Graduated"; // 졸 업
$txt_tab_hr_member_0358 = "Status"; // 졸업 여부
$txt_tab_hr_member_03580 = "Dropout"; // 중 퇴
$txt_tab_hr_member_03581 = "Enrolled"; // 재학중
$txt_tab_hr_member_03582 = "Completed"; // 졸 업

$txt_tab_hr_member_04 = "Religion"; // 종 교
$txt_tab_hr_member_0401 = "Protestant"; // 개신교
$txt_tab_hr_member_0402 = "Catholic"; // 카톨릭
$txt_tab_hr_member_0403 = "Budhism"; // 불 교
$txt_tab_hr_member_0404 = "Islam"; // 이슬람교
$txt_tab_hr_member_0405 = "Hindism"; // 힌두교
$txt_tab_hr_member_0409 = "Msc."; // 기 타
$txt_tab_hr_member_0421 = "Church Name"; // 교회/단체
$txt_tab_hr_member_0422 = "Sect"; // 교파/교단
$txt_tab_hr_member_0423 = "Location"; // 국가/지역
$txt_tab_hr_member_0424 = "Converted"; // 입교년도
$txt_tab_hr_member_0425 = "Baptized"; // 수세년도
$txt_tab_hr_member_0426 = "Expelled"; // 제적년도
$txt_tab_hr_member_0427 = "Expelled Reason"; // 제적사유
$txt_tab_hr_member_0428 = "Church"; // 본교회
$txt_tab_hr_member_0429 = "Title"; // 직 분
$txt_tab_hr_member_0430 = "Senior Pastor"; // 담임목사

$txt_tab_hr_member_05 = "Training"; // 훈련/활동
$txt_tab_hr_member_0501 = "Previous Corporate"; // 이전 회사
$txt_tab_hr_member_0502 = "Corporate Name"; // 회사 이름
$txt_tab_hr_member_0503 = "Evaulation"; // 항목별 평가
$txt_tab_hr_member_0504 = "Status"; // 수료 여부
$txt_tab_hr_member_05040 = "Dropout"; // 미수료
$txt_tab_hr_member_05041 = "Enrolled"; // 수료중
$txt_tab_hr_member_05042 = "Completed"; // 수 료
$txt_tab_hr_member_0506 = "Record"; // 점 수
$txt_tab_hr_member_0507 = "Credit"; // 평 가
$txt_tab_hr_member_0508 = "Remarks"; // 참고 사항
$txt_tab_hr_member_0509 = "Director Comments"; // 이사 견해

$txt_tab_hr_member_06 = "Specifics"; // 특기사항
$txt_tab_hr_member_0601 = "Guide"; // 인도자
$txt_tab_hr_member_0602 = "Blood Type"; // 혈액형
$txt_tab_hr_member_0603 = "Wedding Anniversary"; // 결혼 기념일
$txt_tab_hr_member_0604 = "Financial Status"; // 가정 형편
$txt_tab_hr_member_0605 = "Hobby"; // 취 미
$txt_tab_hr_member_0606 = "Talent"; // 특 기
$txt_tab_hr_member_0607 = "Certificate"; // 자격증
$txt_tab_hr_member_0608 = "Health"; // 건 강
$txt_tab_hr_member_0609 = "Car Lisence No."; // 차량 번호 
$txt_tab_hr_member_0610 = "Parking Lot No."; // 주차장 번호

$txt_tab_hr_member_07 = "Wages"; // 급 여
$txt_tab_hr_member_07s = "Wages"; // 급여
$txt_tab_hr_member_0701 = "M-Y"; // 연/월
$txt_tab_hr_member_0702 = "Type"; // 급여 구분
$txt_tab_hr_member_07021 = "Salary"; // 정기 급여
$txt_tab_hr_member_07022 = "Incentive"; // 인센티브
$txt_tab_hr_member_0703 = "Payroll Code"; // 임금 코드
$txt_tab_hr_member_0704 = "Avr. Wage"; // 평균 급여
$txt_tab_hr_member_0705 = "Incentive"; // 인센티브
$txt_tab_hr_member_0706 = "Bonus"; // 보너스
$txt_tab_hr_member_0707 = "Deduction"; // 공 제
$txt_tab_hr_member_0708 = "Offset"; // 급여 조정
$txt_tab_hr_member_0709 = "Tax"; // 세금
$txt_tab_hr_member_0710 = "Wage"; // 확정 급여
$txt_tab_hr_member_0711 = "Payment"; // 지급액
$txt_tab_hr_member_0712 = "Diffrence"; // 지급 차액
$txt_tab_hr_member_0713 = "Due Date"; // 급여일
$txt_tab_hr_member_0714 = "Pay Date"; // 지급일

$txt_tab_hr_member_08 = "Works"; // 근 태

$txt_tab_hr_member_09 = "Updates"; // 변경사항
$txt_tab_hr_member_0901 = "Date"; // 변경일
$txt_tab_hr_member_0902 = "Status"; // 사원 구분
$txt_tab_hr_member_09021 = "New Employee"; // 새가족
$txt_tab_hr_member_09022 = "Employee"; // 사 원
$txt_tab_hr_member_09023 = "Non-employee"; // 퇴 사

$txt_tab_hr_member_chk01 = "Please input Amount."; // 금액을 입력하셔야 합니다.
$txt_tab_hr_member_chk02 = "Please input Name"; // 아래에 이름을 직접 입력하세요.
$txt_tab_hr_member_chk03 = "Do you want to finish calculating?"; // 계수를 완료하시겠습니까?
$txt_tab_hr_member_chk04 = "Do you want to delete this?"; // 삭제하시겠습니까?


// hr > work attitudes
$txt_hr_work_01 = "Work Attitudes"; // 근태 관리
$txt_hr_work_011 = "Attendance Book"; // 직원 출근부
$txt_hr_work_02 = "NIK"; // NIK
$txt_hr_work_03 = "Date"; // 날짜
$txt_hr_work_04 = "Shift"; // 구분
$txt_hr_work_05 = "Work Time"; // 근무 시간대
$txt_hr_work_06 = "IN"; // 출근
$txt_hr_work_07 = "OUT"; // 퇴근
$txt_hr_work_08 = "Erl In"; // 조기 출근
$txt_hr_work_09 = "Late"; // 지각
$txt_hr_work_10 = "Erl Out"; // 조기 퇴근
$txt_hr_work_11 = "Overwork"; // 잔업
$txt_hr_work_12 = "Work Hours"; // 근무 시간
$txt_hr_work_13 = "Explanation"; // 증명서
$txt_hr_work_14 = "Total Work"; //  총 근무
$txt_hr_work_15 = "Days"; // 일
$txt_hr_work_16 = "DUTY"; // 근무여부
$txt_hr_work_161 = "ON"; // 근무
$txt_hr_work_162 = "OFF"; // 비번
$txt_hr_work_17 = "OFF-DUTY"; // 비번 사유
$txt_hr_work_171 = "Sunday"; // 휴일
$txt_hr_work_172 = "Holiday"; // 개인 휴가
$txt_hr_work_173 = "Hari Raya"; // 르바란 연휴
$txt_hr_work_174 = "Recommended"; // 권장 휴가
$txt_hr_work_175 = "Annual Leave"; // 엱차
$txt_hr_work_176 = "Maternity Leave"; // 출산 휴가
$txt_hr_work_177 = "Marital Leave"; // 결혼 휴가
$txt_hr_work_178 = "Mourning Leave (Family)"; // 상조 휴가
$txt_hr_work_179 = "Sick Leave"; // 병가
$txt_hr_work_18 = "Nonattendance Reason"; // 결근 사유
$txt_hr_work_181 = "Forgot Report"; // 출근기록 상실
$txt_hr_work_182 = "Absence without Report"; // 무단 결근
$txt_hr_work_183 = "Not bring Report"; // 출근기록 미지참
$txt_hr_work_184 = "Outing / Duty"; // 외출 / 공무 
$txt_hr_work_185 = "System Error"; // 시스템 오류
$txt_hr_work_19 = "Erlier Outing Allowed"; // 조퇴
$txt_hr_work_20 = "Warning"; // 경고
$txt_hr_work_21 = "Permitted"; // 허가


// chmember > group, district
$txt_ch_group_01 = "$ch_comm_cug10"." List"; // 구역 리스트
$txt_ch_group_02 = "Add "."$ch_comm_cug10"; // 구역 등록
$txt_ch_group_03 = "Update "."$ch_comm_cug10"; // 구역 정보 수정
$txt_ch_group_04 = "Delete "."$ch_comm_cug10"; // 구역 삭제
$txt_ch_group_05 = "$ch_comm_cug10"." Name"; // 구역 이름
$txt_ch_group_06 = "$ch_comm_cug10"." Category"; // 구역 카테고리
$txt_ch_group_07 = "About"; // 간략 소개
$txt_ch_group_08 = "Details"; // 상세 소개
$txt_ch_group_09 = "Activation"; // 활성화
$txt_ch_group_31 = "$ch_comm_dir20"." List"; // 지역 리스트


// chmember > member (basic)
$txt_ch_member_01 = "Members"; // 성도 리스트
$txt_ch_member_02 = "Add Member Profile"; // 성도 등록하기
$txt_ch_member_03 = "Update Member Profile"; // 성도 수정하기
$txt_ch_member_04 = "Remove Member Profile"; // 성도 삭제하기
$txt_ch_member_05 = "Mb. Code"; // 성도 코드
$txt_ch_member_06 = "Website ID"; // 웹사이트 ID
$txt_ch_member_07 = "Member Level"; // 성도 등급
$txt_ch_member_08 = "Comapny/Organization"; // 회사/단체명
$txt_ch_member_09 = "Sync to Website"; // 웹사이트 DB 연동 여부
$txt_ch_member_10 = "Unlinked"; // 단 절
$txt_ch_member_11 = "Duplicated"; // 중 복
$txt_ch_member_12 = "Merged"; // 통 합
$txt_ch_member_13 = "Mileage Point"; // 마일리지 포인트
$txt_ch_member_14 = "Reseller"; // 리셀러
$txt_ch_member_15 = "Non-reseller"; // 일반 성도
$txt_ch_member_16 = "News Letter"; // 뉴스 레터
$txt_ch_member_17 = "Join"; // 가 입
$txt_ch_member_18 = "Cancel"; // 해 제
$txt_ch_member_31 = "Nick Name"; // 영문 이름
$txt_ch_member_32 = "Marital Status"; // 결혼 여부
$txt_ch_member_321 = "Single"; // 미 혼
$txt_ch_member_322 = "Married"; // 기 혼
$txt_ch_member_323 = "Divorced"; // 이 혼
$txt_ch_member_324 = "Bereaved"; // 사 별
$txt_ch_member_325 = "Remarried"; // 재 혼
$txt_ch_member_3291 = "Expelled Date"; // 교회 제적일
$txt_ch_member_3292 = "Remarks"; // 비 고
$txt_ch_member_3293 = "Passed Away"; // 소 천
$txt_ch_member_3294 = "Cause of Exp."; // 제적 사유

$txt_ch_member_33 = "Family Head"; // 세대주 여부
$txt_ch_member_331 = "Head"; // 세대주
$txt_ch_member_332 = "Member"; // 세대원
$txt_ch_member_333 = "Single"; // 단독 세대주
$txt_ch_member_334 = "Another Head"; // 세대 분리
$txt_ch_member_335 = "Number"; // 세대원수
$txt_ch_member_336 = "Person(s)"; // 명
$txt_ch_member_34 = "Age Group"; // 소 속
$txt_ch_member_341 = "Adult"; // 장년부
$txt_ch_member_342 = "Young"; // 청년부
$txt_ch_member_343 = "Collegeate"; // 대학부
$txt_ch_member_344 = "Schooler"; // 주일학교
$txt_ch_member_345 = "Unknown"; // 기 타
$txt_ch_member_346 = "Undefined"; // 미소속
$txt_ch_member_35 = "Community"; // 공동체 모임
$txt_ch_member_36 = "New Family"; // 새가족 모임
$txt_ch_member_37 = "Faith Level"; // 신 급
$txt_ch_member_371 = "Baptized"; // 세 례
$txt_ch_member_372 = "B. Suckling"; // 영아세례
$txt_ch_member_373 = "B. Infant"; // 유아세례
$txt_ch_member_374 = "Converted"; // 입 교
$txt_ch_member_375 = "B. Immersion"; // 침 례
$txt_ch_member_376 = "Learned"; // 학 습
$txt_ch_member_38 = "Date of Regis."; // 교회 등록일
$txt_ch_member_380 = "Crossed-out"; // 제적교인
$txt_ch_member_381 = "Non-member"; // 미등록
$txt_ch_member_382 = "Member"; // 등록교인
$txt_ch_member_39 = "Passport No."; // 여권 번호
$txt_ch_member_40 = "Expiry Date"; // 만료여권 만료일
$txt_ch_member_41 = "Nationality"; // 국 적
$txt_ch_member_42 = "Visa"; // 비자 종류
$txt_ch_member_43 = "Spouse"; // 배우자
$txt_ch_member_44 = "Photo"; // 사진

$txt_ch_member_60 = "Weekly Report"; // 주간 보고서
$txt_ch_member_611 = "Sunday"; // 주일 출석
$txt_ch_member_612 = "Weekday"; // 예배 출석
$txt_ch_member_621 = "Roll"; // 여부
$txt_ch_member_6211 = "Yes"; // 출석
$txt_ch_member_6212 = "No"; // 결석
$txt_ch_member_622 = "Why"; // 사유
$txt_ch_member_63 = "Remarks"; // 조치사항
$txt_ch_member_631 = "by Head"; // 조치사항
$txt_ch_member_632 = "by Pastor"; // 담당 교역자 조치사항
$txt_ch_member_64 = "Prayer"; // 기도 제목
$txt_ch_member_65 = "Submit"; // 전 송

$txt_ch_member_chk01 = "Please select System."; // 시스템을 선택하세요.


// chmember > member (detail)
$txt_tab_member_01 = "General"; // 일 반
$txt_tab_member_A = "Address"; // 주 소
$txt_tab_member_A01 = "Family Address"; // 가족단위로 수정

$txt_tab_member_02 = "Family"; // 가 족
$txt_tab_member_0201 = "Rel."; // 관 계
$txt_tab_member_0202 = "Age"; // 나 이
$txt_tab_member_0203 = "Edu."; // 학 력
$txt_tab_member_0204 = "Religion"; // 종 교
$txt_tab_member_0210 = "Relation"; // 세대주와의 관계
$txt_tab_member_0210M = "Husband"; // 남 편
$txt_tab_member_0210F = "Wife"; // 아 내
$txt_tab_member_0211 = "Parent"; // 부 모
$txt_tab_member_0211M = "Father"; // 부
$txt_tab_member_0211F = "Mother"; // 모
$txt_tab_member_0212 = "Child"; // 자 녀
$txt_tab_member_0212M = "Son"; // 아 들
$txt_tab_member_0212F = "Daughter"; // 딸
$txt_tab_member_0213 = "Relative"; // 친 지
$txt_tab_member_0214 = "Friend"; // 친 구
$txt_tab_member_0219 = "Undefined"; // 기 타
$txt_tab_member_02x = "Enter"; // 직접 입력
$txt_tab_member_03 = "Work/Study"; // 직장/학교
$txt_tab_member_0301 = "Work"; // 직 장
$txt_tab_member_0302 = "Work Type"; // 직 종
$txt_tab_member_0303 = "Job"; // 직 업
$txt_tab_member_0304 = "Company"; // 직장명
$txt_tab_member_0305 = "Introduction"; // 회사 소개
$txt_tab_member_0306 = "From"; // 입 사
$txt_tab_member_0307 = "Until"; // 퇴 사

$txt_tab_member_0351 = "Study"; // 학 교
$txt_tab_member_0352 = "School Name"; // 학교명
$txt_tab_member_0353 = "Degree"; // 구 분
$txt_tab_member_03531 = "Kinder G"; // 유치원
$txt_tab_member_03532 = "Primary S"; // 초등학교
$txt_tab_member_03533 = "Middle S"; // 중학교
$txt_tab_member_03534 = "High S"; // 고등학교
$txt_tab_member_03535 = "College (2Y)"; // 대학(2년)
$txt_tab_member_03536 = "College (3Y)"; // 대학(2년)
$txt_tab_member_03537 = "Univ. (Bc)"; // 대학교(학사)
$txt_tab_member_03538 = "Univ. (Ms)"; // 대학원(석사)
$txt_tab_member_03539 = "Univ. (Dr)"; // 대학원(박사)
$txt_tab_member_0354 = "Location"; // 학교소재지
$txt_tab_member_0355 = "Major/Dept"; // 전공/과
$txt_tab_member_0356 = "Entered"; // 입 학
$txt_tab_member_0357 = "Graduated"; // 졸 업
$txt_tab_member_0358 = "Status"; // 졸업 여부
$txt_tab_member_03580 = "Dropout"; // 중 퇴
$txt_tab_member_03581 = "Enrolled"; // 재학중
$txt_tab_member_03582 = "Completed"; // 졸 업

$txt_tab_member_04 = "Baptism"; // 신 급
$txt_tab_member_0401 = "Protestant"; // 개신교
$txt_tab_member_0402 = "Catholic"; // 카톨릭
$txt_tab_member_0403 = "Budhism"; // 불 교
$txt_tab_member_0404 = "Islam"; // 이슬람교
$txt_tab_member_0405 = "Hindism"; // 힌두교
$txt_tab_member_0409 = "Msc."; // 기 타
$txt_tab_member_0421 = "Church Name"; // 교회/단체
$txt_tab_member_0422 = "Sect"; // 교파/교단
$txt_tab_member_0423 = "Location"; // 국가/지역
$txt_tab_member_0424 = "Converted"; // 입교년도
$txt_tab_member_0425 = "Baptized"; // 수세년도
$txt_tab_member_0426 = "Expelled"; // 제적년도
$txt_tab_member_0427 = "Expelled Reason"; // 제적사유
$txt_tab_member_0428 = "Church"; // 본교회
$txt_tab_member_0429 = "Title"; // 직 분
$txt_tab_member_0430 = "Senior Pastor"; // 담임목사

$txt_tab_member_05 = "Training"; // 훈련/활동
$txt_tab_member_0501 = "Previous Church"; // 이전 교회
$txt_tab_member_0502 = "Church Name"; // 교회 이름
$txt_tab_member_0503 = "Evaulation"; // 항목별 평가
$txt_tab_member_0504 = "Status"; // 수료 여부
$txt_tab_member_05040 = "Dropout"; // 미수료
$txt_tab_member_05041 = "Enrolled"; // 수료중
$txt_tab_member_05042 = "Completed"; // 수 료
$txt_tab_member_0506 = "Cume"; // 점 수
$txt_tab_member_0507 = "Credit"; // 평 가
$txt_tab_member_0508 = "Remarks"; // 참고 사항
$txt_tab_member_0509 = "Pastor Comments"; // 교역자 견해

$txt_tab_member_06 = "Specifics"; // 특기사항
$txt_tab_member_0601 = "Guide"; // 인도자
$txt_tab_member_0602 = "Blood Type"; // 혈액형
$txt_tab_member_0603 = "Wedding Anniversary"; // 결혼 기념일
$txt_tab_member_0604 = "Financial Status"; // 가정 형편
$txt_tab_member_0605 = "Hobby"; // 취 미
$txt_tab_member_0606 = "Talent"; // 특 기
$txt_tab_member_0607 = "Special Gift"; // 은 사
$txt_tab_member_0608 = "Health"; // 건 강
$txt_tab_member_0609 = "Car Lisence No."; // 차량 번호 
$txt_tab_member_0610 = "Parking Lot No."; // 주차장 번호

$txt_tab_member_07 = "Offering"; // 헌 금
$txt_tab_member_07s = "Offering"; // 헌금
$txt_tab_member_0701 = "Type"; // 헌금 구분
$txt_tab_member_0702 = "Select Name"; // 헌금자 선택
$txt_tab_member_0703 = "Name"; // 헌금자 이름
$txt_tab_member_0704 = "Input Name"; // 직접 입력
$txt_tab_member_0705 = "Amount"; // 금 액
$txt_tab_member_0706 = "Enter"; // 입 력
$txt_tab_member_0707 = "Submit"; // 계수 완료
$txt_tab_member_0708 = "Anonymous"; // 무 명
$txt_tab_member_0709 = "Offering List"; // 헌금자 리스트
$txt_tab_member_0710 = "Date of Counting"; // 헌금 계수일
$txt_tab_member_0711 = "Total Amount"; // 총 헌금 합계
$txt_tab_member_0712 = "Report of Offering"; // 헌금 현황 보고
$txt_tab_member_0713 = "Report of Offering"; // 헌금 현황
$txt_tab_member_0714 = "Overall"; // 종합
$txt_tab_member_0715 = "Division"; // 구 분
$txt_tab_member_0716 = "Remarks"; // 비 고
$txt_tab_member_0717 = "Verification"; // 확 인
$txt_tab_member_0718 = "Signature"; // 서명
$txt_tab_member_0719 = "F. Director"; // 재정부장
$txt_tab_member_0720 = "Account"; // 회 계
$txt_tab_member_0721 = "Cashier"; // 현금담당
$txt_tab_member_0722 = "Sub Total"; // 소 계
$txt_tab_member_0723 = "Total"; // 합 계
$txt_tab_member_0724 = "Date of Offering"; // 헌금일

$txt_tab_member_08 = "Visit"; // 심 방
$txt_tab_member_0801 = "Visit Date"; // 심방 일시
$txt_tab_member_0802 = "Visit Subject"; // 심방 제목/사유
$txt_tab_member_0803 = "Place"; // 심방 장소
$txt_tab_member_0804 = "Visitor(s)"; // 심방자
$txt_tab_member_0805 = "Posting Date"; // 기록일시
$txt_tab_member_0806 = "Writer"; // 기록자
$txt_tab_member_0807 = "Visit Note"; // 심방 메모
$txt_tab_member_0808 = "Hymn"; // 찬 송
$txt_tab_member_0809 = "Prayer"; // 기 도
$txt_tab_member_0810 = "Bible"; // 성 경
$txt_tab_member_0811 = "Worship"; // 인 도

$txt_tab_member_09 = "Updates"; // 변경사항
$txt_tab_member_0901 = "Date"; // 변경일
$txt_tab_member_0902 = "Status"; // 교인 상태
$txt_tab_member_09021 = "New Member"; // 새가족
$txt_tab_member_09022 = "Member"; // 교 인
$txt_tab_member_09023 = "Non-member"; // 제 적

$txt_tab_member_chk01 = "Please input Amount."; // 금액을 입력하셔야 합니다.
$txt_tab_member_chk02 = "Please input Name"; // 아래에 이름을 직접 입력하세요.
$txt_tab_member_chk03 = "Do you want to finish calculating?"; // 계수를 완료하시겠습니까?
$txt_tab_member_chk04 = "Do you want to delete this?"; // 삭제하시겠습니까?


// member > member
$txt_stf_member_01 = "Members"; // 회원 리스트
$txt_stf_member_02 = "Add Member Profile"; // 회원 등록하기
$txt_stf_member_03 = "Update Member Profile"; // 회원 수정하기
$txt_stf_member_04 = "Remove Member Profile"; // 회원 삭제하기
$txt_stf_member_05 = "Mb. Code"; // 회원 코드
$txt_stf_member_06 = "Member ID"; // 회원 ID
$txt_stf_member_07 = "Member Level"; // 회원 등급
$txt_stf_member_08 = "Company/Organization"; // 회사/단체명
$txt_stf_member_09 = "Sync to Website"; // 웹사이트 DB 연동 여부
$txt_stf_member_10 = "Unlinked"; // 단 절
$txt_stf_member_11 = "Duplicated"; // 중 복
$txt_stf_member_12 = "Merged"; // 통 합
$txt_stf_member_13 = "Mileage Point"; // 마일리지 포인트
$txt_stf_member_14 = "Reseller"; // 리셀러
$txt_stf_member_15 = "Non-reseller"; // 일반 회원
$txt_stf_member_16 = "News Letter"; // 뉴스 레터
$txt_stf_member_17 = "Join"; // 가 입
$txt_stf_member_18 = "Cancel"; // 해 제
$txt_stf_member_51 = "Distributors"; // 대리점 리스트
$txt_stf_member_52 = "Add Distributor Profile"; // 대리점 등록하기
$txt_stf_member_53 = "Update Distributor Profile"; // 대리점 수정하기
$txt_stf_member_54 = "Remove Distributor Profile"; // 대리점 삭제하기
$txt_stf_member_55 = "D. Code"; // 대리점 코드
$txt_stf_member_57 = "D. Level"; // 대리점 등급
$txt_stf_member_60 = "Bank Name (Branch)"; // 결제 은행(지점)
$txt_stf_member_61 = "Account Name"; // 예금주
$txt_stf_member_62 = "Account No."; // 계좌 번호

$txt_stf_member_chk01 = "Please select System."; // System을 선택하세요.

// member > staff
$txt_stf_staff_01 = "Employees"; // 사원 리스트
$txt_stf_staff_02 = "Add Profile"; // 사원 등록하기
$txt_stf_staff_03 = "Update Profile"; // 사원 수정하기
$txt_stf_staff_04 = "Remove Profile"; // 사원 삭제하기
$txt_stf_staff_05 = "Warehouse"; // Shop 회원 ID
$txt_stf_staff_06 = "Unknown"; // 해당사항 없음
$txt_stf_staff_061 = "No Contract"; // 해당사항 없음
$txt_stf_staff_07 = "Emp. Code"; // 사원 코드
$txt_stf_staff_08 = "Name"; // 이 름
$txt_stf_staff_09 = "Gender"; // 성 별
$txt_stf_staff_10 = "Male"; // 남
$txt_stf_staff_11 = "Female"; // 여
$txt_stf_staff_12 = "Date of Birth"; // 생년월일
$txt_stf_staff_13 = "Solar"; // 양력
$txt_stf_staff_14 = "Lunar"; // 음력
$txt_stf_staff_15 = "Department"; // 부 서
$txt_stf_staff_16 = "Job Title"; // 직 책
$txt_stf_staff_17 = "Level"; // 직 급
$txt_stf_staff_18 = "Select Branch"; // 지사 선택

$txt_stf_staff_chk01 = "Please Enter Name."; // 이름을 입력하세요.
$txt_stf_staff_chk02 = "Your submittion already exists."; // 입력하신 이름과 동일인이 있습니다.
$txt_stf_staff_chk03 = "Please check and re-enter."; // 확인하시고 다시 입력하여 주십시오.
$txt_stf_staff_chk04 = "Please select Corporate."; // 회사를 선택하세요.


// member > special
$txt_stf_model_01 = "Models"; // 모델 리스트
$txt_stf_model_02 = "Add Model"; // 모델 등록하기
$txt_stf_model_03 = "Update Model"; // 모델 수정하기
$txt_stf_model_04 = "Remove Model"; // 모델 삭제하기
$txt_stf_model_05 = "Shop User ID"; // Shop 회원 ID
$txt_stf_model_06 = "No"; // 해당사항 없음
$txt_stf_model_07 = "Type"; // 계약 유형
$txt_stf_model_07_01 = "Contract"; // 계약직
$txt_stf_model_07_02 = "Freelancer"; // 프리랜서
$txt_stf_model_08 = "Proile"; // 상세 프로필
$txt_stf_model_09 = "Contract Period"; // 계약 기간
$txt_stf_model_10 = "VISA";
$txt_stf_model_11 = "Termination"; // 계약 만료일


// system > client
$txt_sys_client_01 = "System Name"; // System 이름
$txt_sys_client_02 = "Code"; // 코드
$txt_sys_client_03 = "System ID";
$txt_sys_client_04 = "System Level"; // System 등급
$txt_sys_client_05 = "Website"; // 웹사이트
$txt_sys_client_06 = "Post Date"; // 등록일
$txt_sys_client_061 = "Post Date"; // 시스템 등록일
$txt_sys_client_062 = "Last Update"; // 최종 변경일시
$txt_sys_client_07 = "Manager Name"; // 최고관리자 이름
$txt_sys_client_08 = "Phone No."; // 전화번호
$txt_sys_client_09 = "Mobile"; // 휴대폰
$txt_sys_client_10 = "Systems"; // System 리스트
$txt_sys_client_11 = "Add System"; // System 등록하기
$txt_sys_client_12 = "Update System"; // System 수정하기
$txt_sys_client_13 = "Remove System"; // System 삭제하기
$txt_sys_client_14 = "Address"; // 주 소
$txt_sys_client_15 = "Zip Code"; // 우편번호
$txt_sys_client_16 = "Street";
$txt_sys_client_17 = "City, State";
$txt_sys_client_18 = "DB Account"; // DB 계정
$txt_sys_client_19 = "DB Account Name"; // DB명,계정명,비밀번호
$txt_sys_client_20 = "New Password"; // 새 비밀번호
$txt_sys_client_21 = "Re-type"; // 재입력
$txt_sys_client_22 = "Update"; // 변경하기
$txt_sys_client_23 = "Profile"; // 프로필
$txt_sys_client_24 = "Condition"; // 계약관계
$txt_sys_client_25 = "Contact Info."; // 연락정보
$txt_sys_client_26 = "Memo"; // 관리자 메모

$txt_sys_client_chk01 = "Please enter ID."; // ID를 입력하세요.
$txt_sys_client_chk02 = "The ID must be a combination of numbers and letters with 4~12 characters long."; // ID는 4~12자의 영소문자 또는 영소문자와 숫자의 결합이어야 합니다.
$txt_sys_client_chk03 = "The first letter of ID should be an alpahbet."; // ID의 첫글자는 언제나 영소문자여야 합니다.
$txt_sys_client_chk04 = "No space permitted."; // 공백이 허용되지 않습니다.
$txt_sys_client_chk05 = "Please enter Password."; // 비밀번호를 입력하세요.
$txt_sys_client_chk06 = "The password must be at least 4 characters long, may contain lowercase letters (a-z) or numbers."; // 비밀번호는 4~12자의 영문자와 숫자 또는 영문자와 숫자의 결합이어야 합니다.
$txt_sys_client_chk07 = "Please enter System Name."; // 시스템의 Client 이름을 입력하세요.
$txt_sys_client_chk08 = "Please enter Email address."; // E-mail 주소를 입력하세요.
$txt_sys_client_chk09 = "The email address you entered is invalid."; // E-mail 주소의 형식이 틀렸습니다.
$txt_sys_client_chk10 = "Please input the temporary pin code."; // 인증번호를 입력하세요.


// system > user
$txt_sys_user_01 = "System Managers"; // Shop Manager 리스트
$txt_sys_user_02 = "Add System Manager"; // Shop Manager 등록하기
$txt_sys_user_03 = "Update System Manager"; // Shop Manager 수정하기
$txt_sys_user_04 = "Remove System Manager"; // Shop Manager 삭제하기
$txt_sys_user_05 = "Manager ID"; // Manager ID
$txt_sys_user_06 = "Manager Name"; // Manager 이름
$txt_sys_user_07 = "System"; // Shop
$txt_sys_user_08 = "Level"; // Manager 등급
$txt_sys_user_09 = "Last Login"; // 지난 로그인
$txt_sys_user_10 = "Visit"; // 방문수
$txt_sys_user_11 = "Language"; // 사용 언어
$txt_sys_user_12 = "No Login"; // 로그인 기록 없음

$txt_sys_user_chk01 = "Please enter System Manager Name."; // Shop Manager 이름을 입력하세요.
$txt_sys_user_chk02 = "";
$txt_sys_user_chk03 = "Your password is not valid."; // 입력하신 두 비밀번호가 일치하지 않습니다.


// system > church_job category
$txt_sys_chjob_01 = "Type"; // 구 분
$txt_sys_chjob_011 = "Clergymen"; // 교역자
$txt_sys_chjob_012 = "Laity"; // 평신도
$txt_sys_chjob_013 = "Non-Chritian"; // 일반인(태신자)
$txt_sys_chjob_02 = "Code"; // 코 드
$txt_sys_chjob_031 = "Position Name"; // 직위 이름
$txt_sys_chjob_032 = "Post Name"; // 직분 이름
$txt_sys_chjob_033 = "Occupation Jame"; // 직업 이름
$txt_sys_chjob_04 = "Add New Code"; // 코드 등록하기
$txt_sys_chjob_05 = "Update Code"; // 코드 수정하기
$txt_sys_chjob_06 = "Remove Code"; // 코드 삭제하기

$txt_sys_chjob_chk01 = "Please enter Code."; // 코드를 입력하세요.
$txt_sys_chjob_chk02 = "Please enter Nomination."; // 분류명을 입력하세요.
$txt_sys_chjob_chk03 = "Your submittion already exists."; // 동일한 코드가 존재합니다.


// system > tarin_course [*]
$txt_sys_tcourse_01 = "Training/Activity"; // 훈련/활동 과정
$txt_sys_tcourse_02 = "Add Training/Activity"; // 훈련/활동 과정 등록
$txt_sys_tcourse_03 = "Update Training/Activity"; // 훈련/활동 과정 수정
$txt_sys_tcourse_04 = "Delete Training/Activity"; // 훈련/활동 과정 삭제
$txt_sys_tcourse_05 = "Course Code"; // 과정 코드
$txt_sys_tcourse_051 = "Course Category"; // 훈련/활동 카테고리
$txt_sys_tcourse_06 = "Course Name"; // 훈련/활동 이름
$txt_sys_tcourse_07 = "Period No."; // 기 수
$txt_sys_tcourse_08 = "Open"; // 시작일
$txt_sys_tcourse_09 = "Close"; // 수료일
$txt_sys_tcourse_10 = "Lecturer"; // 강 사
$txt_sys_tcourse_11 = "Trainee"; // 수강 대상
$txt_sys_tcourse_12 = "Course Terms"; // 과정 기간
$txt_sys_tcourse_13 = "Class Hours"; // 과정 시간
$txt_sys_tcourse_14 = "Course Details"; // 과정 내용
$txt_sys_tcourse_15 = "Evaluation"; // 평가 항목
$txt_sys_tcourse_1501 = "Attendance"; // 출 석
$txt_sys_tcourse_1502 = "Attitude"; // 태 도
$txt_sys_tcourse_1503 = "Achievement"; // 달성도
$txt_sys_tcourse_1504 = "Knowledge"; // 지 식
$txt_sys_tcourse_1505 = "Test"; // 시 험
$txt_sys_tcourse_1506 = "Assignment"; // 과제물
$txt_sys_tcourse_16 = "Tuition"; // 수강료

$txt_sys_tcourse_chk01 = "Please select Course Category."; // 카테고리를 선택하셔야 합니다.


// system > train_course [church]
$txt_sys_chcourse_1501 = "Attendance"; // 출 석
$txt_sys_chcourse_1502 = "Prayer"; // 기 도
$txt_sys_chcourse_1503 = "Q.T."; // 큐 티
$txt_sys_chcourse_1504 = "Bible"; // 성경지식
$txt_sys_chcourse_1505 = "Test"; // 시 험
$txt_sys_chcourse_1506 = "Assignment"; // 과제물


// system > shop
$txt_sys_shop_01 = "Shops"; // 매장 리스트
$txt_sys_shop_02 = "Add Shop"; // 매장 등록하기
$txt_sys_shop_03 = "Update Shop"; // 매장 수정하기
$txt_sys_shop_04 = "Remove Shop"; // 매장 삭제하기
$txt_sys_shop_05 = "Shop Code"; // 매장 코드
$txt_sys_shop_06 = "Shop Name"; // 매장 이름
$txt_sys_shop_07 = "Shop Type"; // 매장 유형
$txt_sys_shop_071 = "Branch Shop"; // 직영 매장
$txt_sys_shop_072 = "Consignment Store"; // 위탁판매 매장
$txt_sys_shop_073 = "Associate Store"; // 협력 매장
$txt_sys_shop_074 = "Online Shop"; // 온라인 매장
$txt_sys_shop_079 = "Warehouse"; // 창고
$txt_sys_shop_08 = "Shop Manager"; // 관리자
$txt_sys_shop_09 = "On"; // 운영
$txt_sys_shop_10 = "Off"; // 중지
$txt_sys_shop_11 = "On"; // 운영
$txt_sys_shop_12 = "On-line"; // 온라인
$txt_sys_shop_13 = "Off-line"; // 오프라인
$txt_sys_shop_14 = "On/Off-line"; // 온/오프라인
$txt_sys_shop_15 = "Shop Scale"; // 매장 규모별 구분
$txt_sys_shop_151 = "Hypermarket"; // 대형 매장
$txt_sys_shop_152 = "Supermarket"; // 수퍼마켓
$txt_sys_shop_16 = "Area"; // 지역
$txt_sys_shop_17 = "Select Area."; // 지역을 선택하세요.

$txt_sys_shop_chk01 = "Please enter Shop Code."; // 매장 코드를 입력하세요
$txt_sys_shop_chk02 = "The Shop Code must be a combination of numbers and letters with 4~12 characters long."; // 매장 코드는 4~12자의 영소문자 또는 영소문자와 숫자의 결합이어야 합니다.
$txt_sys_shop_chk03 = "The first letter of Shop Code should be an alpahbet."; // 매장 코드의 첫글자는 언제나 영소문자여야 합니다.
$txt_sys_shop_chk04 = "No spce permitted."; // 공백이 허용되지 않습니다.
$txt_sys_shop_chk05 = "Please enter Shop Name."; // 매장 이름을 입력하세요.


// system > user2
$txt_sys_user2_01 = "Shop Managers"; // Shop Manager 리스트
$txt_sys_user2_02 = "Add Shop Manager"; // Shop Manager 등록하기
$txt_sys_user2_03 = "Update Shop Manager"; // Shop Manager 수정하기
$txt_sys_user2_04 = "Remove Shop Manager"; // Shop Manager 삭제하기
$txt_sys_user2_05 = "Manager ID"; // Manager ID
$txt_sys_user2_06 = "Manager Name"; // Manager 이름
$txt_sys_user2_07 = "Shop"; // Shop
$txt_sys_user2_08 = "Level"; // Manager 등급
$txt_sys_user2_09 = "Last Login"; // 지난 로그인
$txt_sys_user2_10 = "Visit"; // 방문수
$txt_sys_user2_11 = "Language"; // 사용 언어
$txt_sys_user2_12 = "No Login"; // 로그인 기록 없음

$txt_sys_user2_chk01 = "Please enter Shop Manager Name."; // Shop Manager 이름을 입력하세요.
$txt_sys_user2_chk02 = "";
$txt_sys_user2_chk03 = "Your password is not valid."; // 입력하신 두 비밀번호가 일치하지 않습니다.


// system > warehouse location
$txt_sys_wloc_01 = "Location Management"; // 적재소 관리
$txt_sys_wloc_02 = "Add Location"; // 적재소 등록하기
$txt_sys_wloc_03 = "Update Location"; // 적재소 수정하기
$txt_sys_wloc_04 = "Remove Location"; // 적재소 삭제하기
$txt_sys_wloc_05 = "Category"; // 카테고리
$txt_sys_wloc_06 = "Location Code"; // 적재소 코드
$txt_sys_wloc_07 = "Location Name"; // 적재소 이름
$txt_sys_wloc_08 = "Location Options"; // 적재소 옵션
$txt_sys_wloc_09 = "PIC"; // 담당자
$txt_sys_wloc_10 = "Date of Regis."; // 등록일
$txt_sys_wloc_11 = "Date of Update"; // 변경일

$txt_sys_wloc_chk01 = "Please enter Location Name."; // 적재소 이름을 입력하셔야 합니다.


// system > supplier
$txt_sys_supplier_01 = "Suppliers"; // 공급자 리스트
$txt_sys_supplier_02 = "Add Supplier"; // 공급자 등록하기
$txt_sys_supplier_03 = "Update Supplier"; // 공급자 수정하기
$txt_sys_supplier_04 = "Remove Supplier"; // 공급자 삭제하기
$txt_sys_supplier_05 = "Supplier Code"; // 공급자 코드
$txt_sys_supplier_06 = "Supplier Name"; // 공급자 이름
$txt_sys_supplier_07 = "Type"; // 공급 유형
$txt_sys_supplier_071 = "Overseas (Import)"; // 해외 (수입)
$txt_sys_supplier_072 = "Local"; // 국내
$txt_sys_supplier_08 = "Manager"; // 담당자
$txt_sys_supplier_09 = "Status"; // 상태
$txt_sys_supplier_10 = "Hold"; // 보류
$txt_sys_supplier_11 = "Activ."; // 거래
$txt_sys_supplier_12 = "Select Supplier"; // 공급자 선택
$txt_sys_supplier_13 = "Please select Supplier."; // 공급자를 선택하세요.
$txt_sys_supplier_14 = "Supplier"; // 공급자

$txt_sys_supplier_chk01 = "Please enter Supplier Name."; // 공급자 이름을 입력하세요.


// system > brand
$txt_sys_brand_01 = "Brands"; // 브랜드 리스트
$txt_sys_brand_02 = "Add Brand"; // 브랜드 등록하기
$txt_sys_brand_03 = "Update Brand"; // 브랜드 수정하기
$txt_sys_brand_04 = "Remove Brand"; // 브랜드 삭제하기
$txt_sys_brand_05 = "Brand Code"; // 브랜드 코드
$txt_sys_brand_06 = "Brand Name"; // 브랜드 이름
$txt_sys_brand_07 = "Origin"; // 원산지
$txt_sys_brand_09 = "Show"; // 상태
$txt_sys_brand_12 = "Select Brand"; // 브랜드 선택
$txt_sys_brand_13 = "Please select Brand."; // 브랜드를 선택하세요.
$txt_sys_brand_14 = "Brand"; // 브랜드

$txt_sys_brand_chk01 = "Please enter Brand Name."; // 브랜드 이름을 입력하세요.


// system > consign
$txt_sys_consign_01 = "Consignment Groups"; // 위탁판매 그룹 리스트
$txt_sys_consign_02 = "Add Consignment Group"; // 위탁판매 그룹 등록하기
$txt_sys_consign_03 = "Update Consignment Group"; // 위탁판매 그룹 수정하기
$txt_sys_consign_04 = "Remove Consignment Group"; // 위탁판매 그룹 삭제하기
$txt_sys_consign_05 = "Group Code"; // 그룹 코드
$txt_sys_consign_06 = "Group Name"; // 그룹 이름
$txt_sys_consign_07 = "Group Type"; // 그룹 유형
$txt_sys_consign_12 = "Select Consignment Group"; // 위탁판매 그룹 선택
$txt_sys_consign_13 = "Please select Consignment Group"; // 위탁판매 그룹을 선택하세요.
$txt_sys_consign_14 = "Consignment Group"; // 위탁판매 그룹
$txt_sys_consign_15 = "Profit Share"; // 이익 분배율
$txt_sys_consign_151 = "Normal"; // 일반 판매
$txt_sys_consign_152 = "Promo"; // 할인 판매
$txt_sys_consign_153 = "Margin"; // 순이익

$txt_sys_consign_chk01 = "Please enter Consignment Group Name."; // 위탁판매 그룹 이름을 입력하세요.


// system > category
$txt_sys_category_01 = "Category"; // 카테고리
$txt_sys_category_011 = "Going"; // 진행
$txt_sys_category_012 = "Discontinued"; // 중단
$txt_sys_category_013 = "Stop"; // 스톱
$txt_sys_category_02 = "Add Category"; // 카테고리 추가하기
$txt_sys_category_03 = "Update Category"; // 카테고리 수정하기
$txt_sys_category_04 = "Remove Category"; // 카테고리 삭제하기
$txt_sys_category_05 = "Main Category"; // 대분류
$txt_sys_category_06 = "Sub Category"; // 중분류
$txt_sys_category_07 = "Add New Category"; // 새 카테고리 추가
$txt_sys_category_08 = "Remove All Categories"; // 전체 카테고리 삭제
$txt_sys_category_09 = "Add"; // 추가

$txt_sys_category_chk01 = "There should be over 1 Categories under Main Category."; // 1개 이상의 하부 카테고리가 있어야 합니다.
$txt_sys_category_chk02 = "You cannot remove Main Category with Sub Category in it."; // 하부 카테고리가 있는 대분류는 삭제할 수 없습니다.
$txt_sys_category_chk03 = "You cannot remove Sub Category with Products in it."; // 해당 상품이 있으면 중분류를 삭제할 수 없습니다.


// system > department
$txt_sys_department_01 = "Department"; // 부서


// system > mileage
$txt_sys_mileage_01 = "Mileage Table"; // 마일리지 현황
$txt_sys_mileage_02 = "Mileage"; // 마일리지
$txt_sys_mileage_03 = "Date"; // 수정일
$txt_sys_mileage_04 = "Default"; // 초기값


// system > discount
$txt_sys_discount_01 = "Discount Rates"; // 리셀러 할인율 현황
$txt_sys_discount_02 = "D/C Rate"; // 할인율


// system > voucher
$txt_sys_voucher_01 = "Vouchers"; // 바우처 리스트
$txt_sys_voucher_02 = "Issue Voucher"; // 바우처 발행하기
$txt_sys_voucher_03 = "Update Voucher"; // 바우처 수정하기
$txt_sys_voucher_04 = "Remove Voucher"; // 바우처 삭제하기
$txt_sys_voucher_05 = "Voucher Code"; // 바우처 코드
$txt_sys_voucher_06 = "Voucher Value"; // 바우처 액면가
$txt_sys_voucher_07 = "Issue"; // 발행수
$txt_sys_voucher_07_1 = "Use"; // 사용수
$txt_sys_voucher_07_2 = "Remain"; // 잔여수
$txt_sys_voucher_08 = "Validity"; // 바우처 효력
$txt_sys_voucher_09 = "Date of Issue"; // 바우처 발행일
$txt_sys_voucher_10 = "Date of Validity"; // 바우처 유효기간

$txt_sys_voucher_chk01 = "Please input Voucher Value."; // 바우처 액면가를 입력하세요.
$txt_sys_voucher_chk02 = "Please input the number of issues of Vouchers"; // 바우처 발행수를 입력하세요.


// system > voucher2
$txt_sys_voucher2_01 = "YARNEN (Harvest Payment)"; // YARNEN (수확물 대납)
$txt_sys_voucher2_02 = "Add YARNEN Option"; // YARNEN 옵션 추가
$txt_sys_voucher2_03 = "Update YARNEN Option"; // YARNEN 옵션 수정하기
$txt_sys_voucher2_04 = "Remove YARNEN Option"; // YARNEN 옵션 삭제하기
$txt_sys_voucher2_05 = "YARNEN Option Code"; // YARNEN 옵션 코드
$txt_sys_voucher2_06 = "YARNEN Option Name"; // YARNEN 옵션 이름
$txt_sys_voucher2_07 = "YARNEN Rate"; // YARNEN 비율
$txt_sys_voucher2_08 = "YARNEN Description"; // YARNEN 상세 내역
$txt_sys_voucher2_09 = "of Production Result in the field"; // 농지의 총수확물 중에서
$txt_sys_voucher2_10 = "Please select Harvest Payment Pacakge Option."; // 수확물 대납 옵션을 선택하세요.
$txt_sys_voucher2_11 = "Do not use YARNEN Credit"; // YARNEN을 사용하지 않음
$txt_sys_voucher2_12 = "months"; // 개월

$txt_sys_voucher2_chk01 = "Please input YARNEN Option Code."; // YARNEN 옵션 코드를 입력하세요.
$txt_sys_voucher2_chk02 = "Please input YARNEN Option Name."; // YARNEN 옵션 이름을 입력하세요.
$txt_sys_voucher2_chk03 = "Please input YARNEN Rate."; // YARNEN 비율을 입력하세요.


// system > discount2
$txt_sys_discount2_01 = "Special Price Table"; // 특별 행사가 현황


// system > bank
$txt_sys_bank_01 = "Bank Accounts"; // 결제은행 계좌 리스트
$txt_sys_bank_02 = "Add Bank"; // 결제은행 등록하기
$txt_sys_bank_03 = "Update Bank"; // 결제은행 수정하기
$txt_sys_bank_04 = "Remove Bank"; // 결제은행 삭제하기
$txt_sys_bank_05 = "Bank Code"; // 결제은행 코드
$txt_sys_bank_06 = "Bank Name"; // 결제은행 이름
$txt_sys_bank_07 = "Account No."; // 계좌번호
$txt_sys_bank_08 = "Account Name"; // 예금주
$txt_sys_bank_09 = "Branch Name"; // 은행 지점 이름
$txt_sys_bank_10 = "SWIFT CODE";
$txt_sys_bank_11 = "Manager"; // 담당자
$txt_sys_bank_12 = "Email"; // 담당자 Email
$txt_sys_bank_13 = "Currency"; // 통 화
$txt_sys_bank_14 = "Initial Balance"; // 초기 잔액
$txt_sys_bank_15 = "Uncollected"; // 미수금

$txt_sys_bank_chk01 = "Please enter Bank Name."; // 결제은행 이름을 입력하셔야 합니다.


// system > card
$txt_sys_card_01 = "Card Switching Machines"; // 신용카드 결제기 리스트
$txt_sys_card_02 = "Add Card Switching Machine"; // 신용카드 결제기 등록하기
$txt_sys_card_03 = "Update Card Switching Machine"; // 신용카드 결제기 수정하기
$txt_sys_card_04 = "Remove Card Switching Machine"; // 신용카드 결제기 삭제하기
$txt_sys_card_05 = "C. Code"; // 분류 코드
$txt_sys_card_06 = "Switching Machine"; // 신용카드 결제기
$txt_sys_card_07 = "Billing Bank"; // 신용카드 결제은행
$txt_sys_card_08 = "Rate"; // 카드 수수료

$txt_sys_card_chk01 = "Please enter Credit Card Name."; // 신용카드 이름을 입력하셔야 합니다.


// system > insurance
$txt_sys_insur_01 = "Insurance Agents"; // 보험사 리스트
$txt_sys_insur_02 = "Add Insurance Agent"; // 보험사 등록하기
$txt_sys_insur_03 = "Update Insurance Agent"; // 보험사 수정하기
$txt_sys_insur_04 = "Remove Insurance Agent"; // 보험사 삭제하기
$txt_sys_insur_05 = "Agent Code"; // 보험사 코드
$txt_sys_insur_06 = "Agent Name"; // 보험사 이름
$txt_sys_insur_07 = "Contact Person"; // 보험사 담당자

$txt_sys_insur_chk01 = "Please enter Insurance Agent Name."; // 신용카드 이름을 입력하셔야 합니다.


// system > zone_area
$txt_sys_area_01 = "Region List"; // 배송지 리스트
$txt_sys_area_02 = "Add Region"; // 배송지 정보 등록하기
$txt_sys_area_03 = "Update Region"; // 배송지 정보 수정하기
$txt_sys_area_04 = "Remove Region"; // 배송지 정보 삭제하기
$txt_sys_area_05 = "Code"; // 지역 코드
$txt_sys_area_06 = "Country"; // 국 가
$txt_sys_area_07 = "Region"; // 도시/지역 이름
$txt_sys_area_08 = "Shipping Charge"; // 배송료
$txt_sys_area_09 = "Minimum Wage"; // 최저 임금

$txt_sys_area_chk01 = "Please enter Regional Code"; // 지역 코드를 입력하셔야 합니다.
$txt_sys_area_chk02 = "Please enter Region Name"; // 지역 이름을 입력하셔야 합니다.


// system > loan
$txt_sys_loan_01 = "Bank Loans"; // 은행 차입
$txt_sys_loan_02 = "Add Bank Loan"; // 은행 차입 등록하기
$txt_sys_loan_03 = "Update Bank Loan"; // 은행 차입 수정하기
$txt_sys_loan_04 = "Delete Bank Loan"; // 은행 차입 삭제하기
$txt_sys_loan_05 = "Loan Code"; // 은행대출 코드
$txt_sys_loan_06 = "Loan Provider"; // 차입 은행
$txt_sys_loan_07 = "Loan Product Name"; // 대출 상품명
$txt_sys_loan_08 = "Loan Amount"; // 차입 금액
$txt_sys_loan_09 = "Interest"; // 차입 이자
$txt_sys_loan_10 = "Date of Loan"; // 차입일
$txt_sys_loan_11 = "Due Date"; // 만기일
$txt_sys_loan_12 = "Use Bank Loan"; // 은행 차입 사용하기
$txt_sys_loan_13 = "Do not use Bank Loan"; // 사용하지 않음
$txt_sys_loan_14 = "Loan Available"; // 차입 가능분
$txt_sys_loan_15 = "Loan Request"; // 차입 요청
$txt_sys_loan_16 = "Limit"; // 대출 한도

$txt_sys_loan_chk01 = "Please select Loan Provider."; // 차입 은행을 선택하세요.
$txt_sys_loan_chk02 = "Please select Loan Product Name."; // 대출 상품명 선택하세요.
$txt_sys_loan_chk03 = "Please select Loan Amount."; // 차입 금액을 선택하세요.


// system > account
$txt_sys_account_01 = "Accounting Codes"; // 계정항목 리스트
$txt_sys_account_02 = "Add Acc Entry"; // 계정항목 등록하기
$txt_sys_account_03 = "Update Acc Entry"; // 계정항목 수정하기
$txt_sys_account_04 = "Remove Acc Entry"; // 계정항목 삭제하기
$txt_sys_account_05 = "Income"; // 수 입
$txt_sys_account_05_A1 = "Sales Income"; // 판매 수입
$txt_sys_account_05_A2 = "Others"; // 기타 수익

$txt_sys_account_ch05_A1 = "Sales Income"; // 판매 수입
$txt_sys_account_ch05_A2 = "Sunday School"; // 주일 학교
$txt_sys_account_ch05_A3 = "Sunday Offering"; // 주일 헌금
$txt_sys_account_ch05_A4 = "Offering"; // 기타 헌금
$txt_sys_account_ch05_A4051 = "Easter"; // 부활절
$txt_sys_account_ch05_A4052 = "Thanks-giving"; // 추수감사절
$txt_sys_account_ch05_A4053 = "Christmas"; // 성탄절
$txt_sys_account_ch05_A5 = "Others"; // 기타 수입

$txt_sys_account_06 = "Outgoing"; // 지 출
$txt_sys_account_06_B1 = "Direct Cost"; // 직접 비용
$txt_sys_account_06_B2 = "Indirect Cost"; // 간접 비용
$txt_sys_account_06_B3 = "Salaries"; // 인건비
$txt_sys_account_09 = "Add Field"; // 항목 추가
$txt_sys_account_10 = "Post"; // 등 록


// user
$txt_user_01 = "Change Language"; // 언어 변경하기
$txt_user_02 = "Change Password"; // 비밀번호 변경하기
$txt_user_03 = "Old Password"; // 현 비밀번호
$txt_user_04 = "Profile Update"; // 개인정보 변경하기
$txt_user_05 = "";




// Website
// website > menu
$txt_web_menu_01 = "Menu List"; // 메뉴 리스트
$txt_web_menu_02 = "Add Menu"; // 메뉴 등록하기
$txt_web_menu_03 = "Update Menu"; // 메뉴 수정하기
$txt_web_menu_04 = "Delete Menu"; // 메뉴 삭제하기
$txt_web_menu_05 = "Menu Title"; // 메뉴 이름
$txt_web_menu_06 = "Menu Format"; // 메뉴 속성
$txt_web_menu_type_news = "News Clip"; // 뉴스 클립
$txt_web_menu_type_blog = "Blog"; // 블로그
$txt_web_menu_type_emag = "Magazine"; // 매거진
$txt_web_menu_type_hist = "History"; // 연혁
$txt_web_menu_type_serm = "Sermon"; // 설교
$txt_web_menu_type_faq = "FAQ"; // 자주 묻는 질문 (FAQ)
$txt_web_menu_type_qna = "Q&A"; // 묻고 답하기 (Q&A)
$txt_web_menu_type_book = "Guest Book"; // 방명록
$txt_web_menu_type_bbs = "Board"; // 게시판
$txt_web_menu_type_bbsm = "Board (Marketplace)"; // 게시판 (사고팔기)
$txt_web_menu_type_bbsj = "Board (Recruitment)"; // 게시판 (구인구직)
$txt_web_menu_type_alb1 = "Photo Gallery (1 Column)"; // 포토 갤러리 (가로 1칸)
$txt_web_menu_type_alb2 = "Photo Gallery (2 Columns)"; // 포토 갤러리 (가로 2칸)
$txt_web_menu_type_alb3 = "Photo Gallery (3 Columns)"; // 포토 갤러리 (가로 3칸)
$txt_web_menu_type_alb4 = "Photo Gallery (4 Columns)"; // 포토 갤러리 (가로 4칸)
$txt_web_menu_type_alb5 = "Photo Gallery (5 Columns)"; // 포토 갤러리 (가로 5칸)
$txt_web_menu_type_albx = "Photo Gallery (Directory)"; // 포토 갤러리 (디렉토리)
$txt_web_menu_type_week = "Weekly Bulletin"; // 주보
$txt_web_menu_type_blnk = "Blank Page"; // 빈 페이지
$txt_web_menu_type_pop = "* Link to Pop-up Page *"; // * 팝업 페이지에 연결 *
$txt_web_menu_type_link = "* Link to URL *"; // * 특정 URL에 연결 *
$txt_web_menu_type_rss = "* Link to RSS *"; // * RSS에 연결 *
$txt_web_menu_type_x = "* Link to Sub Page *"; // * 서브 페이지에 연결 *

$txt_web_menu_07 = "Option"; // 첨부 옵션
$txt_web_menu_opt_0 = "Default"; // 기본
$txt_web_menu_opt_1 = "Attach Image"; // 이미지
$txt_web_menu_opt_2 = "Attach Flash Movie (SWF)"; // Flash 무비 (SWF)
$txt_web_menu_opt_3 = "Attach File (Resource Centre)"; // 일반 파일 (자료실 운영)
$txt_web_menu_opt_4 = "Attach Audio File & MP3"; // 오디오 파일 및 MP3
$txt_web_menu_opt_5 = "Attach Movie Clip"; // 동영상 파일
$txt_web_menu_opt_6 = "Attach Movie Clip (FLV/MP4)"; // 동영상 파일 (FLV/MP4)
$txt_web_menu_opt_8 = "Attach Form Mailer"; // 메일 발송 폼

$txt_web_menu_08 = "Number"; // 개수
$txt_web_menu_08d = "Day"; // 일
$txt_web_menu_08dp = "Days"; // 일
$txt_web_menu_082 = "articles / page"; // 개 / 페이지
$txt_web_menu_09 = "Add+"; // 추가+
$txt_web_menu_10 = "Add Menu"; // 메뉴 추가
$txt_web_menu_11 = "Website URL"; // 홈페이지 주소
$txt_web_menu_12 = "Menu Code"; // 메뉴 코드
$txt_web_menu_13 = "Menu Depth"; // 메뉴 단계 구분
$txt_web_menu_131 = "Main Menu"; // 메인 메뉴
$txt_web_menu_132 = "Sub Menu"; // 서브 메뉴
$txt_web_menu_14 = "In Use"; // 사용하기
$txt_web_menu_15 = "New Article"; // 신규 게시물 표시
$txt_web_menu_16 = "Number of rows"; // 게시물 수
$txt_web_menu_17 = "Permission"; // 게시물 접근허가
$txt_web_menu_permit_0 = "Free Access"; // 제한 없음
$txt_web_menu_permit_1 = "Writeable After Login"; // 로그인 후 쓰기 가능
$txt_web_menu_permit_2 = "Read-Only Before/After Login"; // 언제나 읽기만 가능
$txt_web_menu_permit_3 = "Read-Only After Login"; // 로그인 후 읽기만 가능
$txt_web_menu_permit_4 = "Free Access By Member After Login"; // 로그인한 회원만 이용 가능
$txt_web_menu_permit_5 = "Free Access By Staff After Login"; // 로그인한 직원만 이용 가능
$txt_web_menu_permit_6 = "No Access Permitted Except Admin"; // 관리자 외 사용 금지

$txt_web_menu_18 = "Menu Location"; // 메뉴 위치
$txt_web_menu_loco_intro1 = "Intro Page"; // 인트로 페이지
$txt_web_menu_loco_intro2 = "Dashboard"; // 대쉬보드
$txt_web_menu_loco_head = "Header"; // 상단
$txt_web_menu_loco_foot = "Footer"; // 하단
$txt_web_menu_loco_short = "Short Cut"; // 단축 메뉴

$txt_web_menu_19 = "Order By"; // 정렬 방법
$txt_web_menu_191 = "DESCending"; // 내림차순
$txt_web_menu_192 = "ASCending"; // 오름차순
$txt_web_menu_193 = "RANDOM"; // 무작위
$txt_web_menu_20 = "Connect to Site"; // 특정 사이트에 연결
$txt_web_menu_21 = "Connect to URL"; // 특정 URL에 연결
$txt_web_menu_22 = "Link now"; // 연결 하기
$txt_web_menu_23 = "";
$txt_web_menu_24 = "";
$txt_web_menu_25 = "";


// website > content
$txt_web_content_01 = "Articles"; // 콘텐츠 리스트
$txt_web_content_02 = "Post Article"; // 콘텐츠 등록하기
$txt_web_content_03 = "Edit Article"; // 콘텐츠 수정하기
$txt_web_content_04 = "Delete Article"; // 콘텐츠 삭제하기
$txt_web_content_order0 = "Updated"; // 수정순
$txt_web_content_order1 = "Subject"; // 제목순
$txt_web_content_order2 = "Contents"; // 내용순
$txt_web_content_order3 = "Posting Date"; // 게시일순
$txt_web_content_order4 = "Last Updated"; // 최근수정순
$txt_web_content_order5 = "Menu"; // 메뉴순

$txt_web_content_05 = "Add Content"; // 콘텐츠 추가
$txt_web_content_06 = "List"; // 리스트
$txt_web_content_07 = "Title"; // 제목
$txt_web_content_08 = "Subtitle"; // 부제목
$txt_web_content_09 = "Content"; // 내용
$txt_web_content_10 = "Image File"; // 이미지 파일
$txt_web_content_10p = "Replace"; // 교체
$txt_web_content_11 = "Image Caption"; // 이미지 설명글
$txt_web_content_12 = "Show"; // 게시
$txt_web_content_121 = "Shown"; // 보여짐
$txt_web_content_122 = "Hidden"; // 숨김
$txt_web_content_13 = "Add Paragraph"; // 단락 추가하기
$txt_web_content_14 = "Select Writer"; // 작가를 선택하세요
$txt_web_content_15 = "Unknown"; // 작가 미지정
$txt_web_content_16 = "Create Contents"; // 콘텐츠 생성하기
$txt_web_content_17 = "Contents Type"; // 콘텐츠 타입
$txt_web_content_18 = "Upload Image File"; // 이미지 파일 올리기


// website > banner1
$txt_web_banner1_01 = "Banner Files"; // 배너 파일 리스트
$txt_web_banner1_02 = "Post Banner File"; // 배너 파일 등록하기
$txt_web_banner1_03 = "Update Banner File"; // 배너 파일 수정하기
$txt_web_banner1_04 = "Delete Banner File"; // 배너 파일 삭제하기
$txt_web_banner1_order0 = "Banner Code"; // 배너 코드순
$txt_web_banner1_order1 = "Upload Date"; // 배너 등록순
$txt_web_banner1_05 = "Banner Code(ID)"; // 배너 코드(ID)
$txt_web_banner1_05s = "Code(ID)"; // 코드(ID)
$txt_web_banner1_06 = "Banner Type"; // 배너 타입
$txt_web_banner1_07 = "File Size"; // 파일 크기
$txt_web_banner1_08 = "Add Banner File"; // 배너 파일 추가
$txt_web_banner1_09 = "Banner File Name"; // 배너 파일명
$txt_web_banner1_10 = "Upload Banner File"; // 배너 파일 올리기
$txt_web_banner1_11 = "Banner Dimension"; // 배너 크기
$txt_web_banner1_111 = "Width"; // 가로
$txt_web_banner1_112 = "Height"; // 세로
$txt_web_banner1_12 = "Pixel"; // 픽셀
$txt_web_banner1_13 = "Replace Banner File"; // 배너 파일 교체
$txt_web_banner1_14 = ""; //
$txt_web_banner1_15 = ""; //


// website > banner2
$txt_web_banner2_01 = "Banner Display List"; // 배너 게시 리스트
$txt_web_banner2_02 = "Add Banner Display"; // 배너 게시 등록하기
$txt_web_banner2_03 = "Update Banner Display"; // 배너 게시 수정하기
$txt_web_banner2_04 = "Delete Banner Display"; // 배너 게시 삭제하기
$txt_web_banner2_05 = "Location"; // 게시 위치
$txt_web_banner2_05b = "Banner Location"; // 배너 게시 위치
$txt_web_banner2_06 = "Account"; // 광고주 계정
$txt_web_banner2_06b = "Banner Account"; // 배너 광고주 계정
$txt_web_banner2_07 = "Add Banner Display"; // 배너 게시 추가
$txt_web_banner2_08 = "Banner URL"; // 배너 연결 URL
$txt_web_banner2_09 = "Bg Color"; // 배경색
$txt_web_banner2_10 = "When 'Custom', input Target name"; // 'Custom' 선택시, Target 이름
$txt_web_banner2_11 = "Banner Display"; // 배너 게시
$txt_web_banner2_12 = "No. of Visitors"; // 방문자 수
$txt_web_banner2_13 = "Date of Posting"; // 등록일
$txt_web_banner2_14 = "Last Update"; // 최근 수정일


// website > stuff
$txt_web_stuff_01 = "Select Location"; // 콘테츠 위치별 종류 선택
$txt_web_stuff_loco_01 = "Welcome Comment [Intro Page]"; // 환영인사 [첫화면]
$txt_web_stuff_loco_02 = "Contact Info [Left]"; // 연락처 [좌측]
$txt_web_stuff_loco_03 = "Guide to Sign-up"; // 회원 가입 안내
$txt_web_stuff_loco_04 = "Terms & Regulations"; // 이용자 약관
$txt_web_stuff_loco_05 = "Reminder [Pop-up Page]"; // 공지 사항 [팝업창]
$txt_web_stuff_loco_06 = "Foot Box"; // 하단 박스
$txt_web_stuff_loco_07 = "Foot Box Small Column"; // 하단 박스 작은 칸
$txt_web_stuff_loco_08 = "Copyrights"; // 하단 저작권 표시
$txt_web_stuff_loco_09 = "Auto Response - Sign-up"; // 자동응답메일 - 회원 가입
$txt_web_stuff_loco_10 = "Auto Response - Find Password"; // 자동응답메일 - 비밀번호 찾기
$txt_web_stuff_loco_11 = "Auto Response - Invoice"; // 자동응답메일 - 인보이스 발행
$txt_web_stuff_loco_12 = "News Letter - Footer"; // 뉴스 레터 - 하단 주소표시 줄
$txt_web_stuff_loco_13 = "Shop - Billing Information"; // 쇼핑몰 - 과금 안내
$txt_web_stuff_loco_14 = "Shop - Shipping"; // 쇼핑몰 - 배송 안내


// website > mailing
$txt_web_mailing_01 = "Agree"; // 수신 동의
$txt_web_mailing_01_yes = "Yes"; // 동의
$txt_web_mailing_01_no = "No"; // 거절
$txt_web_mailing_02 = "List-up"; // 리스트-업
$txt_web_mailing_021 = "Remove"; // 해제하기
$txt_web_mailing_022 = "+ Add"; // + 등록
$txt_web_mailing_03 = "Selected"; // 선택한 메일 수
$txt_web_mailing_04 = "Add All"; // 모두 등록하기
$txt_web_mailing_05 = "Remove All"; // 모두 해제하기
$txt_web_mailing_06 = "Select News Letter"; // 뉴스 레터를 선택하세요
$txt_web_mailing_07 = "Add to Mailing List"; //  메일링 리스트에 등록하기
$txt_web_mailing_08 = "Sent Date"; // 발송일
$txt_web_mailing_08s = "Sent"; // 발송일
$txt_web_mailing_09 = "Count"; // 발송수
$txt_web_mailing_10 = "Mailer"; // 발송하기
$txt_web_mailing_11 = "Re-send"; // 재발송
$txt_web_mailing_12 = "+ Send"; // + 발송
$txt_web_mailing_13 = "Composed"; // 작성일

$txt_web_mailing_chk_01 = "Your submission of Email already exists in the mailing list."; // 입력하신 이메일은 이미 메일링 리스트에 있습니다.


// website > news letter
$txt_web_nletter_01 = "News Letters"; // 뉴스 레터 리스트
$txt_web_nletter_02 = "Compose News Letter"; // 뉴스 레터 등록하기
$txt_web_nletter_03 = "Edit News Letter"; // 뉴스 레터 수정하기
$txt_web_nletter_04 = "Delete News Letter"; // 뉴스 레터 삭제하기
$txt_web_nletter_05 = "Compose News Letter"; // 뉴스 레터 작성하기
$txt_web_nletter_06 = "Issue No."; // 발송 번호
$txt_web_nletter_07 = "Footer"; // 하단 주소표시 부분
$txt_web_nletter_08 = "No. of Recipients"; // 수신자 수
$txt_web_nletter_09 = "Compose"; // 편집창
$txt_web_nletter_10 = "Preview"; // 미리보기
$txt_web_nletter_11 = "Send News Letter"; // 뉴스 레터 발송하기
$txt_web_nletter_12 = "Recipients"; // 수신자
$txt_web_nletter_121 = "All the Mailing List"; // 메일링 리스트에 등록된 전체 수신자
$txt_web_nletter_122 = "All your selections from Mailing List"; // 메일링 리스트에서 선택한 수신자
$txt_web_nletter_123 = "All the List filtered from Mailing List"; // 메일링 리스트에서 검색한 수신자


// website > layout
$txt_web_layout_01 = "Save Website Layout"; // 홈페이지 레이아웃 저장하기
$txt_web_layout_02 = "Create Website Layout Table"; // 홈페이지 레이아웃 테이블 생성하기




// BBS

	// 인사말
	$bbstxt_01 = "Introduction1";
	$bbstxt_02 = "Introduction2";

	// My Members
	$mbdtxt_01 = "Member List";
	$mbdtxt_02 = "Gender";
	$mbdtxt_03 = "Location";
	$mbdtxt_04 = "Message";
	$mbdtxt_05 = "Status";
	$mbdtxt_06 = "Action";
	$mbdtxt_07 = "Male";
	$mbdtxt_08 = "Female";
	$mbdtxt_09 = "Listed";
	$mbdtxt_10 = "Unlisted";
	$mbdtxt_11 = "Address Book";

	// Bulletin
	$bdtxt_01 = "No.";
	$bdtxt_02 = "Subject";
	$bdtxt_03 = "Name";
	$bdtxt_04 = "Date";
	$bdtxt_05 = "Hit";
	$bdtxt_06 = "Select";
	$bdtxt_07 = "Name";
	$bdtxt_08 = "Comment";
	$bdtxt_09 = "Post Article";
	$bdtxt_10 = "Website";
	$bdtxt_11 = "Password";
	$bdtxt_12 = "(At least 4~8 letters)";
	$bdtxt_13 = "Give a Reply Comment";
	$bdtxt_14 = "Edit Article";
	$bdtxt_151 = "Delete Article";

	// PDS
	$bdtxt_15 = "FILE";
	$bdtxt_16 = "Description";
	$bdtxt_17 = "Download";
	$bdtxt_18 = " has posted.";
	$bdtxt_19 = "Testimonial";
	$bdtxt_20 = "Imoticon";
	$bdtxt_21 = "You Comment !";
	$bdtxt_22 = "Delete your FILE";
	$bdtxt_23 = "Pick FILE";
	
	$bdtxt_24 = "IP";

	$bdtxt_31 = "Order of Contents";
	$bdtxt_32 = "Ascending Order";
	$bdtxt_33 = "Descending Order";
	$bdtxt_34 = "Insert Image";
	$bdtxt_35 = "No Image";
	$bdtxt_36 = "GIF";
	$bdtxt_37 = "JPG";
	$bdtxt_38 = "SWF(Flash Movie Clip)";
	$bdtxt_39 = "Image Alignment";
	$bdtxt_40 = "Vertical Alignment - Top";
	$bdtxt_41 = "Vertical Alignment - Bottom";
	$bdtxt_42 = "Vertical Alignment - Middle";
	$bdtxt_43 = "Align Left";
	$bdtxt_44 = "Align Center";
	$bdtxt_45 = "Align Right";

	$bdtxt_51 = "Image Size";
	$bdtxt_52 = "Landscape";
	$bdtxt_53 = "Portrait";
	$bdtxt_54 = "Square";

	$bdtxt_91 = "Pin Key";
	$bdtxt_92 = "Please put the words below in the blank.";
	$bdtxt_93 = "Search";
	$bdtxt_94 = "This is Confidential Content."; // 비밀글입니다.
	$bdtxt_95 = "Confidential"; // 비밀댓글
	$bdtxt_96 = "Post"; // 댓글쓰기
	$bdtxt_97 = "This is Confidential Foot note."; // 비밀댓글입니다.
	$bdtxt_98 = "Please insert your comment."; // 댓글을 입력하셔야 합니다.
	$bdtxt_99 = "Maximum 200 letters are vailable here."; // 글자수는 한글 100자, 영문 200자로 제한됩니다.
	$bdtxt_901 = "This article has been saved in your library."; // My Library에 저장되었습니다.
	$bdtxt_902 = "This article was already saved in your library"; // 이미 My Library에 저장하셨습니다.
	$bdtxt_903 = "Nick Name"; // 닉네임
	$bdtxt_904 = "Sale"; // 매매
	$bdtxt_905 = "Rent"; // 임대
	$bdtxt_906 = "Lease"; // 재임대
	$bdtxt_907 = "Subtitle"; // 부제목
	$bdtxt_908 = "New line breaks"; // 줄바꿔 쓰기
	$bdtxt_909 = "Non-disclosure"; // 비밀글
	$bdtxt_910 = "Advertising"; // 광고 신청
	$bdtxt_911 = "Box"; // 박스광고
	$bdtxt_912 = "Line"; // 줄광고
	$bdtxt_913 = "No, thanks."; // 신청 않음
	$bdtxt_914 = "Replace Attached File"; // 첨부파일 변경
	$bdtxt_915 = "Cancel"; // 광고 해제


	// 방명록
	$buktxt_01 = "Guest Book";
	$buktxt_02 = "There is no writing posted on the Guest Book now.";
	$buktxt_03 = "Modify";
	$buktxt_04 = "Delete";
	$buktxt_05 = "Comment";
	$buktxt_06 = "";
	$buktxt_07 = "";
	$buktxt_08 = "";
	$buktxt_09 = "";
	$buktxt_10 = "";

	// Trade
	$trdtxt_01 = "Title";
	$trdtxt_02 = "Item";
	$trdtxt_03 = "Introduction";
	$trdtxt_04 = "Description";
	$trdtxt_05 = "Condition";
	$trdtxt_06 = "Contact Info";
	$trdtxt_07 = "Image1";
	$trdtxt_08 = "Image2";
	$trdtxt_09 = "No Image";
	$trdtxt_10 = "Attached File";
	$trdtxt_11 = "No Attached File";
	$trdtxt_12 = "File Size";
	$trdtxt_13 = "At most 100 strings available";
	$trdtxt_14 = "Pixel";
	$trdtxt_15 = "Replace Image";
	$trdtxt_16 = "Replace File";
	$trdtxt_17 = "Attach File";
	$trdtxt_18 = "Please enter the Introduction.";
	$trdtxt_19 = "";
	$trdtxt_20 = "";

	// 북마크
	$bmktxt_01 = "Website Name";
	$bmktxt_02 = "Website URL";
	$bmktxt_03 = "Bookmark";
	$bmktxt_04 = "Please enter the Website Name.";
	$bmktxt_05 = "Please enter the Website URL.";

  // 폼메일
  $fmltxt_01 = "Send";
  $fmltxt_02 = "Reset";
  $fmltxt_03 = "Your mail has been delivered successfully ..^^*";
  $fmltxt_04 = "Please enter your name.";
  $fmltxt_05 = "Please enter your Email address.";
  $fmltxt_06 = "Please enter the title.";
  $fmltxt_07 = "Please enter your message.";
  $fmltxt_08 = "Online Order Form";
  $fmltxt_09 = "Product";
  $fmltxt_10 = "";

  $fmltxt_21 = "Invalid Email Adress.";
  $fmltxt_22 = "Please enter a password.";
  $fmltxt_23 = "Please enter the pin key.";
  $fmltxt_24 = "Post";
  $fmltxt_25 = "Reset";
  $fmltxt_26 = "Update";
  $fmltxt_27 = "Delete";
  $fmltxt_28 = "Cancel";
  $fmltxt_29 = "";

	// 마켓플레이스/구인구직 등
	$bmrtxt_01 = "Select";
	$bmrtxt_11 = "Sell";
	$bmrtxt_12 = "Buy";
	$bmrtxt_21 = "Wanted";
	$bmrtxt_22 = "Job Opportunity";
?>

