<?
$DB_SERVER="localhost";      // Database Server machine
$DB_LOGIN="feelbuy";            // Database login ID
$DB_PASSWORD="feelbuy";         // Database password
$DB="feelbuy";                // Database name

// Website Identity
$website_name = "FEEL BUY";
$copyright_name = "&copy; 2014 FEEL BUY. Built on Twitter Bootstrap & IKBIZ ERP-CMS Engine.";

$gate = "host";

if(!$lang) { $lang = "en"; }

$admin_email = "info@ikbiz.com";

$home = "http://localhost/feelbuy3/home/host";
$home_txt = "feelbuy.co.id";
$root = "/home/feelbuy/home/host";
?>
