<?
// Front Desk Menu
$frn1_mmenu_01 = "바코드";
$frn1_mmenu_02 = "확 인";
$frn1_mmenu_03 = "수 정";
$frn1_mmenu_04 = "일일 매출현황";
$frn1_mmenu_05 = "인 쇄";

$frn1_mmenu_06 = "언 어";
$frn1_mmenu_06_en = "영 어";
$frn1_mmenu_06_ko = "한국어";
$frn1_mmenu_06_in = "인도네시아어";
$frn1_mmenu_07 = "사용자 계정이 없나요?";
$frn1_mmenu_08 = "로그인";
$frn1_mmenu_08b = "로그인";
$frn1_mmenu_09 = "회원 로그인";
$frn1_mmenu_10 = "사용자 정보를 입력하세요.";
$frn1_mmenu_11 = "회사 ID";
$frn1_mmenu_12 = "사용자 ID";
$frn1_mmenu_12e = "사용자 ID 또는 Email";
$frn1_mmenu_13 = "비밀번호";
$frn1_mmenu_14 = "로그인 상태 유지";
$frn1_mmenu_15 = "무료 계정 가입하기";
$frn1_mmenu_16 = "데모 버전 로그인";
$frn1_mmenu_17 = "무료 계정을 발급받으세요:";
$frn1_mmenu_18 = "회사 이름";
$frn1_mmenu_19 = "이름";
$frn1_mmenu_20 = "전화번호";
$frn1_mmenu_21 = "사용자 약관에 동의합니다.";
$frn1_mmenu_22 = "등록하기";
$frn1_mmenu_23 = "이미 계정이 있나요?";
$frn1_mmenu_24 = "사용자 로그인";
$frn1_mmenu_25 = "대쉬보드";
$frn1_mmenu_26 = "홈페이지로 가기";


// Church Community Name
$ch_comm_dir1 = "교 구"; // 교 구
$ch_comm_dir11 = "담당 교역자"; // 담당 교역자
$ch_comm_dir2 = "지 역"; // 지 역
$ch_comm_dir20 = "지역"; // 지역
$ch_comm_dir21 = "지역장"; // 지역장
$ch_comm_cug2 = "새가족반"; // 새가족반


// Menu
$hmm_name_01 = "Home";
$hmm_name_02 = "판매 관리";
  $hsm_name_02_01 = "판매 입력";
  $hsm_name_02_02 = "주문 관리";
  $hsm_name_02_02a = "상품 검색";
  $hsm_name_02_02b = "주문 승인 및 화물 인도";
  $hsm_name_02_021 = "상품 수령";
  $hsm_name_02_022 = "재고 실사";
  $hsm_name_02_03 = "배송 관리";
  $hsm_name_02_04 = "대금 청구 관리";
  $hsm_name_02_041 = "수금 관리";
  $hsm_name_02_05 = "인보이스 관리";
  $hsm_name_02_09 = "상품 관리";
  $hsm_name_02_POS = "Point of Sales [POS]";

$hmm_name_03 = "";

$hmm_name_03ch = "교적 관리";
  $hsm_name_03ch_01 = "교역자 정보";
  $hsm_name_03ch_02 = "개인 정보";
  $hsm_name_03ch_03 = "세대 정보";
  $hsm_name_03ch_04 = "$ch_comm_dir20"." 정보";
  $hsm_name_03ch_05 = "$ch_comm_cug1";
  $hsm_name_03ch_06 = "$ch_comm_cug10"."별 출결 관리";
  $hsm_name_03ch_06t = "출결 관리";

$hmm_name_04 = "구매/재고 관리"; // 구매/재고 관리
  $hsm_name_04_01 = "상품 등록/수정"; // 구매/입고 관리
  $hsm_name_04_02 = "출고 관리";
  $hsm_name_04_023 = "대금 청구 관리";
  $hsm_name_04_03 = "재고 수정/마감 관리";
  $hsm_name_04_03_2 = "재고 반품 관리";
  $hsm_name_04_04 = "상품구매 지불결제 관리";
  $hsm_name_04_041 = "지불결제 확인";
  $hsm_name_04_05 = "구매 지불마감 관리";
  $hsm_name_04_06 = "상품구매 주문 관리";
  $hsm_name_04_061 = "구매 상품 검색";
  $hsm_name_04_062 = "구매 주문 승인 및 발송";
  $hsm_name_04_07 = "상품 수령 확인";
  $hsm_name_04_071 = "입고";
  $hsm_name_04_072 = "입고 확인";
  $hsm_name_04_08 = "인보이스";
  $hsm_name_04_21 = "상품 옵션 항목 관리";
  $hsm_name_04_22 = "상품 단위 관리";

$hmm_name_041 = "물류 관리";
  $hsm_name_041_01 = "화물 인도 지시서 확인";
  $hsm_name_041_02 = "화물 인도 관리";

$hmm_name_05 = "재무/회계 관리";
  $hsm_name_05_01 = "일반 비용 관리";
  $hsm_name_05_01_2 = "구매 비용 관리";
  $hsm_name_05_02 = "일반 수익 관리";
  $hsm_name_05_02_2 = "판매 수익 관리";
  
  $hsm_name_05ch_02_2 = "헌금 계수 관리";
  $hsm_name_05ch_offering = "헌금 계수";
  
  $hsm_name_05_03 = "상세 수익/비용 분석";
  $hsm_name_05_04 = "예산 사용 현황";

$hmm_name_06 = "고객 관리";
  $hsm_name_06_01 = "고객 관리";
  $hsm_name_06_011 = "리셀러 (상점)";
  $hsm_name_06_012 = "리셀러 (개인)";
  $hsm_name_06_013 = "일반 고객 (기업)";
  $hsm_name_06_014 = "일반 고객 (개인)";
  $hsm_name_06_02 = "대리점";
  $hsm_name_06_021 = "대리점 (지역총판)";
  $hsm_name_06_022 = "대리점 (지역지점)";
  $hsm_name_06_03 = "메일링 리스트";
  $hsm_name_06_04 = "뉴스 레터";

$hmm_name_07 = "인력 관리";
  $hsm_name_07_01 = "사원 관리";

$hmm_name_08 = "홈페이지 관리";
  $hsm_name_08_01 = "메뉴 관리";
  $hsm_name_08_02 = "콘텐츠 편집";
  $hsm_name_08_03 = "배너 관리";
  $hsm_name_08_031 = "배너 파일 관리";
  $hsm_name_08_032 = "배너 게시 관리";
  $hsm_name_08_04 = "기타 페이지 편집";
  $hsm_name_08_05 = "메일링 리스트";
  $hsm_name_08_05A = "메일링 리스트 A (회원)";
  $hsm_name_08_05B = "메일링 리스트 B (비회원)";
  $hsm_name_08_06 = "뉴스 레터";
  $hsm_name_08_09 = "홈페이지 레이아웃";
  $hsm_name_08_10 = "쇼핑몰 레이아웃";

$hmm_name_09 = "시스템 관리"; // system
  $hsm_name_09_01 = "시스템 관리";
  $hsm_name_09_02 = "시스템 Manager 관리";
  $hsm_name_09_031 = "매장 관리";
  $hsm_name_09_032 = "매장 Manager 관리";
  $hsm_name_09_03C = "통화 관리";
  $hsm_name_09_04 = "공급자 관리";
  $hsm_name_09_05 = "상품 카테고리 관리";
  $hsm_name_09_06 = "마일리지";
  $hsm_name_09_07 = "리셀러 할인율";
  $hsm_name_09_08 = "바우처 발행관리";
  $hsm_name_09_081 = "YARNEN 관리";
  $hsm_name_09_09 = "특별 행사가";
  $hsm_name_09_10 = "현금시제 초기값";
  $hsm_name_09_11 = "결제은행 계좌관리";
  $hsm_name_09_12 = "신용카드 결제기 관리";
  $hsm_name_09_13 = "계정항목 관리";
  $hsm_name_09_132 = "부서별 지출항목";
  $hsm_name_09_133 = "부서별 예산";
  $hsm_name_09_14 = "은행대출";
  $hsm_name_09_20 = "환율 관리";
  $hsm_name_09_15 = "지역 관리";
  $hsm_name_09_17 = "창고 관리";
  $hsm_name_09_18 = "위탁판매 그룹 관리";
  $hsm_name_09_21 = "연동 Client DB 계정";
  $hsm_name_09_22 = "회사 계정";
  $hsm_name_09_34 = "훈련/활동 과정 관리";
  $hsm_name_09_341 = "훈련/활동 카테고리";
  $hsm_name_09_342 = "훈련/활동 과정";
  $hsm_name_09_41 = "직급 코드";
  $hsm_name_09_42 = "호봉";
  $hsm_name_09_43 = "연간 임금기준표";
  
  $hsm_name_09ch_31 = "그룹 카테고리";
  $hsm_name_09ch_311 = "교구와 지역 구분";
  $hsm_name_09ch_312 = "부 서";
  $hsm_name_09ch_313 = "선교회";
  $hsm_name_09ch_32 = "$ch_comm_cug1";
  $hsm_name_09ch_33 = "직위 및 직분";
  $hsm_name_09ch_331 = "직 위";
  $hsm_name_09ch_332 = "직 분";
  $hsm_name_09ch_333 = "직 업";
  $hsm_name_09ch_34 = "훈련/활동 과정 관리";
  $hsm_name_09ch_341 = "훈련/활동 카테고리";
  $hsm_name_09ch_342 = "훈련/활동 과정";
  
$hmm_name_10 = "환경 설정"; // user
  $hsm_name_10_01 = "언어선택";
  $hsm_name_10_02 = "계정정보 변경";
  $hsm_name_10_03 = "비밀번호 변경";
  $hsm_name_10_04 = "사용자 등록";
  $hsm_name_10_05 = "로그인";
  $hsm_name_10_06 = "로그아웃";


// 입출력 폼 - 공통
$txt_comm_frm01 = "입 력";
$txt_comm_frm01s = "입력";
$txt_comm_frm02 = "확 인";
$txt_comm_frm03 = "등 록";
$txt_comm_frm04 = "변 경";
$txt_comm_frm05 = "수정하기";
$txt_comm_frm051 = "추가하기";
$txt_comm_frm051s = "추가";
$txt_comm_frm052 = "삭제하기";
$txt_comm_frm06 = "취 소";
$txt_comm_frm07 = "재입력";
$txt_comm_frm08 = "삭 제";
$txt_comm_frm09 = "답 변";
$txt_comm_frm10 = "출 력";
$txt_comm_frm11 = "인 쇄";
$txt_comm_frm12 = "수정";
$txt_comm_frm13 = "삭제";
$txt_comm_frm14 = "정렬 순서";
$txt_comm_frm15 = "전체 보기";
$txt_comm_frm16 = "자료 업데이트";
$txt_comm_frm17 = "업데이트";
$txt_comm_frm18 = "다 음";
$txt_comm_frm19 = "선 택";
$txt_comm_frm20 = "전체 System";
$txt_comm_frm21 = "인증번호";
$txt_comm_frm22 = "다음 번호를 입력하세요:";
$txt_comm_frm23 = "회사 코드";
$txt_comm_frm24 = "System 선택";
$txt_comm_frm25 = "전체 회사 보기";
$txt_comm_frm26 = "검 색";
$txt_comm_frm27 = "저장하기";
$txt_comm_frm28 = "처리하기";
$txt_comm_frm29 = "상품 업데이트";
$txt_comm_frm30 = "전체 회사";
$txt_comm_frm31 = "전체 Shop";
$txt_comm_frm32 = "회사 선택";
$txt_comm_frm33 = "테이블 생성";
$txt_comm_frm331 = "아래 버튼을 클릭하세요.";
$txt_comm_frm34 = "날짜";

$txt_comm_lang_en = "영 어";
$txt_comm_lang_in = "인도네시아어";
$txt_comm_lang_ko = "한 글";

$txt_comm_month_01 = "1월";
$txt_comm_month_02 = "2월";
$txt_comm_month_03 = "3월";
$txt_comm_month_04 = "4월";
$txt_comm_month_05 = "5월";
$txt_comm_month_06 = "6월";
$txt_comm_month_07 = "7월";
$txt_comm_month_08 = "8월";
$txt_comm_month_09 = "9월";
$txt_comm_month_10 = "10월";
$txt_comm_month_11 = "11월";
$txt_comm_month_12 = "12월";

$txt_comm_report_01 = "일일 보고";
$txt_comm_report_02 = "주간 보고";
$txt_comm_report_03 = "기간별 보고";
$txt_comm_report_04 = "월간 보고";
$txt_comm_report_05 = "분기 보고";
$txt_comm_report_06 = "연간 보고";
$txt_comm_report_21 = "판매 현황 보고";
$txt_comm_report_41 = "재고 현황 보고";
$txt_comm_report_51 = "재무 현황 보고";
$txt_comm_report_71 = "검색 기간";
$txt_comm_report_81 = "일일";
$txt_comm_report_82 = "주간";
$txt_comm_report_83 = "월간";
$txt_comm_report_84 = "분기";
$txt_comm_report_85 = "연간";


// sales > order, sales
$txt_sales_sales_01 = "재 고";
$txt_sales_sales_02 = "입고지";
$txt_sales_sales_03 = "판 매";
$txt_sales_sales_04 = "장바구니에 담기";
$txt_sales_sales_05 = "장바구니";
$txt_sales_sales_06 = "결 제 하 기";
$txt_sales_sales_07 = "다른 상품 검색";
$txt_sales_sales_08 = "매 진";
$txt_sales_sales_09 = "단 가";
$txt_sales_sales_10 = "합 계";
$txt_sales_sales_11 = "총 주문 합계";
$txt_sales_sales_12 = "계산하기";
$txt_sales_sales_13 = "고객 이름";
$txt_sales_sales_14 = "고객 분류";
$txt_sales_sales_14_1 = "회 원";
$txt_sales_sales_14_2 = "비회원";
$txt_sales_sales_15 = "상품 유형";
$txt_sales_sales_16 = "총 판매액";
$txt_sales_sales_17 = "수불 기일";
$txt_sales_sales_18 = "모델 Fee";
$txt_sales_sales_19 = "메 모";
$txt_sales_sales_20 = "인보이스 발행";
$txt_sales_sales_21 = "인보이스 리스트";
$txt_sales_sales_22 = "인보이스 인쇄";
$txt_sales_sales_23 = "바우처 결제";
$txt_sales_sales_24 = "특별 행사가";
$txt_sales_sales_25 = "부가세 포함";
$txt_sales_sales_26 = "부가세";
$txt_sales_sales_27 = "주문일";
$txt_sales_sales_30 = "비회원";
$txt_sales_sales_31 = "개인 회원";
$txt_sales_sales_32 = "기업 회원";
$txt_sales_sales_40 = "주문하기";
$txt_sales_sales_41 = "지금 주문하기";
$txt_sales_sales_42 = "주문번호";
$txt_sales_sales_43 = "주문 확인/취소";
$txt_sales_sales_44 = "수금 완료";

$txt_sales_sales_chk01 = "이미 선택하신 상품입니다.";
$txt_sales_sales_chk02 = "고객 이름을 선택하세요.";
$txt_sales_sales_chk03 = "판매 유형을 선택하세요.";
$txt_sales_sales_chk04 = "총 판매액을 입력하세요.";
$txt_sales_sales_chk05 = "동일한 Shop의 상품만 선택하실 수 있습니다.";


// inventory > stock_in
$txt_invn_stockin_01 = "품목/상품 리스트";
$txt_invn_stockin_02 = "품 목";
$txt_invn_stockin_03 = "상 품";
$txt_invn_stockin_04 = "카테고리";
$txt_invn_stockin_05 = "상품명";
$txt_invn_stockin_06 = "상품 코드";
$txt_invn_stockin_051 = "품목명(브랜드)";
$txt_invn_stockin_061 = "품목 코드";
$txt_invn_stockin_07 = "매입단가";
$txt_invn_stockin_07s = "매입단가"; // 매입단가
$txt_invn_stockin_08 = "입고단가";
$txt_invn_stockin_09 = "원 가";
$txt_invn_stockin_10 = "시장가"; // Kios Price
$txt_invn_stockin_11 = "정 가"; // Kios Price
$txt_invn_stockin_12 = "판매가";
$txt_invn_stockin_13 = "할인가";
$txt_invn_stockin_13i = "인보이스 금액";
$txt_invn_stockin_14 = "이 익";
$txt_invn_stockin_15 = "마 진";
$txt_invn_stockin_16 = "개당이익";
$txt_invn_stockin_17 = "수 량";
$txt_invn_stockin_18 = "입고일";
$txt_invn_stockin_19 = "품목 추가";
$txt_invn_stockin_20 = "상품 추가";
$txt_invn_stockin_21 = "카테고리 선택";
$txt_invn_stockin_22 = "추가";
$txt_invn_stockin_23 = "상품정보 변경";
$txt_invn_stockin_24 = "품목정보 수정";
$txt_invn_stockin_25 = "총매입액";
$txt_invn_stockin_26 = "총출고액";
$txt_invn_stockin_27 = "상품 삭제하기";
$txt_invn_stockin_28 = "색 상";
$txt_invn_stockin_29 = "크 기";
$txt_invn_stockin_30 = "공급자 상품 코드";
$txt_invn_stockin_31 = "입고 수량";
$txt_invn_stockin_32 = "판매 수량";
$txt_invn_stockin_32s = "판매 수량";
$txt_invn_stockin_33 = "재고 수량";
$txt_invn_stockin_34 = "유효기간 만료";
$txt_invn_stockin_35 = "남은 재고";
$txt_invn_stockin_36 = "단위";
$txt_invn_stockin_37 = "단위명";
$txt_invn_stockin_38 = "단위당 수량";
$txt_invn_stockin_40 = "단위 추가하기";
$txt_invn_stockin_41 = "단위 수정하기";
$txt_invn_stockin_42 = "단위 삭제하기";
$txt_invn_stockin_43 = "개요";
$txt_invn_stockin_44 = "상품 단위";
$txt_invn_stockin_45 = "구매 승인 요청서";
$txt_invn_stockin_46 = "선택한 구매 항목을 입고함";
$txt_invn_stockin_47 = "승인";
$txt_invn_stockin_48 = "승인됨";
$txt_invn_stockin_49 = "PO 발송";
$txt_invn_stockin_50 = "PO 인쇄";
$txt_invn_stockin_60 = "수령확인일";
$txt_invn_stockin_61 = "수량 확인";
$txt_invn_stockin_611 = "발주시";
$txt_invn_stockin_612 = "수령시";
$txt_invn_stockin_613 = "손실";
$txt_invn_stockin_6131 = "분실";
$txt_invn_stockin_6132 = "파손";
$txt_invn_stockin_6133 = "기한 만료";
$txt_invn_stockin_6134 = "제품 결함";
$txt_invn_stockin_6135 = "기타";
$txt_invn_stockin_614 = "비고";
$txt_invn_stockin_62 = "수령 확인";
$txt_invn_stockin_63 = "확인";
$txt_invn_stockin_64 = "재고 확인";
$txt_invn_stockin_65 = "재고 확인 완료";
$txt_invn_stockin_66 = "추정치";

$txt_invn_stockin_chk01 = "상품 코드를 입력하세요.";
$txt_invn_stockin_chk02 = "상품명을 입력하세요.";
$txt_invn_stockin_chk03 = "좌측 상단에서 Shop을 선택하세요.";
$txt_invn_stockin_chk04 = "카테고리를 선택하세요.";
$txt_invn_stockin_chk05 = "상품이 있는 품목은 삭제할 수 없습니다.";
$txt_invn_stockin_chk06 = "먼저 상품 리스트에서 삭제후 다시 품목을 삭제하십시오.";
$txt_invn_stockin_chk07 = "창고를 선택하세요.";


// inventory > stock_out
$txt_invn_stockout_01 = "출고지(매장)";
$txt_invn_stockout_02 = "출고지(매장) 저장";
$txt_invn_stockout_03 = "반 품";
$txt_invn_stockout_04 = "출 고";
$txt_invn_stockout_05 = "출고지";
$txt_invn_stockout_06 = "미 정";
$txt_invn_stockout_07 = "지 정";
$txt_invn_stockout_08 = "출고 취소";
$txt_invn_stockout_09 = "출고 완료";
$txt_invn_stockout_10 = "일부 출고";
$txt_invn_stockout_11 = "분할 출고";
$txt_invn_stockout_12 = "출고 수정";
$txt_invn_stockout_13 = "재고 마감";
$txt_invn_stockout_14 = "재고 수정";
$txt_invn_stockout_15 = "변경전 재고";
$txt_invn_stockout_16 = "처리 구분";
$txt_invn_stockout_17 = "재고 수정 및 마감";
$txt_invn_stockout_18 = "재고 마감 취소";
$txt_invn_stockout_19 = "재고 변동 관리";
$txt_invn_stockout_20 = "반품 리스트";
$txt_invn_stockout_21 = "출고지(Shop) 변경";
$txt_invn_stockout_22 = "재고 추가";
$txt_invn_stockout_23 = "신규 상품 생성";
$txt_invn_stockout_24 = "재고 변동일";
$txt_invn_stockout_25 = "미출고";
$txt_invn_stockout_26 = "출고";
$txt_invn_stockout_27 = "추가 출고";
$txt_invn_stockout_28 = "출고지(매장) 선택";
$txt_invn_stockout_29 = "매장을 선택하세요.";

$txt_invn_stockout_30 = "화물 인도 지시 검토"; // Delivery Check
$txt_invn_stockout_31 = "화물 인도 지시서"; // Delivery Order
$txt_invn_stockout_32 = "화물 인도 지시서 양식"; // Delivery Order Form
$txt_invn_stockout_33 = "선택한 품목에 대하여 화물 인도 지시를 합니다"; // Make a Delivery Order of your selection
$txt_invn_stockout_34 = "화물 인도 담당자"; // PIC of Delivery
$txt_invn_stockout_35 = "상세 지시서"; // Order Details
$txt_invn_stockout_36 = "인도 지시일";
$txt_invn_stockout_361 = "SJ 발송일"; // DO 발송일
$txt_invn_stockout_37 = "인도 지시 확인일";
$txt_invn_stockout_38 = "인도 완료일";
$txt_invn_stockout_39 = "처리 상태";
$txt_invn_stockout_390 = "미인도";
$txt_invn_stockout_391 = "인도 지시중";
$txt_invn_stockout_392 = "인도 처리중";
$txt_invn_stockout_393 = "인도 완료";
$txt_invn_stockout_39x = "인도 취소";
$txt_invn_stockout_40 = "수령자";
$txt_invn_stockout_41 = "매장 미지정";
$txt_invn_stockout_42 = "출발지";
$txt_invn_stockout_421 = "출발";
$txt_invn_stockout_43 = "도착지";
$txt_invn_stockout_431 = "도착";
$txt_invn_stockout_44 = "인도중";
$txt_invn_stockout_45 = "평균 소요 시간";
$txt_invn_stockout_46 = "소요 시간";
$txt_invn_stockout_47 = "소요 비용";

$txt_invn_stockout_chk01 = "출고지(매장)를 선택하세요.";


// inventory > return
$txt_invn_return_01 = "총반품액";
$txt_invn_return_02 = "반품일";
$txt_invn_return_02s = "반품일";
$txt_invn_return_03 = "처 리";
$txt_invn_return_04 = "수금 완료";
$txt_invn_return_05 = "반 품";
$txt_invn_return_06 = "분 실";
$txt_invn_return_07 = "파 손";
$txt_invn_return_08 = "기 타";
$txt_invn_return_09 = "처리중";
$txt_invn_return_09s = "처리중";
$txt_invn_return_10 = "미 수";
$txt_invn_return_11 = "반품 처리";
$txt_invn_return_12 = "수금 처리";
$txt_invn_return_13 = "수금일";
$txt_invn_return_14 = "반품 사유";


// inventory > payment
$txt_invn_payment_01 = "지불결제 리스트";
$txt_invn_payment_02 = "총 결제액";
$txt_invn_payment_03 = "결제일";
$txt_invn_payment_03s = "결제일";
$txt_invn_payment_04 = "결제 취소";
$txt_invn_payment_05 = "미지불";
$txt_invn_payment_05s = "미지불";
$txt_invn_payment_06 = "지불완료";
$txt_invn_payment_07 = "선택한 항목 지불결제하기";
$txt_invn_payment_08 = "지불 처리";
$txt_invn_payment_09 = "지불하기";
$txt_invn_payment_10 = "결제 유형";
$txt_invn_payment_10s = "결제 유형";
$txt_invn_payment_10_1 = "현금";
$txt_invn_payment_10_2 = "은행 송금";
$txt_invn_payment_10_3 = "계좌 이체";
$txt_invn_payment_10_4 = "신용 카드";
$txt_invn_payment_10_5 = "바우처";
$txt_invn_payment_10_6 = "기 타";
$txt_invn_payment_11 = "결제 은행";
$txt_invn_payment_12 = "고객 은행";
$txt_invn_payment_13 = "송금 번호";
$txt_invn_payment_14 = "결제 정보 변경";
$txt_invn_payment_15 = "결제 코드";
$txt_invn_payment_16 = "송금 은행";
$txt_invn_payment_17 = "은행 선택";
$txt_invn_payment_18 = "카드 선택";
$txt_invn_payment_19 = "수불 처리";
$txt_invn_payment_20 = "카드 결제기 선택";
$txt_invn_payment_21 = "수신 은행 계좌";
$txt_invn_payment_22 = "실 결제액";
$txt_invn_payment_23 = "미수금";
$txt_invn_payment_24 = "미수금";
$txt_invn_payment_25 = "정산";
$txt_invn_payment_26 = "수금";
$txt_invn_payment_27 = "수금";
$txt_invn_payment_28 = "송금";


// inventory > purchase
$txt_invn_purchase_01 = "상품구매 주문 리스트";
$txt_invn_purchase_02 = "상품구매 주문 작성";
$txt_invn_purchase_03 = "상품구매 주문 수정";
$txt_invn_purchase_04 = "상품구매 주문 삭제";
$txt_invn_purchase_05 = "상품구매 주문서 인쇄";
$txt_invn_purchase_06 = "발주 번호";
$txt_invn_purchase_06s = "발주 번호";
$txt_invn_purchase_07 = "발주 총액";
$txt_invn_purchase_08 = "발주일";
$txt_invn_purchase_08s = "발주일";
$txt_invn_purchase_09 = "주문하기";
$txt_invn_purchase_10 = "신규 추가";
$txt_invn_purchase_11 = "상품구매 주문서 발송";
$txt_invn_purchase_11pr = "PR 주문서 발송";
$txt_invn_purchase_12 = "상품구매 주문 리스트에 추가";
$txt_invn_purchase_12pr = "PR 리스트에 추가";
$txt_invn_purchase_13 = "상품구매 주문 리스트";
$txt_invn_purchase_13pr = "PR 리스트";


// inventory > zone_option
$txt_invn_zonopt_01 = "상품 옵션 항목 리스트";
$txt_invn_zonopt_02 = "테이블 생성";
$txt_invn_zonopt_03 = "옵션 이름";
$txt_invn_zonopt_04 = "옵션 항목";
$txt_invn_zonopt_05 = "콤마(,)를 구분자로 이용하세요.";

$txt_invn_zonopt_chk01 = "관련 테이블을 생성하셔야 합니다.";


// inventory > zone_gudang
$txt_invn_gudang_01 = "창고 리스트";
$txt_invn_gudang_02 = "창고 등록하기";
$txt_invn_gudang_03 = "창고 수정하기";
$txt_invn_gudang_04 = "창고 삭제하기";
$txt_invn_gudang_05 = "창고 코드";
$txt_invn_gudang_06 = "창고 이름";
$txt_invn_gudang_07 = "창고 관리자";

$txt_invn_gudang_chk01 = "창고 이름을 입력하세요.";


// finance > cost
$txt_fin_cost_01 = "지출 결의";
$txt_fin_cost_02 = "계정항목 선택";
$txt_fin_cost_03 = "지출 금액";
$txt_fin_cost_04 = "지출 내역";
$txt_fin_cost_05 = "참 고";
$txt_fin_cost_06 = "날 짜";
$txt_fin_cost_07 = "계정코드";

$txt_fin_cost_chk01 = "계정항목을 선택하세요.";
$txt_fin_cost_chk02 = "금액을 입력하세요.";
$txt_fin_cost_chk03 = "내역을 입력하세요.";


// finance > income
$txt_fin_income_01 = "수익 처리";
$txt_fin_income_03 = "수익 금액";
$txt_fin_income_04 = "수익 내역";


// finance > balance
$txt_fin_balance_01 = "수 입";
$txt_fin_balance_02 = "지 출";
$txt_fin_balance_03 = "잔 액";
$txt_fin_balance_04 = "누적 합계";
$txt_fin_balance_05 = "합 계";
$txt_fin_balance_06 = "계정항목";


// hr > member (basic)
$txt_hr_member_01 = "사원 리스트";
$txt_hr_member_02 = "사원 등록하기";
$txt_hr_member_03 = "사원 수정하기";
$txt_hr_member_04 = "사원 삭제하기";
$txt_hr_member_05 = "사원 코드";
$txt_hr_member_06 = "웹사이트 ID";
$txt_hr_member_07 = "사원 등급";
$txt_hr_member_08 = "회사/단체명";
$txt_hr_member_09 = "웹사이트 DB 연동 여부";
$txt_hr_member_10 = "단 절";
$txt_hr_member_11 = "중 복";
$txt_hr_member_12 = "통 합";
$txt_hr_member_13 = "마일리지 포인트";
$txt_hr_member_14 = "리셀러";
$txt_hr_member_15 = "일반 사원";
$txt_hr_member_16 = "뉴스 레터";
$txt_hr_member_17 = "가 입";
$txt_hr_member_18 = "해 제";
$txt_hr_member_31 = "영문 이름";
$txt_hr_member_32 = "결혼 여부";
$txt_hr_member_321 = "미 혼";
$txt_hr_member_322 = "기 혼";
$txt_hr_member_323 = "이 혼";
$txt_hr_member_324 = "사 별";
$txt_hr_member_325 = "재 혼";
$txt_hr_member_3291 = "퇴사일";
$txt_hr_member_3292 = "비 고";
$txt_hr_member_3293 = "소 천";
$txt_hr_member_3294 = "퇴직 사유";

$txt_hr_member_33 = "세대주 여부";
$txt_hr_member_331 = "세대주";
$txt_hr_member_332 = "세대원";
$txt_hr_member_333 = "단독 세대주";
$txt_hr_member_334 = "세대 분리";
$txt_hr_member_335 = "세대원수";
$txt_hr_member_336 = "명";
$txt_hr_member_34 = "소 속";
$txt_hr_member_341 = "장년부";
$txt_hr_member_342 = "청년부";
$txt_hr_member_343 = "대학부";
$txt_hr_member_344 = "주일학교";
$txt_hr_member_345 = "기 타";
$txt_hr_member_346 = "미소속";
$txt_hr_member_35 = "공동체 모임";
$txt_hr_member_36 = "새가족 모임";
$txt_hr_member_37 = "신 급";
$txt_hr_member_371 = "세 례";
$txt_hr_member_372 = "영아세례";
$txt_hr_member_373 = "유아세례";
$txt_hr_member_374 = "입 교";
$txt_hr_member_375 = "침 례";
$txt_hr_member_376 = "학 습";
$txt_hr_member_38 = "입사 등록일";
$txt_hr_member_380 = "퇴사";
$txt_hr_member_381 = "비정규직";
$txt_hr_member_382 = "정규직";
$txt_hr_member_39 = "여권 번호";
$txt_hr_member_40 = "여권 만료일";
$txt_hr_member_41 = "국 적";
$txt_hr_member_42 = "비자 종류";
$txt_hr_member_43 = "배우자";
$txt_hr_member_44 = "사진";
$txt_hr_member_45 = "부 서";

$txt_hr_member_60 = "구역장 주간 보고서";
$txt_hr_member_611 = "주일 출석";
$txt_hr_member_612 = "순예배 출석";
$txt_hr_member_621 = "여부";
$txt_hr_member_6211 = "출석";
$txt_hr_member_6212 = "결석";
$txt_hr_member_622 = "사유";
$txt_hr_member_63 = "조치사항";
$txt_hr_member_631 = "구역장 조치사항";
$txt_hr_member_632 = "담당 교역자 조치사항";
$txt_hr_member_64 = "기도 제목";
$txt_hr_member_65 = "전 송";

$txt_hr_member_chk01 = "시스템을 선택하세요.";


// hr > member (detail)
$txt_tab_hr_member_01 = "일 반";
$txt_tab_hr_member_A = "주 소";
$txt_tab_hr_member_A01 = "가족단위로 수정";

$txt_tab_hr_member_02 = "가 족";
$txt_tab_hr_member_0201 = "관 계";
$txt_tab_hr_member_0202 = "나 이";
$txt_tab_hr_member_0203 = "학 력";
$txt_tab_hr_member_0204 = "종 교";
$txt_tab_hr_member_0210 = "세대주와의 관계";
$txt_tab_hr_member_0210M = "남 편";
$txt_tab_hr_member_0210F = "아 내";
$txt_tab_hr_member_0211 = "부 모";
$txt_tab_hr_member_0211M = "부";
$txt_tab_hr_member_0211F = "모";
$txt_tab_hr_member_0212 = "자 녀";
$txt_tab_hr_member_0212M = "아 들";
$txt_tab_hr_member_0212F = "딸";
$txt_tab_hr_member_0213 = "친 지";
$txt_tab_hr_member_0214 = "친 구";
$txt_tab_hr_member_0219 = "기 타";
$txt_tab_hr_member_02x = "직접 입력";
$txt_tab_hr_member_03 = "직장/학교";
$txt_tab_hr_member_0301 = "직 장";
$txt_tab_hr_member_0302 = "직 종";
$txt_tab_hr_member_0303 = "직 업";
$txt_tab_hr_member_0304 = "직장명";
$txt_tab_hr_member_0305 = "회사 소개";
$txt_tab_hr_member_0306 = "입 사";
$txt_tab_hr_member_0307 = "퇴 사";

$txt_tab_hr_member_0351 = "학 교";
$txt_tab_hr_member_0352 = "학교명";
$txt_tab_hr_member_0353 = "구 분";
$txt_tab_hr_member_03531 = "유치원";
$txt_tab_hr_member_03532 = "초등학교";
$txt_tab_hr_member_03533 = "중학교";
$txt_tab_hr_member_03534 = "고등학교";
$txt_tab_hr_member_03535 = "대학(2년)";
$txt_tab_hr_member_03536 = "대학(3년)";
$txt_tab_hr_member_03537 = "대학교(학사)";
$txt_tab_hr_member_03538 = "대학원(석사)";
$txt_tab_hr_member_03539 = "대학원(박사)";
$txt_tab_hr_member_0354 = "학교소재지";
$txt_tab_hr_member_0355 = "전공/과";
$txt_tab_hr_member_0356 = "입 학";
$txt_tab_hr_member_0357 = "졸 업";
$txt_tab_hr_member_0358 = "졸업 여부";
$txt_tab_hr_member_03580 = "중 퇴";
$txt_tab_hr_member_03581 = "재학중";
$txt_tab_hr_member_03582 = "졸 업";

$txt_tab_hr_member_04 = "종 교";
$txt_tab_hr_member_0401 = "개신교";
$txt_tab_hr_member_0402 = "카톨릭";
$txt_tab_hr_member_0403 = "불 교";
$txt_tab_hr_member_0404 = "이슬람교";
$txt_tab_hr_member_0405 = "힌두교";
$txt_tab_hr_member_0409 = "기 타";
$txt_tab_hr_member_0421 = "교회/단체";
$txt_tab_hr_member_0422 = "교파/교단";
$txt_tab_hr_member_0423 = "국가/지역";
$txt_tab_hr_member_0424 = "입교년도";
$txt_tab_hr_member_0425 = "수세년도";
$txt_tab_hr_member_0426 = "제적년도";
$txt_tab_hr_member_0427 = "제적사유";
$txt_tab_hr_member_0428 = "본교회";
$txt_tab_hr_member_0429 = "직 분";
$txt_tab_hr_member_0430 = "담임목사";

$txt_tab_hr_member_05 = "훈련/활동";
$txt_tab_hr_member_0501 = "이전 교회";
$txt_tab_hr_member_0502 = "교회 이름";
$txt_tab_hr_member_0503 = "항목별 평가";
$txt_tab_hr_member_0504 = "수료 여부";
$txt_tab_hr_member_05040 = "미수료";
$txt_tab_hr_member_05041 = "수료중";
$txt_tab_hr_member_05042 = "수 료";
$txt_tab_hr_member_0506 = "점 수";
$txt_tab_hr_member_0507 = "평 가";
$txt_tab_hr_member_0508 = "참고 사항";
$txt_tab_hr_member_0509 = "교역자 견해";

$txt_tab_hr_member_06 = "특기사항";
$txt_tab_hr_member_0601 = "인도자";
$txt_tab_hr_member_0602 = "혈액형";
$txt_tab_hr_member_0603 = "결혼 기념일";
$txt_tab_hr_member_0604 = "가정 형편";
$txt_tab_hr_member_0605 = "취 미";
$txt_tab_hr_member_0606 = "특 기";
$txt_tab_hr_member_0607 = "은 사";
$txt_tab_hr_member_0608 = "건 강";
$txt_tab_hr_member_0609 = "차량 번호";
$txt_tab_hr_member_0610 = "주차장 번호";

$txt_tab_hr_member_07 = "급 여";
$txt_tab_hr_member_07s = "급여";
$txt_tab_hr_member_0701 = "연/월";
$txt_tab_hr_member_0702 = "급여 구분";
$txt_tab_hr_member_07021 = "정기 급여";
$txt_tab_hr_member_07022 = "인센티브";
$txt_tab_hr_member_0703 = "임금 코드";
$txt_tab_hr_member_0704 = "평균 급여";
$txt_tab_hr_member_0705 = "인센티브";
$txt_tab_hr_member_0706 = "보너스";
$txt_tab_hr_member_0707 = "공 제";
$txt_tab_hr_member_0708 = "급여 조정";
$txt_tab_hr_member_0709 = "세금";
$txt_tab_hr_member_0710 = "확정 급여";
$txt_tab_hr_member_0711 = "지급액";
$txt_tab_hr_member_0712 = "지급 차액";
$txt_tab_hr_member_0713 = "급여일";
$txt_tab_hr_member_0714 = "지급일";

$txt_tab_hr_member_09 = "변경사항";
$txt_tab_hr_member_0901 = "변경일";
$txt_tab_hr_member_0902 = "사원 구분";
$txt_tab_hr_member_09021 = "새가족";
$txt_tab_hr_member_09022 = "사 원";
$txt_tab_hr_member_09023 = "퇴 사";

$txt_tab_hr_member_chk01 = "금액을 입력하셔야 합니다.";
$txt_tab_hr_member_chk02 = "아래에 이름을 직접 입력하세요.";
$txt_tab_hr_member_chk03 = "계수를 완료하시겠습니까?";
$txt_tab_hr_member_chk04 = "삭제하시겠습니까?";


// chmember > group, district
$txt_ch_group_01 = "$ch_comm_cug10"." 리스트";
$txt_ch_group_02 = "$ch_comm_cug10"." 등록";
$txt_ch_group_03 = "$ch_comm_cug10"." 정보 수정";
$txt_ch_group_04 = "$ch_comm_cug10"." 삭제";
$txt_ch_group_05 = "$ch_comm_cug10"." 이름";
$txt_ch_group_06 = "$ch_comm_cug10"." 카테고리";
$txt_ch_group_07 = "간략 소개";
$txt_ch_group_08 = "상세 소개";
$txt_ch_group_09 = "활성화";
$txt_ch_group_31 = "$ch_comm_dir20"." 리스트";


// chmember > member (basic)
$txt_ch_member_01 = "성도 리스트";
$txt_ch_member_02 = "성도 등록하기";
$txt_ch_member_03 = "성도 수정하기";
$txt_ch_member_04 = "성도 삭제하기";
$txt_ch_member_05 = "성도 코드";
$txt_ch_member_06 = "웹사이트 ID";
$txt_ch_member_07 = "성도 등급";
$txt_ch_member_08 = "회사/단체명";
$txt_ch_member_09 = "웹사이트 DB 연동 여부";
$txt_ch_member_10 = "단 절";
$txt_ch_member_11 = "중 복";
$txt_ch_member_12 = "통 합";
$txt_ch_member_13 = "마일리지 포인트";
$txt_ch_member_14 = "리셀러";
$txt_ch_member_15 = "일반 성도";
$txt_ch_member_16 = "뉴스 레터";
$txt_ch_member_17 = "가 입";
$txt_ch_member_18 = "해 제";
$txt_ch_member_31 = "영문 이름";
$txt_ch_member_32 = "결혼 여부";
$txt_ch_member_321 = "미 혼";
$txt_ch_member_322 = "기 혼";
$txt_ch_member_323 = "이 혼";
$txt_ch_member_324 = "사 별";
$txt_ch_member_325 = "재 혼";
$txt_ch_member_3291 = "교회 제적일";
$txt_ch_member_3292 = "비 고";
$txt_ch_member_3293 = "소 천";
$txt_ch_member_3294 = "제적 사유";

$txt_ch_member_33 = "세대주 여부";
$txt_ch_member_331 = "세대주";
$txt_ch_member_332 = "세대원";
$txt_ch_member_333 = "단독 세대주";
$txt_ch_member_334 = "세대 분리";
$txt_ch_member_335 = "세대원수";
$txt_ch_member_336 = "명";
$txt_ch_member_34 = "소 속";
$txt_ch_member_341 = "장년부";
$txt_ch_member_342 = "청년부";
$txt_ch_member_343 = "대학부";
$txt_ch_member_344 = "주일학교";
$txt_ch_member_345 = "기 타";
$txt_ch_member_346 = "미소속";
$txt_ch_member_35 = "공동체 모임";
$txt_ch_member_36 = "새가족 모임";
$txt_ch_member_37 = "신 급";
$txt_ch_member_371 = "세 례";
$txt_ch_member_372 = "영아세례";
$txt_ch_member_373 = "유아세례";
$txt_ch_member_374 = "입 교";
$txt_ch_member_375 = "침 례";
$txt_ch_member_376 = "학 습";
$txt_ch_member_38 = "교회 등록일";
$txt_ch_member_380 = "제적교인";
$txt_ch_member_381 = "미등록";
$txt_ch_member_382 = "등록교인";
$txt_ch_member_39 = "여권 번호";
$txt_ch_member_40 = "여권 만료일";
$txt_ch_member_41 = "국 적";
$txt_ch_member_42 = "비자 종류";
$txt_ch_member_43 = "배우자";
$txt_ch_member_44 = "사진";

$txt_ch_member_60 = "구역장 주간 보고서";
$txt_ch_member_611 = "주일 출석";
$txt_ch_member_612 = "순예배 출석";
$txt_ch_member_621 = "여부";
$txt_ch_member_6211 = "출석";
$txt_ch_member_6212 = "결석";
$txt_ch_member_622 = "사유";
$txt_ch_member_63 = "조치사항";
$txt_ch_member_631 = "구역장 조치사항";
$txt_ch_member_632 = "담당 교역자 조치사항";
$txt_ch_member_64 = "기도 제목";
$txt_ch_member_65 = "전 송";

$txt_ch_member_chk01 = "시스템을 선택하세요.";


// chmember > member (detail)
$txt_tab_member_01 = "일 반";
$txt_tab_member_A = "주 소";
$txt_tab_member_A01 = "가족단위로 수정";

$txt_tab_member_02 = "가 족";
$txt_tab_member_0201 = "관 계";
$txt_tab_member_0202 = "나 이";
$txt_tab_member_0203 = "학 력";
$txt_tab_member_0204 = "종 교";
$txt_tab_member_0210 = "세대주와의 관계";
$txt_tab_member_0210M = "남 편";
$txt_tab_member_0210F = "아 내";
$txt_tab_member_0211 = "부 모";
$txt_tab_member_0211M = "부";
$txt_tab_member_0211F = "모";
$txt_tab_member_0212 = "자 녀";
$txt_tab_member_0212M = "아 들";
$txt_tab_member_0212F = "딸";
$txt_tab_member_0213 = "친 지";
$txt_tab_member_0214 = "친 구";
$txt_tab_member_0219 = "기 타";
$txt_tab_member_02x = "직접 입력";
$txt_tab_member_03 = "직장/학교";
$txt_tab_member_0301 = "직 장";
$txt_tab_member_0302 = "직 종";
$txt_tab_member_0303 = "직 업";
$txt_tab_member_0304 = "직장명";
$txt_tab_member_0305 = "회사 소개";
$txt_tab_member_0306 = "입 사";
$txt_tab_member_0307 = "퇴 사";

$txt_tab_member_0351 = "학 교";
$txt_tab_member_0352 = "학교명";
$txt_tab_member_0353 = "구 분";
$txt_tab_member_03531 = "유치원";
$txt_tab_member_03532 = "초등학교";
$txt_tab_member_03533 = "중학교";
$txt_tab_member_03534 = "고등학교";
$txt_tab_member_03535 = "대학(2년)";
$txt_tab_member_03536 = "대학(3년)";
$txt_tab_member_03537 = "대학교(학사)";
$txt_tab_member_03538 = "대학원(석사)";
$txt_tab_member_03539 = "대학원(박사)";
$txt_tab_member_0354 = "학교소재지";
$txt_tab_member_0355 = "전공/과";
$txt_tab_member_0356 = "입 학";
$txt_tab_member_0357 = "졸 업";
$txt_tab_member_0358 = "졸업 여부";
$txt_tab_member_03580 = "중 퇴";
$txt_tab_member_03581 = "재학중";
$txt_tab_member_03582 = "졸 업";

$txt_tab_member_04 = "신 급";
$txt_tab_member_0401 = "개신교";
$txt_tab_member_0402 = "카톨릭";
$txt_tab_member_0403 = "불 교";
$txt_tab_member_0404 = "이슬람교";
$txt_tab_member_0405 = "힌두교";
$txt_tab_member_0409 = "기 타";
$txt_tab_member_0421 = "교회/단체";
$txt_tab_member_0422 = "교파/교단";
$txt_tab_member_0423 = "국가/지역";
$txt_tab_member_0424 = "입교년도";
$txt_tab_member_0425 = "수세년도";
$txt_tab_member_0426 = "제적년도";
$txt_tab_member_0427 = "제적사유";
$txt_tab_member_0428 = "본교회";
$txt_tab_member_0429 = "직 분";
$txt_tab_member_0430 = "담임목사";

$txt_tab_member_05 = "훈련/활동";
$txt_tab_member_0501 = "이전 교회";
$txt_tab_member_0502 = "교회 이름";
$txt_tab_member_0503 = "항목별 평가";
$txt_tab_member_0504 = "수료 여부";
$txt_tab_member_05040 = "미수료";
$txt_tab_member_05041 = "수료중";
$txt_tab_member_05042 = "수 료";
$txt_tab_member_0506 = "점 수";
$txt_tab_member_0507 = "평 가";
$txt_tab_member_0508 = "참고 사항";
$txt_tab_member_0509 = "교역자 견해";

$txt_tab_member_06 = "특기사항";
$txt_tab_member_0601 = "인도자";
$txt_tab_member_0602 = "혈액형";
$txt_tab_member_0603 = "결혼 기념일";
$txt_tab_member_0604 = "가정 형편";
$txt_tab_member_0605 = "취 미";
$txt_tab_member_0606 = "특 기";
$txt_tab_member_0607 = "은 사";
$txt_tab_member_0608 = "건 강";
$txt_tab_member_0609 = "차량 번호";
$txt_tab_member_0610 = "주차장 번호";

$txt_tab_member_07 = "헌 금";
$txt_tab_member_07s = "헌금";
$txt_tab_member_0701 = "헌금 구분";
$txt_tab_member_0702 = "헌금자 선택";
$txt_tab_member_0703 = "헌금자 이름";
$txt_tab_member_0704 = "직접 입력";
$txt_tab_member_0705 = "금 액";
$txt_tab_member_0706 = "입 력";
$txt_tab_member_0707 = "계수 완료";
$txt_tab_member_0708 = "무 명";
$txt_tab_member_0709 = "헌금자 리스트";
$txt_tab_member_0710 = "헌금 계수일";
$txt_tab_member_0711 = "총 헌금 합계";
$txt_tab_member_0712 = "헌금 현황 보고";
$txt_tab_member_0713 = "헌금 현황";
$txt_tab_member_0714 = "종합";
$txt_tab_member_0715 = "구 분";
$txt_tab_member_0716 = "비 고";
$txt_tab_member_0717 = "확 인";
$txt_tab_member_0718 = "서명";
$txt_tab_member_0719 = "재정부장";
$txt_tab_member_0720 = "회 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 계";
$txt_tab_member_0721 = "현금담당";
$txt_tab_member_0722 = "소 계";
$txt_tab_member_0723 = "합 계";
$txt_tab_member_0724 = "헌금일";

$txt_tab_member_08 = "심 방";
$txt_tab_member_0801 = "심방 일시";
$txt_tab_member_0802 = "심방 제목/사유";
$txt_tab_member_0803 = "심방 장소";
$txt_tab_member_0804 = "심방자";
$txt_tab_member_0805 = "기록일시";
$txt_tab_member_0806 = "기록자";
$txt_tab_member_0807 = "심방 메모";
$txt_tab_member_0808 = "찬 송";
$txt_tab_member_0809 = "기 도";
$txt_tab_member_0810 = "성 경";
$txt_tab_member_0811 = "인 도";

$txt_tab_member_09 = "변경사항";
$txt_tab_member_0901 = "변경일";
$txt_tab_member_0902 = "교인 상태";
$txt_tab_member_09021 = "새가족";
$txt_tab_member_09022 = "교 인";
$txt_tab_member_09023 = "제 적";

$txt_tab_member_chk01 = "금액을 입력하셔야 합니다.";
$txt_tab_member_chk02 = "아래에 이름을 직접 입력하세요.";
$txt_tab_member_chk03 = "계수를 완료하시겠습니까?";
$txt_tab_member_chk04 = "삭제하시겠습니까?";


// member > member
$txt_stf_member_01 = "회원 리스트";
$txt_stf_member_02 = "회원 등록하기";
$txt_stf_member_03 = "회원 수정하기";
$txt_stf_member_04 = "회원 삭제하기";
$txt_stf_member_05 = "회원 코드";
$txt_stf_member_06 = "회원 ID";
$txt_stf_member_07 = "회원 등급";
$txt_stf_member_08 = "회사/단체명";
$txt_stf_member_09 = "웹사이트 DB 연동 여부";
$txt_stf_member_10 = "단 절";
$txt_stf_member_11 = "중 복";
$txt_stf_member_12 = "통 합";
$txt_stf_member_13 = "마일리지 포인트";
$txt_stf_member_14 = "리셀러";
$txt_stf_member_15 = "일반 회원";
$txt_stf_member_16 = "뉴스 레터";
$txt_stf_member_17 = "가 입";
$txt_stf_member_18 = "해 제";
$txt_stf_member_51 = "대리점 리스트";
$txt_stf_member_52 = "대리점 등록하기";
$txt_stf_member_53 = "대리점 수정하기";
$txt_stf_member_54 = "대리점 삭제하기";
$txt_stf_member_55 = "대리점 코드";
$txt_stf_member_57 = "대리점 등급";
$txt_stf_member_60 = "결제 은행(지점)";
$txt_stf_member_61 = "예금주";
$txt_stf_member_62 = "계좌 번호";

$txt_stf_member_chk01 = "System을 선택하세요.";

// member > staff
$txt_stf_staff_01 = "사원 리스트";
$txt_stf_staff_02 = "사원 등록하기";
$txt_stf_staff_03 = "사원 수정하기";
$txt_stf_staff_04 = "사원 삭제하기";
$txt_stf_staff_05 = "Shop 회원 ID";
$txt_stf_staff_06 = "해당사항 없음";
$txt_stf_staff_07 = "사원 코드";
$txt_stf_staff_08 = "이 름";
$txt_stf_staff_09 = "성 별";
$txt_stf_staff_10 = "남";
$txt_stf_staff_11 = "여";
$txt_stf_staff_12 = "생년월일";
$txt_stf_staff_13 = "양력";
$txt_stf_staff_14 = "음력";
$txt_stf_staff_15 = "부 서";
$txt_stf_staff_16 = "직 책";
$txt_stf_staff_17 = "직 급";
$txt_stf_staff_18 = "지사 선택";

$txt_stf_staff_chk01 = "이름을 입력하세요.";
$txt_stf_staff_chk02 = "입력하신 이름과 동일인이 있습니다.";
$txt_stf_staff_chk03 = "확인하시고 다시 입력하여 주십시오.";
$txt_stf_staff_chk04 = "회사를 선택하세요.";


// member > special
$txt_stf_model_01 = "모델 리스트";
$txt_stf_model_02 = "모델 등록하기";
$txt_stf_model_03 = "모델 수정하기";
$txt_stf_model_04 = "모델 삭제하기";
$txt_stf_model_05 = "Shop 회원 ID";
$txt_stf_model_06 = "해당사항 없음";
$txt_stf_model_07 = "계약 유형";
$txt_stf_model_07_01 = "계약직";
$txt_stf_model_07_02 = "프리랜서";
$txt_stf_model_08 = "상세 프로필";
$txt_stf_model_09 = "계약 기간";
$txt_stf_model_10 = "VISA";
$txt_stf_model_11 = "계약 만료일";


// system > client
$txt_sys_client_01 = "System 이름";
$txt_sys_client_02 = "코드";
$txt_sys_client_03 = "System ID";
$txt_sys_client_04 = "System 등급";
$txt_sys_client_05 = "웹사이트";
$txt_sys_client_06 = "등록일";
$txt_sys_client_061 = "시스템 등록일";
$txt_sys_client_062 = "최종 변경일시";
$txt_sys_client_07 = "최고관리자 이름";
$txt_sys_client_08 = "전화번호";
$txt_sys_client_09 = "휴대폰";
$txt_sys_client_10 = "System 리스트";
$txt_sys_client_11 = "System 등록하기";
$txt_sys_client_12 = "System 수정하기";
$txt_sys_client_13 = "System 삭제하기";
$txt_sys_client_14 = "주 소";
$txt_sys_client_15 = "우편번호";
$txt_sys_client_16 = "Street";
$txt_sys_client_17 = "City, State";
$txt_sys_client_18 = "DB 계정";
$txt_sys_client_19 = "DB명,계정명,비밀번호";
$txt_sys_client_20 = "새 비밀번호";
$txt_sys_client_21 = "재입력";
$txt_sys_client_22 = "변경하기";
$txt_sys_client_23 = "프로필";
$txt_sys_client_24 = "계약관계";
$txt_sys_client_25 = "연락정보";
$txt_sys_client_26 = "관리자 메모";

$txt_sys_client_chk01 = "ID를 입력하세요.";
$txt_sys_client_chk02 = "ID는 4~12자의 영소문자 또는 영소문자와 숫자의 결합이어야 합니다.";
$txt_sys_client_chk03 = "ID의 첫글자는 언제나 영소문자여야 합니다.";
$txt_sys_client_chk04 = "공백이 허용되지 않습니다.";
$txt_sys_client_chk05 = "비밀번호를 입력하세요.";
$txt_sys_client_chk06 = "비밀번호는 4~12자의 영문자와 숫자 또는 영문자와 숫자의 결합이어야 합니다.";
$txt_sys_client_chk07 = "시스템의 Client 이름을 입력하세요.";
$txt_sys_client_chk08 = "E-mail 주소를 입력하세요.";
$txt_sys_client_chk09 = "E-mail 주소의 형식이 틀렸습니다.";
$txt_sys_client_chk10 = "인증번호를 입력하세요.";


// system > user
$txt_sys_user_01 = "시스템 Manager 리스트";
$txt_sys_user_02 = "시스템 Manager 등록하기";
$txt_sys_user_03 = "시스템 Manager 수정하기";
$txt_sys_user_04 = "시스템 Manager 삭제하기";
$txt_sys_user_05 = "Manager ID";
$txt_sys_user_06 = "Manager 이름";
$txt_sys_user_07 = "시스템";
$txt_sys_user_08 = "Manager 등급";
$txt_sys_user_09 = "지난 로그인";
$txt_sys_user_10 = "방문수";
$txt_sys_user_11 = "사용 언어";
$txt_sys_user_12 = "로그인 기록 없음";

$txt_sys_user_chk01 = "시스템 Manager 이름을 입력하세요.";
$txt_sys_user_chk02 = "";
$txt_sys_user_chk03 = "입력하신 두 비밀번호가 일치하지 않습니다.";


// system > church_job category [*]
$txt_sys_chjob_01 = "구 분";
$txt_sys_chjob_011 = "교역자";
$txt_sys_chjob_012 = "평신도";
$txt_sys_chjob_013 = "일반인(태신자)";
$txt_sys_chjob_02 = "코 드";
$txt_sys_chjob_031 = "직위 이름";
$txt_sys_chjob_032 = "직분 이름";
$txt_sys_chjob_033 = "직업 이름";
$txt_sys_chjob_04 = "코드 등록하기";
$txt_sys_chjob_05 = "코드 수정하기";
$txt_sys_chjob_06 = "코드 삭제하기";

$txt_sys_chjob_chk01 = "코드를 입력하세요.";
$txt_sys_chjob_chk02 = "분류명을 입력하세요.";
$txt_sys_chjob_chk03 = "동일한 코드가 존재합니다.";


// system > tarin_course [*]
$txt_sys_tcourse_01 = "훈련/활동 과정";
$txt_sys_tcourse_02 = "훈련/활동 과정 등록";
$txt_sys_tcourse_03 = "훈련/활동 과정 수정";
$txt_sys_tcourse_04 = "훈련/활동 과정 삭제";
$txt_sys_tcourse_05 = "과정 코드";
$txt_sys_tcourse_051 = "훈련/활동 카테고리";
$txt_sys_tcourse_06 = "훈련/활동 이름";
$txt_sys_tcourse_07 = "기 수";
$txt_sys_tcourse_08 = "시작일";
$txt_sys_tcourse_09 = "수료일";
$txt_sys_tcourse_10 = "강 사";
$txt_sys_tcourse_11 = "수강 대상";
$txt_sys_tcourse_12 = "과정 기간";
$txt_sys_tcourse_13 = "과정 시간";
$txt_sys_tcourse_14 = "과정 내용";
$txt_sys_tcourse_1501 = "출 석";
$txt_sys_tcourse_1502 = "태 도";
$txt_sys_tcourse_1503 = "달성도";
$txt_sys_tcourse_1504 = "지 식";
$txt_sys_tcourse_1505 = "시 험";
$txt_sys_tcourse_1506 = "과제물";
$txt_sys_tcourse_15 = "평가 항목";
$txt_sys_tcourse_16 = "수강료";

$txt_sys_tcourse_chk01 = "카테고리를 선택하셔야 합니다.";


// system > train_course [church]
$txt_sys_chcourse_1501 = "출 석";
$txt_sys_chcourse_1502 = "기 도";
$txt_sys_chcourse_1503 = "큐 티";
$txt_sys_chcourse_1504 = "성경지식";
$txt_sys_chcourse_1505 = "시 험";
$txt_sys_chcourse_1506 = "과제물";


// system > shop
$txt_sys_shop_01 = "매장 리스트";
$txt_sys_shop_02 = "매장 등록하기";
$txt_sys_shop_03 = "매장 수정하기";
$txt_sys_shop_04 = "매장 삭제하기";
$txt_sys_shop_05 = "매장 코드";
$txt_sys_shop_06 = "매장 이름";
$txt_sys_shop_07 = "매장 유형";
$txt_sys_shop_071 = "직영 매장";
$txt_sys_shop_072 = "위탁판매 매장";
$txt_sys_shop_073 = "협력 매장";
$txt_sys_shop_08 = "관리자";
$txt_sys_shop_09 = "운영";
$txt_sys_shop_10 = "중지";
$txt_sys_shop_11 = "운영";
$txt_sys_shop_12 = "온라인";
$txt_sys_shop_13 = "오프라인";
$txt_sys_shop_14 = "온/오프라인";
$txt_sys_shop_15 = "매장 규모별 구분";
$txt_sys_shop_151 = "대형 매장";
$txt_sys_shop_152 = "수퍼마켓";

$txt_sys_shop_chk01 = "매장 코드를 입력하세요.";
$txt_sys_shop_chk02 = "매장 코드는 4~12자의 영소문자 또는 영소문자와 숫자의 결합이어야 합니다.";
$txt_sys_shop_chk03 = "매장 코드의 첫글자는 언제나 영소문자여야 합니다.";
$txt_sys_shop_chk04 = "공백이 허용되지 않습니다.";
$txt_sys_shop_chk05 = "매장 이름을 입력하세요.";


// system > user2
$txt_sys_user2_01 = "Shop Manager 리스트";
$txt_sys_user2_02 = "Shop Manager 등록하기";
$txt_sys_user2_03 = "Shop Manager 수정하기";
$txt_sys_user2_04 = "Shop Manager 삭제하기";
$txt_sys_user2_05 = "Manager ID";
$txt_sys_user2_06 = "Manager 이름";
$txt_sys_user2_07 = "Shop";
$txt_sys_user2_08 = "Manager 등급";
$txt_sys_user2_09 = "지난 로그인";
$txt_sys_user2_10 = "방문수";
$txt_sys_user2_11 = "사용 언어";
$txt_sys_user2_12 = "로그인 기록 없음";

$txt_sys_user2_chk01 = "Shop Manager 이름을 입력하세요.";
$txt_sys_user2_chk02 = "";
$txt_sys_user2_chk03 = "입력하신 두 비밀번호가 일치하지 않습니다.";


// system > supplier
$txt_sys_supplier_01 = "공급자 리스트";
$txt_sys_supplier_02 = "공급자 등록하기";
$txt_sys_supplier_03 = "공급자 수정하기";
$txt_sys_supplier_04 = "공급자 삭제하기";
$txt_sys_supplier_05 = "공급자 코드";
$txt_sys_supplier_06 = "공급자 이름";
$txt_sys_supplier_07 = "공급 유형";
$txt_sys_supplier_071 = "해외 (수입)";
$txt_sys_supplier_072 = "국내";
$txt_sys_supplier_08 = "담당자";
$txt_sys_supplier_09 = "상태";
$txt_sys_supplier_10 = "보류";
$txt_sys_supplier_11 = "거래";
$txt_sys_supplier_12 = "공급자 선택";
$txt_sys_supplier_13 = "공급자를 선택하세요.";
$txt_sys_supplier_14 = "공급자";

$txt_sys_supplier_chk01 = "공급자 이름을 입력하세요.";


// system > brand
$txt_sys_brand_01 = "브랜드 리스트";
$txt_sys_brand_02 = "브랜드 등록하기";
$txt_sys_brand_03 = "브랜드 수정하기";
$txt_sys_brand_04 = "브랜드 삭제하기";
$txt_sys_brand_05 = "브랜드 코드";
$txt_sys_brand_06 = "브랜드 이름";
$txt_sys_brand_07 = "원산지";
$txt_sys_brand_09 = "상태";
$txt_sys_brand_12 = "브랜드 선택";
$txt_sys_brand_13 = "브랜드를 선택하세요.";
$txt_sys_brand_14 = "브랜드";

$txt_sys_brand_chk01 = "브랜드 이름을 입력하세요.";


// system > consign
$txt_sys_consign_01 = "위탁판매 그룹 리스트";
$txt_sys_consign_02 = "위탁판매 그룹 등록하기";
$txt_sys_consign_03 = "위탁판매 그룹 수정하기";
$txt_sys_consign_04 = "위탁판매 그룹 삭제하기";
$txt_sys_consign_05 = "그룹 코드";
$txt_sys_consign_06 = "그룹 이름";
$txt_sys_consign_07 = "그룹 유형";
$txt_sys_consign_12 = "위탁판매 그룹 선택";
$txt_sys_consign_13 = "위탁판매 그룹을 선택하세요.";
$txt_sys_consign_14 = "위탁판매 그룹";

$txt_sys_consign_chk01 = "위탁판매 그룹 이름을 입력하세요.";


// system > category
$txt_sys_category_01 = "카테고리";
$txt_sys_category_02 = "카테고리 추가하기";
$txt_sys_category_03 = "카테고리 수정하기";
$txt_sys_category_04 = "카테고리 삭제하기";
$txt_sys_category_05 = "대분류";
$txt_sys_category_06 = "중분류";
$txt_sys_category_07 = "새 카테고리 추가";
$txt_sys_category_08 = "전체 카테고리 삭제";

$txt_sys_category_chk01 = "1개 이상의 하부 카테고리가 있어야 합니다.";
$txt_sys_category_chk02 = "하부 카테고리가 있는 대분류는 삭제할 수 없습니다.";
$txt_sys_category_chk03 = "해당 상품이 있으면 중분류를 삭제할 수 없습니다.";


// system > mileage
$txt_sys_mileage_01 = "마일리지 현황";
$txt_sys_mileage_02 = "마일리지";
$txt_sys_mileage_03 = "수정일";
$txt_sys_mileage_04 = "초기값";


// system > discount
$txt_sys_discount_01 = "리셀러 할인율 현황";
$txt_sys_discount_02 = "할인율";


// system > voucher
$txt_sys_voucher_01 = "바우처 리스트";
$txt_sys_voucher_02 = "바우처 발행하기";
$txt_sys_voucher_03 = "바우처 수정하기";
$txt_sys_voucher_04 = "바우처 삭제하기";
$txt_sys_voucher_05 = "바우처 코드";
$txt_sys_voucher_06 = "바우처 액면가";
$txt_sys_voucher_07 = "발행수";
$txt_sys_voucher_07_1 = "사용수";
$txt_sys_voucher_07_2 = "잔여수";
$txt_sys_voucher_08 = "바우처 효력";
$txt_sys_voucher_09 = "바우처 발행일";
$txt_sys_voucher_10 = "바우처 유효기간";

$txt_sys_voucher_chk01 = "바우처 액면가를 입력하세요.";
$txt_sys_voucher_chk02 = "바우처 발행수를 입력하세요.";


// system > voucher2
$txt_sys_voucher2_01 = "YARNEN (수확물 대납)";
$txt_sys_voucher2_02 = "YARNEN 옵션 추가";
$txt_sys_voucher2_03 = "YARNEN 옵션 수정하기";
$txt_sys_voucher2_04 = "YARNEN 옵션 삭제하기";
$txt_sys_voucher2_05 = "YARNEN 옵션 코드";
$txt_sys_voucher2_06 = "YARNEN 옵션 이름";
$txt_sys_voucher2_07 = "YARNEN 비율";
$txt_sys_voucher2_08 = "YARNEN 상세 내역";
$txt_sys_voucher2_09 = "농지의 총수확물 중에서";
$txt_sys_voucher2_10 = "수확물 대납 옵션을 선택하세요.";
$txt_sys_voucher2_11 = "YARNEN을 사용하지 않음";
$txt_sys_voucher2_12 = "개월";

$txt_sys_voucher2_chk01 = "YARNEN 옵션 코드를 입력하세요.";
$txt_sys_voucher2_chk02 = "YARNEN 옵션 이름을 입력하세요.";
$txt_sys_voucher2_chk03 = "YARNEN 비율을 입력하세요.";


// system > discount2
$txt_sys_discount2_01 = "특별 행사가 현황";


// system > bank
$txt_sys_bank_01 = "결제은행 계좌 리스트";
$txt_sys_bank_02 = "결제은행 등록하기";
$txt_sys_bank_03 = "결제은행 수정하기";
$txt_sys_bank_04 = "결제은행 삭제하기";
$txt_sys_bank_05 = "결제은행 코드";
$txt_sys_bank_06 = "결제은행 이름";
$txt_sys_bank_07 = "계좌번호";
$txt_sys_bank_08 = "예금주";
$txt_sys_bank_09 = "은행 지점 이름";
$txt_sys_bank_10 = "SWIFT CODE";
$txt_sys_bank_11 = "담당자";
$txt_sys_bank_12 = "담당자 Email";
$txt_sys_bank_13 = "통 화";
$txt_sys_bank_14 = "초기 잔액";
$txt_sys_bank_15 = "미수금";

$txt_sys_bank_chk01 = "결제은행 이름을 입력하셔야 합니다.";


// system > card
$txt_sys_card_01 = "신용카드 결제기 리스트";
$txt_sys_card_02 = "신용카드 결제기 등록하기";
$txt_sys_card_03 = "신용카드 결제기 수정하기";
$txt_sys_card_04 = "신용카드 결제기 삭제하기";
$txt_sys_card_05 = "분류 코드";
$txt_sys_card_06 = "신용카드 결제기";
$txt_sys_card_07 = "신용카드 결제은행";
$txt_sys_card_08 = "카드 수수료";

$txt_sys_card_chk01 = "신용카드 이름을 입력하셔야 합니다.";


// system > zone_area
$txt_sys_area_01 = "배송지 리스트";
$txt_sys_area_02 = "배송지 정보 등록하기";
$txt_sys_area_03 = "배송지 정보 수정하기";
$txt_sys_area_04 = "배송지 정보 삭제하기";
$txt_sys_area_05 = "지역 코드";
$txt_sys_area_06 = "국 가";
$txt_sys_area_07 = "도시/지역 이름";
$txt_sys_area_08 = "배송료";
$txt_sys_area_09 = "최저 임금";

$txt_sys_area_chk01 = "지역 코드를 입력하셔야 합니다.";
$txt_sys_area_chk02 = "지역 이름을 입력하셔야 합니다.";


// system > loan
$txt_sys_loan_01 = "은행 차입";
$txt_sys_loan_02 = "은행 차입 등록하기";
$txt_sys_loan_03 = "은행 차입 수정하기";
$txt_sys_loan_04 = "은행 차입 삭제하기";
$txt_sys_loan_05 = "은행대출 코드";
$txt_sys_loan_06 = "차입 은행";
$txt_sys_loan_07 = "대출 상품명";
$txt_sys_loan_08 = "차입 금액";
$txt_sys_loan_09 = "차입 이자";
$txt_sys_loan_10 = "차입일";
$txt_sys_loan_11 = "만기일";
$txt_sys_loan_12 = "은행 차입 사용하기";
$txt_sys_loan_13 = "사용하지 않음";
$txt_sys_loan_14 = "차입 가능분";
$txt_sys_loan_15 = "차입 요청";
$txt_sys_loan_16 = "대출 한도";

$txt_sys_loan_chk01 = "차입 은행을 선택하세요.";
$txt_sys_loan_chk02 = "대출 상품명 선택하세요.";
$txt_sys_loan_chk03 = "차입 금액을 선택하세요.";


// system > account
$txt_sys_account_01 = "계정항목 리스트";
$txt_sys_account_02 = "계정항목 등록하기";
$txt_sys_account_03 = "계정항목 수정하기";
$txt_sys_account_04 = "계정항목 삭제하기";
$txt_sys_account_05 = "수 입";
$txt_sys_account_05_A1 = "판매 수입";
$txt_sys_account_05_A2 = "주일 학교";
$txt_sys_account_05_A3 = "주일 헌금";
$txt_sys_account_05_A4 = "기타 헌금";
$txt_sys_account_05_A4051 = "부활절";
$txt_sys_account_05_A4052 = "추수감사절";
$txt_sys_account_05_A4053 = "성탄절";
$txt_sys_account_05_A5 = "기타 수입";
$txt_sys_account_06 = "지 출";
$txt_sys_account_06_B1 = "직접 비용";
$txt_sys_account_06_B2 = "간접 비용";
$txt_sys_account_06_B3 = "인건비";
$txt_sys_account_09 = "항목 추가";
$txt_sys_account_10 = "등 록";


// user
$txt_user_01 = "언어 변경하기";
$txt_user_02 = "비밀번호 변경하기";
$txt_user_03 = "현 비밀번호";
$txt_user_04 = "개인정보 변경하기";
$txt_user_05 = "";




// Website
// website > menu
$txt_web_menu_01 = "메뉴 리스트";
$txt_web_menu_02 = "메뉴 등록하기";
$txt_web_menu_03 = "메뉴 수정하기";
$txt_web_menu_04 = "메뉴 삭제하기";
$txt_web_menu_05 = "메뉴 이름"; // Menu Title
$txt_web_menu_06 = "메뉴 속성"; // Menu Format
$txt_web_menu_type_news = "뉴스 클립"; // News Clip
$txt_web_menu_type_emag = "매거진"; // Magazine
$txt_web_menu_type_hist = "연혁"; // History
$txt_web_menu_type_serm = "설교"; // Sermon
$txt_web_menu_type_faq = "자주 묻는 질문 (FAQ)"; // FAQ
$txt_web_menu_type_qna = "묻고 답하기 (Q&A)"; // Q&A
$txt_web_menu_type_book = "방명록"; // Guest Book
$txt_web_menu_type_bbs = "게시판"; // Board
$txt_web_menu_type_bbsm = "게시판 (사고팔기)"; // Board (Marketplace)
$txt_web_menu_type_bbsj = "게시판 (구인구직)"; // Board (Recruitment)
$txt_web_menu_type_alb1 = "포토 갤러리 (가로 1칸)"; // Photo Gallery (1 Column)
$txt_web_menu_type_alb2 = "포토 갤러리 (가로 2칸)"; // Photo Gallery (2 Columns)
$txt_web_menu_type_alb4 = "포토 갤러리 (가로 4칸)"; // Photo Gallery (4 Columns)
$txt_web_menu_type_alb5 = "포토 갤러리 (가로 5칸)"; // Photo Gallery (5 Columns)
$txt_web_menu_type_albx = "포토 갤러리 (디렉토리)"; // Photo Gallery (Directory)
$txt_web_menu_type_week = "주보"; // Weekly Bulletin
$txt_web_menu_type_blnk = "빈 페이지"; // Blank Page
$txt_web_menu_type_pop = "* 팝업 페이지에 연결 *"; // * Link to Pop-up Page *
$txt_web_menu_type_link = "* 특정 URL에 연결 *"; // * Link to URL *
$txt_web_menu_type_rss = "* RSS에 연결 *"; // * Link to RSS *
$txt_web_menu_type_x = "* 서브 페이지에 연결 *"; // * Link to Sub Page *

$txt_web_menu_07 = "첨부 옵션"; // Option
$txt_web_menu_opt_0 = "기본"; // Default
$txt_web_menu_opt_1 = "이미지"; // Attach Image
$txt_web_menu_opt_2 = "Flash 무비 (SWF)"; // Attach Flash Movie (SWF)
$txt_web_menu_opt_3 = "일반 파일 (자료실 운영)"; // Attach File (Resource Centre)
$txt_web_menu_opt_4 = "오디오 파일 및 MP3"; // Attach Audio File & MP3
$txt_web_menu_opt_5 = "동영상 파일"; // Attach Movie Clip
$txt_web_menu_opt_6 = "동영상 파일 (FLV/MP4)"; // Attach Movie Clip (FLV/MP4)
$txt_web_menu_opt_8 = "메일 발송 폼"; // Attach Form Mailer

$txt_web_menu_08 = "개수"; // Number
$txt_web_menu_08d = "일"; // Day
$txt_web_menu_08dp = "일"; // Days
$txt_web_menu_082 = "개 / 페이지"; // articles / page
$txt_web_menu_09 = "추가+"; // Add+
$txt_web_menu_10 = "메뉴 추가"; // Add Menu
$txt_web_menu_11 = "홈페이지 주소"; // Website URL
$txt_web_menu_12 = "메뉴 코드"; // Menu Code
$txt_web_menu_13 = "메뉴 단계 구분"; // Menu Depth
$txt_web_menu_131 = "메인 메뉴"; // Main Menu
$txt_web_menu_132 = "서브 메뉴"; // Sub Menu
$txt_web_menu_14 = "사용하기"; // In Use
$txt_web_menu_15 = "신규 게시물 표시"; // New Article
$txt_web_menu_16 = "게시물 수"; // Number of rows
$txt_web_menu_17 = "게시물 접근허가"; // Permission
$txt_web_menu_permit_0 = "제한 없음"; // Free Access
$txt_web_menu_permit_1 = "로그인 후 쓰기 가능"; // Writeable After Login
$txt_web_menu_permit_2 = "언제나 읽기만 가능"; // Read-Only Before/After Login
$txt_web_menu_permit_3 = "로그인 후 읽기만 가능"; // Read-Only After Login
$txt_web_menu_permit_4 = "로그인한 회원만 이용 가능"; // Free Access By Member After Login
$txt_web_menu_permit_5 = "로그인한 직원만 이용 가능"; // Free Access By Staff After Login
$txt_web_menu_permit_6 = "관리자 외 사용 금지"; // No Access Permitted Except Admin

$txt_web_menu_18 = "메뉴 위치"; // Menu Location
$txt_web_menu_loco_intro1 = "인트로 페이지"; // Intro Page
$txt_web_menu_loco_intro2 = "대쉬보드"; // Dashboard
$txt_web_menu_loco_head = "상단"; // Header
$txt_web_menu_loco_foot = "하단"; // Footer
$txt_web_menu_loco_short = "단축 메뉴"; // Short Cut

$txt_web_menu_19 = "정렬 방법"; // Order By
$txt_web_menu_191 = "내림차순"; // DESCending
$txt_web_menu_192 = "오름차순"; // ASCending
$txt_web_menu_193 = "무작위"; // RANDOM
$txt_web_menu_20 = "특정 사이트에 연결"; // Connect to Site
$txt_web_menu_21 = "특정 URL에 연결"; // Connect to URL
$txt_web_menu_22 = "연결 하기"; // Link now
$txt_web_menu_23 = "";
$txt_web_menu_24 = "";
$txt_web_menu_25 = "";


// website > content
$txt_web_content_01 = "콘텐츠 리스트";
$txt_web_content_02 = "콘텐츠 등록하기";
$txt_web_content_03 = "콘텐츠 수정하기";
$txt_web_content_04 = "콘텐츠 삭제하기";
$txt_web_content_order0 = "수정순"; // Updated
$txt_web_content_order1 = "제목순"; // Subject
$txt_web_content_order2 = "내용순"; // Contents
$txt_web_content_order3 = "게시일순"; // Posting Date
$txt_web_content_order4 = "최근수정순"; // Last Updated

$txt_web_content_05 = "콘텐츠 추가"; // Add Content
$txt_web_content_06 = "리스트"; // List
$txt_web_content_07 = "제목"; // Title
$txt_web_content_08 = "부제목"; // Subtitle
$txt_web_content_09 = "내용"; // Content
$txt_web_content_10 = "이미지 파일"; // Image File
$txt_web_content_10p = "교체"; // Replace
$txt_web_content_11 = "이미지 설명글"; // Image Caption
$txt_web_content_12 = "게시"; // Show
$txt_web_content_121 = "보여짐"; // Shown
$txt_web_content_122 = "숨김"; // Hidden
$txt_web_content_13 = "단락 추가하기"; // Add Paragraph
$txt_web_content_14 = "작가를 선택하세요"; // Select Writer
$txt_web_content_15 = "작가 미지정"; // 
$txt_web_content_16 = "콘텐츠 생성하기"; // Create Contents
$txt_web_content_17 = "콘텐츠 타입"; // Contents Type
$txt_web_content_18 = "이미지 파일 올리기"; // Upload Image File


// website > banner1
$txt_web_banner1_01 = "배너 파일 리스트";
$txt_web_banner1_02 = "배너 파일 등록하기";
$txt_web_banner1_03 = "배너 파일 수정하기";
$txt_web_banner1_04 = "배너 파일 삭제하기";
$txt_web_banner1_order0 = "배너 코드순"; // Banner Code
$txt_web_banner1_order1 = "배너 등록순"; // Upload Date
$txt_web_banner1_05 = "배너 코드(ID)"; // Banner Code(ID)
$txt_web_banner1_05s = "코드(ID)"; // Code(ID)
$txt_web_banner1_06 = "배너 타입"; // Banner Type
$txt_web_banner1_07 = "파일 크기"; // File Size
$txt_web_banner1_08 = "배너 파일 추가"; // Add Banner File
$txt_web_banner1_09 = "배너 파일명"; // Banner File Name
$txt_web_banner1_10 = "배너 파일 올리기"; // Upload Banner File
$txt_web_banner1_11 = "배너 크기"; // Banner Dimension
$txt_web_banner1_111 = "가로"; // Width
$txt_web_banner1_112 = "세로"; // Height
$txt_web_banner1_12 = "픽셀"; // Pixel
$txt_web_banner1_13 = "배너 파일 교체"; // Replace Banner File
$txt_web_banner1_14 = ""; //
$txt_web_banner1_15 = ""; //


// website > banner2
$txt_web_banner2_01 = "배너 게시 리스트";
$txt_web_banner2_02 = "배너 게시 등록하기";
$txt_web_banner2_03 = "배너 게시 수정하기";
$txt_web_banner2_04 = "배너 게시 삭제하기";
$txt_web_banner2_05 = "게시 위치"; // Location
$txt_web_banner2_05b = "배너 게시 위치"; // Banner Location
$txt_web_banner2_06 = "광고주 계정"; // Account
$txt_web_banner2_06b = "배너 광고주 계정"; // Banner Account
$txt_web_banner2_07 = "배너 게시 추가"; // Add Banner Display
$txt_web_banner2_08 = "배너 연결 URL"; // Banner URL
$txt_web_banner2_09 = "배경색"; // Bg Color
$txt_web_banner2_10 = "'Custom' 선택시, Target 이름"; // When 'Custom', input Target name
$txt_web_banner2_11 = "배너 게시"; // Banner Display
$txt_web_banner2_12 = "방문자 수"; // No. of Visitors
$txt_web_banner2_13 = "등록일"; // Date of Posting
$txt_web_banner2_14 = "최근 수정일"; // Last Update


// website > stuff
$txt_web_stuff_01 = "콘테츠 위치별 종류 선택"; // Select Location
$txt_web_stuff_loco_01 = "환영인사 [첫화면]"; // Welcome Comment [Intro Page]
$txt_web_stuff_loco_02 = "연락처 [좌측]"; // Contact Info [Left]
$txt_web_stuff_loco_03 = "회원 가입 안내"; // Guide to Sign-up
$txt_web_stuff_loco_04 = "이용자 약관"; // Terms & Regulations
$txt_web_stuff_loco_05 = "공지 사항 [팝업창]"; // Reminder [Pop-up Page]
$txt_web_stuff_loco_06 = "하단 박스"; // Foot Box
$txt_web_stuff_loco_07 = "하단 박스 작은 칸"; // Foot Box Small Column
$txt_web_stuff_loco_08 = "하단 저작권 표시"; // Copyrights
$txt_web_stuff_loco_09 = "자동응답메일 - 회원 가입"; // Auto Response - Sign-up
$txt_web_stuff_loco_10 = "자동응답메일 - 비밀번호 찾기"; // Auto Response - Find Password
$txt_web_stuff_loco_11 = "자동응답메일 - 인보이스 발행"; // Auto Response - Invoice
$txt_web_stuff_loco_12 = "뉴스 레터 - 하단 주소표시 줄"; // News Letter - Footer
$txt_web_stuff_loco_13 = "쇼핑몰 - 과금 안내"; // Shop - Billing Information
$txt_web_stuff_loco_14 = "쇼핑몰 - 배송 안내"; // Shop - Shipping


// website > mailing
$txt_web_mailing_01 = "수신 동의"; // Agree
$txt_web_mailing_01_yes = "동의"; // Yes
$txt_web_mailing_01_no = "거절"; // No
$txt_web_mailing_02 = "리스트-업"; // List-up
$txt_web_mailing_021 = "해제하기"; // Remove
$txt_web_mailing_022 = "+ 등록"; // + Add
$txt_web_mailing_03 = "선택한 메일 수"; // Selected
$txt_web_mailing_04 = "모두 등록하기"; // Add All
$txt_web_mailing_05 = "모두 해제하기"; // Remove All
$txt_web_mailing_06 = "뉴스 레터를 선택하세요"; // Select News Letter
$txt_web_mailing_07 = "메일링 리스트에 등록하기"; //  Add to Mailing List
$txt_web_mailing_08 = "발송일"; // Sent Date
$txt_web_mailing_08s = "발송일"; // Sent
$txt_web_mailing_09 = "발송수"; // Count
$txt_web_mailing_10 = "발송하기"; // Mailer
$txt_web_mailing_11 = "재발송"; // Re-send
$txt_web_mailing_12 = "+ 발송"; // + Send
$txt_web_mailing_13 = "작성일"; // Composed

$txt_web_mailing_chk_01 = "입력하신 이메일은 이미 메일링 리스트에 있습니다."; // Your submission of Email already exists in the mailing list.


// website > news letter
$txt_web_nletter_01 = "뉴스 레터 리스트";
$txt_web_nletter_02 = "뉴스 레터 등록하기";
$txt_web_nletter_03 = "뉴스 레터 수정하기";
$txt_web_nletter_04 = "뉴스 레터 삭제하기";
$txt_web_nletter_05 = "뉴스 레터 작성하기"; // Compose News Letter
$txt_web_nletter_06 = "발송 번호"; // Issue No.
$txt_web_nletter_07 = "하단 주소표시 부분"; // Footer
$txt_web_nletter_08 = "수신자 수"; // No. of Recipients
$txt_web_nletter_09 = "편집창"; // Compose
$txt_web_nletter_10 = "미리보기"; // Preview
$txt_web_nletter_11 = "뉴스 레터 발송하기"; // Send News Letter
$txt_web_nletter_12 = "수신자"; // Recipients
$txt_web_nletter_121 = "메일링 리스트에 등록된 전체 수신자"; // All the Mailing List
$txt_web_nletter_122 = "메일링 리스트에서 선택한 수신자"; // All your selections from Mailing List
$txt_web_nletter_123 = "메일링 리스트에서 검색한 수신자"; // All the List filtered from Mailing List


// website > layout
$txt_web_layout_01 = "홈페이지 레이아웃 저장하기"; // Save Website Layout
$txt_web_layout_02 = "홈페이지 레이아웃 테이블 생성하기"; // Create Website Layout Table




// BBS

	// 인사말
	$bbstxt_01 = "Introduction1";
	$bbstxt_02 = "Introduction2";


	// My Members
	$mbdtxt_01 = "회원 리스트";
	$mbdtxt_02 = "성별";
	$mbdtxt_03 = "지역";
	$mbdtxt_04 = "쪽지보내기";
	$mbdtxt_05 = "등록여부";
	$mbdtxt_06 = "등록";
	$mbdtxt_07 = "남";
	$mbdtxt_08 = "여";
	$mbdtxt_09 = "등록됨";
	$mbdtxt_10 = "미등록";
	$mbdtxt_11 = "주소록";

	// Bulletin
	$bdtxt_01 = "번호";
	$bdtxt_02 = "제목";
	$bdtxt_03 = "글쓴이";
	$bdtxt_04 = "날짜";
	$bdtxt_05 = "조회수";
	$bdtxt_06 = "체크";
	$bdtxt_07 = "이름";
	$bdtxt_08 = "내용";
	$bdtxt_09 = "새 글 쓰 기";
	$bdtxt_10 = "홈페이지";
	$bdtxt_11 = "비밀번호";
	$bdtxt_12 = "(비밀번호 4자리이상)";
	$bdtxt_13 = "답 변 하 기";
	$bdtxt_14 = "수 정 하 기";
	$bdtxt_151 = "삭 제 하 기";

	// PDS
	$bdtxt_15 = "파일";
	$bdtxt_16 = "자료 소개";
	$bdtxt_17 = "등록 파일";
	$bdtxt_18 = "님의 글";
	$bdtxt_19 = "댓글";
	$bdtxt_20 = "표정 달기";
	$bdtxt_21 = "자료에 대한 한마디 !";
	$bdtxt_22 = "파 일 삭 제";
	$bdtxt_23 = "등록할 파일";

	$bdtxt_24 = "아이피";

	$bdtxt_31 = "컨텐츠 정렬";
	$bdtxt_32 = "등록순";
	$bdtxt_33 = "등록역순";
	$bdtxt_34 = "이미지 삽입";
	$bdtxt_35 = "이미지 없음";
	$bdtxt_36 = "GIF";
	$bdtxt_37 = "JPG";
	$bdtxt_38 = "SWF(플래쉬)";
	$bdtxt_39 = "이미지 정렬";
	$bdtxt_40 = "텍스트 위";
	$bdtxt_41 = "텍스트 아래";
	$bdtxt_42 = "텍스트와 같은 위치";
	$bdtxt_43 = "좌측 정렬";
	$bdtxt_44 = "중앙 정렬";
	$bdtxt_45 = "우측 정렬";

	$bdtxt_51 = "이미지 장평";
	$bdtxt_52 = "가로를 크게";
	$bdtxt_53 = "세로를 크게";
	$bdtxt_54 = "가로와 세로 똑같이";

	$bdtxt_91 = "인증코드";
	$bdtxt_92 = "로봇에 의한 자동글쓰기 방지용 코드로 아래 글자를 입력하세요.";
	$bdtxt_93 = "검 색";
	$bdtxt_94 = "비밀글입니다.";
	$bdtxt_95 = "비밀댓글";
	$bdtxt_96 = "댓글쓰기";
	$bdtxt_97 = "비밀댓글입니다.";
	$bdtxt_98 = "댓글을 입력하셔야 합니다.";
	$bdtxt_99 = "글자수는 한글 100자, 영문 200자로 제한됩니다.";
	$bdtxt_901 = "My Library에 저장하였습니다.";
	$bdtxt_902 = "이미 My Library에 저장하셨습니다.";
	$bdtxt_903 = "닉네임";
	$bdtxt_904 = "매매";
	$bdtxt_905 = "임대";
	$bdtxt_906 = "재임대";
	$bdtxt_907 = "부제목";
	$bdtxt_908 = "줄바꿔 쓰기";
	$bdtxt_909 = "비밀글";
	$bdtxt_910 = "광고 신청";
	$bdtxt_911 = "박스광고";
	$bdtxt_912 = "줄광고";
	$bdtxt_913 = "신청 않음";
	$bdtxt_914 = "첨부파일 변경";
	$bdtxt_915 = "광고 해제";
	
	
	// 방명록
	$buktxt_01 = "방 명 록";
	$buktxt_02 = "현재 방명록에는 글이 하나도 없습니다.";
	$buktxt_03 = "수정";
	$buktxt_04 = "삭제";
	$buktxt_05 = "방문 소감";
	$buktxt_06 = "광고 신청";
	$buktxt_07 = "";
	$buktxt_08 = "";
	$buktxt_09 = "";
	$buktxt_10 = "";

	// Trade
	$trdtxt_01 = "제목";
	$trdtxt_02 = "아이템";
	$trdtxt_03 = "간략 소개";
	$trdtxt_04 = "상세 소개";
	$trdtxt_05 = "조건";
	$trdtxt_06 = "연락 정보";
	$trdtxt_07 = "작은 사진";
	$trdtxt_08 = "확대 사진";
	$trdtxt_09 = "이미지 없음";
	$trdtxt_10 = "첨부 자료";
	$trdtxt_11 = "첨부 자료 없음";
	$trdtxt_12 = "파일 크기";
	$trdtxt_13 = "한글 50자까지 허용";
	$trdtxt_14 = "픽셀";
	$trdtxt_15 = "이미지 변경";
	$trdtxt_16 = "첨부자료 변경";
	$trdtxt_17 = "자료 첨부";
	$trdtxt_18 = "간략한 제안 및 제품 소개를 입력하세요.";
	$trdtxt_19 = "";
	$trdtxt_20 = "";
	
	// 북마크
	$bmktxt_01 = "웹사이트명";
	$bmktxt_02 = "웹사이트 주소";
	$bmktxt_03 = "북마크";
	$bmktxt_04 = "표시할 웹사이트명을 입력하세요.";
	$bmktxt_05 = "웹사이트 주소를 입력하세요.";

  // 폼메일
  $fmltxt_01 = "보내기";
  $fmltxt_02 = "재작성";
  $fmltxt_03 = "메시지가 성공적으로 발송되었습니다.";
  $fmltxt_04 = "이름을 입력하세요.";
  $fmltxt_05 = "Email 주소를 입력하세요.";
  $fmltxt_06 = "제목을 입력하세요.";
  $fmltxt_07 = "내용을 입력하세요.";
  $fmltxt_08 = "온라인 주문서";
  $fmltxt_09 = "제품명";
  $fmltxt_10 = "";
  
  $fmltxt_21 = "이메일 형식이 틀립니다.";
  $fmltxt_22 = "비밀번호를 입력하세요.";
  $fmltxt_23 = "인증번호를 입력하세요.";
  $fmltxt_24 = "등 록";
  $fmltxt_25 = "재입력";
  $fmltxt_26 = "수 정";
  $fmltxt_27 = "삭 제";
  $fmltxt_28 = "취 소";
  $fmltxt_29 = "";

	// 마켓플레이스/구인구직 등
	$bmrtxt_01 = "구분";
	$bmrtxt_11 = "팝니다";
	$bmrtxt_12 = "삽니다";
	$bmrtxt_21 = "구인";
	$bmrtxt_22 = "구직";
?>

