<?
// Front Desk Menu
$frn1_mmenu_01 = "Barcode";
$frn1_mmenu_02 = "Periksa";
$frn1_mmenu_03 = "Koreksi";
$frn1_mmenu_04 = "Rekapitulasi harian";
$frn1_mmenu_05 = "Print";

$frn1_mmenu_06 = "Bahasa"; // 언 어
$frn1_mmenu_06_en = "English"; // 영 어
$frn1_mmenu_06_ko = "Korean"; // 한국어
$frn1_mmenu_06_in = "Indonesian"; // 인도네시아어
$frn1_mmenu_07 = "Tidak punya akun?"; // 사용자 계정이 없나요?
$frn1_mmenu_08 = "Login"; // 로그인
$frn1_mmenu_08b = "Sign In"; // 로그인
$frn1_mmenu_09 = "Login Anggota"; // 회원 로그인
$frn1_mmenu_10 = "Please provide your details."; // 사용자 정보를 입력하세요.
$frn1_mmenu_11 = "Company ID"; // 회사 ID
$frn1_mmenu_12 = "User ID"; // 사용자 ID
$frn1_mmenu_12e = "User ID atau Email"; // 사용자 ID 또는 Email
$frn1_mmenu_13 = "Password"; // 비밀번호
$frn1_mmenu_14 = "Keep me signed in"; // 로그인 상태 유지
$frn1_mmenu_15 = "Daftar untuk Akun gratis"; // 무료 계정 가입하기
$frn1_mmenu_16 = "Login to Trial Version"; // 데모 버전 로그인
$frn1_mmenu_17 = "Membuat akun anda dengan gratis:"; // 무료 계정을 발급받으세요:
$frn1_mmenu_18 = "Nama Perusahaan"; // 회사 이름
$frn1_mmenu_19 = "Nama Anda"; // 이름
$frn1_mmenu_20 = "Nomor Telpon"; // 전화번호
$frn1_mmenu_21 = "Agree with the Terms & Conditions."; // 사용자 약관에 동의합니다.
$frn1_mmenu_22 = "Daftar"; // 등록하기
$frn1_mmenu_23 = "Sudah punya akun?"; // 이미 계정이 있나요?
$frn1_mmenu_24 = "Login to your account"; // 사용자 로그인
$frn1_mmenu_25 = "Dashboard"; // 대쉬보드
$frn1_mmenu_26 = "Back to Homepage"; // 홈페이지로 가기


// Church Community Name
$ch_comm_dir1 = "Parish"; // 교 구
$ch_comm_dir11 = "Parish Priest"; // 담당 교역자
$ch_comm_dir2 = "Rigion"; // 지 역
$ch_comm_dir20 = "Rigion"; // 지역
$ch_comm_dir21 = "Head of Rigion"; // 지역장
$ch_comm_cug2 = "New Family"; // 새가족반


// Menu
$hmm_name_01 = "Beranda";
$hmm_name_02 = "Penjualan"; // 판매 관리
  $hsm_name_02_01 = "Daftar Penjualan"; // 판매 입력
  $hsm_name_02_02 = "Purchase Request"; // 주문 관리 *feelbuy Ordersheet
  $hsm_name_02_02a = "Product Search"; // 상품 검색
  $hsm_name_02_02b = "Request Approval"; // 주문 승인 및 화물 인도
  $hsm_name_02_021 = "Terima Produk"; // 상품 수령
  $hsm_name_02_022 = "Stok Opname"; // 재고 실사
  $hsm_name_02_03 = "Pengiriman"; // 배송 관리
  $hsm_name_02_04 = "Manajemen Tagihan"; // 대금 청구 관리
  $hsm_name_02_041 = "Payment Collection"; // 수금 관리
  $hsm_name_02_05 = "Invoice"; // 인보이스 관리
  $hsm_name_02_09 = "Produk"; // 상품 관리
  $hsm_name_02_POS = "Point of Sales [POS]"; // 판매 관리

$hmm_name_03 = "";

$hmm_name_03ch = "Anggota"; // 교적 관리
  $hsm_name_03ch_01 = "Clergymen"; // 교역자 정보
  $hsm_name_03ch_02 = "Peribadi"; // 개인 정보
  $hsm_name_03ch_03 = "Kepala Keluarga"; // 세대 정보
  $hsm_name_03ch_04 = "$ch_comm_dir20";
  $hsm_name_03ch_05 = "$ch_comm_cug1";
  $hsm_name_03ch_06 = "$ch_comm_cug10"." Attendances";
  $hsm_name_03ch_06t = "Attandances"; // 출결 관리

$hmm_name_04 = "Inventaris"; // 구매/재고 관리 -- 상품 관리 현황
  $hsm_name_04_01 = "Stok Masuk"; // 구매/입고 관리 -- 상품 등록/수정
  $hsm_name_04_02 = "Stok Keluar"; // 출고 관리
  $hsm_name_04_023 = "Manajemen Tagihan"; // 대금 청구 관리
  $hsm_name_04_03 = "Konfirmasi Inventaris"; // 재고 수정/마감 관리
  $hsm_name_04_03_2 = "Kembali"; // 재고 반품 관리
  $hsm_name_04_04 = "Pembayaran"; // 상품구매 지불결제 관리
  $hsm_name_04_041 = "Cek Pembayaran"; // 지불결제 확인
  $hsm_name_04_05 = "Konfirmasi Pembayaran"; // 구매 지불마감 관리
  $hsm_name_04_06 = "Pesanan Pembelian"; // 상품구매 주문 관리
  $hsm_name_04_061 = "Product Search"; // 구매 상품 검색
  $hsm_name_04_062 = "Purchase Approval"; // 구매 주문 승인 및 발송
  $hsm_name_04_07 = "Physical Check"; // 상품 수령 확인
  $hsm_name_04_071 = "Warehousing"; // 입고
  $hsm_name_04_072 = "Warehousing Check"; // 입고 확인
  $hsm_name_04_08 = "Invoice"; // 인보이스
  $hsm_name_04_21 = "Pilihan Produk"; // 상품 옵션 항목 관리
  $hsm_name_04_22 = "Unit Produk"; // 상품 단위 관리

$hmm_name_041 = "Logistics"; // 물류 관리
  $hsm_name_041_01 = "Cek Sujat Jalan"; // 화물 인도 지시서 확인
  $hsm_name_041_02 = "Logistics Progress"; // 화물 인도 관리

$hmm_name_05 = "Keuangan"; // 재무/회계 관리
  $hsm_name_05_01 = "Manajemen Biaya"; // 비용 관리
  $hsm_name_05_01_2 = "Biaya Pembelian"; // 구매 비용 관리
  $hsm_name_05_02 = "Manajemen Pendapatan"; // 수익 관리
  $hsm_name_05_02_2 = "Pendapatan Penjualan"; // "판매 수익 관리
  
  $hsm_name_05ch_02_2 = "Offering Income"; // 헌금 계수 관리
  $hsm_name_05ch_offering = "Offering Data Entry"; // 헌금 계수
  
  $hsm_name_05_03 = "Neraca"; // 상세 수익/비용 분석
  $hsm_name_05_04 = "Budget & Biaya"; // 예산 사용 현황

$hmm_name_06 = "Pelanggan"; // 고객 관리
  $hsm_name_06_01 = "Pelanggan"; // 고객 관리
  $hsm_name_06_011 = "Reseller (Toko)"; // 리셀러 (상점)
  $hsm_name_06_012 = "Reseller (Individual)"; // 리셀러 (개인)
  $hsm_name_06_013 = "Perusahaan"; // 일반 고객 (기업)
  $hsm_name_06_014 = "Individual"; // 일반 고객 (개인)
  $hsm_name_06_02 = "Distributor"; // 대리점
  $hsm_name_06_021 = "Distributor"; // 대리점 (지역총판)
  $hsm_name_06_022 = "Sub-distributor"; // 대리점 (지역지점)
  $hsm_name_06_03 = "Mailing List"; // 메일링 리스트
  $hsm_name_06_04 = "News Letter"; // 뉴스 레터

$hmm_name_07 = "HR"; // 인력 관리
  $hsm_name_07_01 = "Karyawan"; // 사원 관리

$hmm_name_08 = "Website"; // 홈페이지 관리
  $hsm_name_08_01 = "Menu Editor"; // 메뉴 관리
  $hsm_name_08_02 = "Contents Editor"; // 콘텐츠 편집
  $hsm_name_08_03 = "Banner Manager"; // 배너 관리
  $hsm_name_08_031 = "Banner Files"; // 배너 파일 관리
  $hsm_name_08_032 = "Banner Display"; // 배너 게시 관리
  $hsm_name_08_04 = "Page Stuff"; // 기타 페이지 편집
  $hsm_name_08_05 = "Mailing List"; // 메일링 리스트
  $hsm_name_08_05A = "Mailing List (Member)"; // 메일링 리스트 A (회원)
  $hsm_name_08_05B = "Mailing List (Non-member)"; // 메일링 리스트 B (비회원)
  $hsm_name_08_06 = "News Letter"; // 뉴스 레터
  $hsm_name_08_09 = "Website Layout"; // 홈페이지 레이아웃
  $hsm_name_08_10 = "Online Shop Layout"; // 쇼핑몰 레이아웃
  
$hmm_name_09 = "System Settings"; // 시스템 관리
  $hsm_name_09_01 = "Sistem"; // 창고 관리
  $hsm_name_09_02 = "Pengelola Sistem"; // 창고 Manager 관리
  $hsm_name_09_031 = "Toko"; // 매장 관리
  $hsm_name_09_032 = "Pengelola Toko"; // 매장 Manager 관리
  $hsm_name_09_03C = "Currency"; // Currency
  $hsm_name_09_04 = "Penyedia"; // 공급자 관리
  $hsm_name_09_05 = "Kategori Produk"; // 상품 카테고리 관리
  $hsm_name_09_06 = "Pengaturan Jarak Tempuh"; // 마일리지
  $hsm_name_09_07 = "Tarif Diskon"; // 리셀러 할인율
  $hsm_name_09_08 = "Voucher"; // 바우처 발행관리
  $hsm_name_09_09 = "Diskon Spesial"; // 특별 행사가
  $hsm_name_09_081 = "YARNEN"; // YARNEN 관리
  $hsm_name_09_10 = "Kas Awal"; // 현금시제 초기값
  $hsm_name_09_11 = "Akun Bank"; // 결제은행 계좌관리
  $hsm_name_09_12 = "Penggantian Kartu"; // 신용카드 결제기 관리
  $hsm_name_09_13 = "Kode Akuntansi"; // 계정항목 관리
  $hsm_name_09_132 = "Biaya"; // 부서별 지출항목
  $hsm_name_09_133 = "Budget"; // 부서별 예산
  $hsm_name_09_14 = "Bank Loans"; // 은행대출
  $hsm_name_09_20 = "Foreign Exchange"; // 환율 관리
  $hsm_name_09_15 = "Daerah"; // 지역 관리
  $hsm_name_09_17 = "Gudang"; // 창고 관리
  $hsm_name_09_18 = "Grup Konsinyasi"; // 위탁판매 그룹 관리
  $hsm_name_09_21 = "Penggabungan Klien DB"; // 연동 Client DB 계정
  $hsm_name_09_22 = "Perusahaan"; // 회사 계정
  $hsm_name_09_23 = "Loan Providers"; // 펀드 제공은행
  $hsm_name_09_34 = "Training/Activity"; // 훈련/활동 과정 관리
  $hsm_name_09_341 = "Training Category"; // 훈련/활동 카테고리
  $hsm_name_09_342 = "Training Course"; // 훈련/활동 과정
  $hsm_name_09_41 = "Job Class"; // 직급 코드
  $hsm_name_09_42 = "Salary Class"; // 호봉
  $hsm_name_09_43 = "Garis Dasar Gaji Tahunan"; // 연간 임금기준표
  
  $hsm_name_09ch_31 = "Group Category"; // 그룹 카테고리
  $hsm_name_09ch_311 = "Districts"; // 교구와 지역 구분
  $hsm_name_09ch_312 = "Departments"; // 부 서
  $hsm_name_09ch_313 = "Missionaries"; // 선교회
  $hsm_name_09ch_32 = "$ch_comm_cug1";
  $hsm_name_09ch_33 = "Avocation"; // 직위 및 직분
  $hsm_name_09ch_331 = "Position"; // 직 위
  $hsm_name_09ch_332 = "Post"; // 직 분
  $hsm_name_09ch_333 = "Occupation"; // 직 업
  $hsm_name_09ch_34 = "Training/Activity"; // 훈련/활동 과정 관리
  $hsm_name_09ch_341 = "Training Category"; // 훈련/활동 카테고리
  $hsm_name_09ch_342 = "Training Course"; // 훈련/활동 과정

$hmm_name_10 = "Pengaturan"; // user // 환경 설정
  $hsm_name_10_01 = "Bahasa"; // 언어선택
  $hsm_name_10_02 = "Profil"; // 계정정보 변경
  $hsm_name_10_03 = "Ubah Kata Sandi anda"; // 비밀번호 변경
  $hsm_name_10_04 = "Daftar"; // 사용자 등록
  $hsm_name_10_05 = "Log In"; // 로그인
  $hsm_name_10_06 = "Log Out"; // 로그아웃


// 입출력 폼 - 공통
$txt_comm_frm01 = "Submit"; // 입 력
$txt_comm_frm01s = "Enter"; // 입력
$txt_comm_frm02 = "Submit"; // 확 인
$txt_comm_frm03 = "Kirim"; // 등 록
$txt_comm_frm04 = "Ubah"; // 변 경
$txt_comm_frm05 = "Perbarui"; // 수정하기
$txt_comm_frm051 = "Submit"; // 추가하기
$txt_comm_frm051s = "Add"; // 추 가
$txt_comm_frm052 = "Delete"; // 삭제하기
$txt_comm_frm06 = "Batal"; // 취 소
$txt_comm_frm07 = "Reset"; // 재입력
$txt_comm_frm08 = "Hapus"; // 삭 제
$txt_comm_frm09 = "Balas"; // 답 변
$txt_comm_frm10 = "Cetak"; // 출 력
$txt_comm_frm11 = "Cetak"; // 인 쇄
$txt_comm_frm12 = "Upd"; // 수정
$txt_comm_frm13 = "Del"; // 삭제
$txt_comm_frm14 = "Dipesan Oleh"; // 정렬 순서
$txt_comm_frm15 = "Lihat Semua"; // 전체 보기
$txt_comm_frm16 = "Data Update"; // 자료 업데이트
$txt_comm_frm17 = "Perbarui"; // 업데이트
$txt_comm_frm18 = "Selanjutnya"; // 다 음
$txt_comm_frm19 = "Pilih"; // 선 택
$txt_comm_frm20 = "Semua Sistem"; // 전체 System
$txt_comm_frm21 = "Kode PIN"; // 인증번호
$txt_comm_frm22 = "Masukkan kode PIN:"; // 다음 번호를 입력하세요:
$txt_comm_frm23 = "Perusahaan"; // 회사 코드
$txt_comm_frm24 = "Pilih Sistem"; // System 선택
$txt_comm_frm25 = "Lihat Semua Perusahaan"; // 전체 회사 보기
$txt_comm_frm26 = "Cari"; // 검 색
$txt_comm_frm27 = "Simpan"; // 저장하기
$txt_comm_frm28 = "Submit"; // 처리하기
$txt_comm_frm29 = "Produk Update"; // 상품 업데이트
$txt_comm_frm30 = "Semua Perusahaan"; // 전체 회사
$txt_comm_frm31 = "Semua Toko"; // 전체 Shop
$txt_comm_frm32 = "Pilih Perusahaan"; // 회사 선택
$txt_comm_frm33 = "Membuat Table"; // 테이블 생성
$txt_comm_frm331 = "Please click the button below to create Table here."; // 아래 버튼을 클릭하세요.
$txt_comm_frm34 = "Tanggal"; // 날짜

$txt_comm_lang_en = "Bahasa Inggris"; // 영 어
$txt_comm_lang_in = "Bahasa Indonesia"; // 인도네시아어
$txt_comm_lang_ko = "Korean"; // 한 글

$txt_comm_month_01 = "Januari"; // 1월
$txt_comm_month_02 = "Februari"; // 2월
$txt_comm_month_03 = "Maret"; // 3월
$txt_comm_month_04 = "April"; // 4월
$txt_comm_month_05 = "Mei"; // 5월
$txt_comm_month_06 = "Juni"; // 6월
$txt_comm_month_07 = "Juli"; // 7월
$txt_comm_month_08 = "Agustus"; // 8월
$txt_comm_month_09 = "September"; // 9월
$txt_comm_month_10 = "Oktober"; // 10월
$txt_comm_month_11 = "November"; // 11월
$txt_comm_month_12 = "Desember"; // 12월

$txt_comm_report_01 = "Laporn Harian"; // 일일 보고
$txt_comm_report_02 = "Laporan Mingguan"; // 주간 보고
$txt_comm_report_03 = "Laporan Berkala"; // 기간별 보고
$txt_comm_report_04 = "Laporan Bulanan"; // 월간 보고
$txt_comm_report_05 = "Laporan Tri Wulan"; // 분기 보고
$txt_comm_report_06 = "Laporan Tahunan"; // 연간 보고
$txt_comm_report_21 = "Proyeksi Penjualan"; // 판매 현황 보고
$txt_comm_report_41 = "Proyeksi Inventaris"; // 재고 현황 보고
$txt_comm_report_51 = "Proyeksi Financial"; // 재무 현황 보고
$txt_comm_report_71 = "Periode"; // 검색 기간
$txt_comm_report_81 = "Harian"; // 일일
$txt_comm_report_82 = "Mingguan"; // 주간
$txt_comm_report_83 = "Bulanan"; // 월간
$txt_comm_report_84 = "Tri Wulan"; // 분기
$txt_comm_report_85 = "Tahunan"; // 연간


// sales > order, sales
$txt_sales_sales_01 = "Stok"; // 재 고
$txt_sales_sales_02 = "Gerbang"; // 입고지
$txt_sales_sales_03 = "Jual"; // 판 매
$txt_sales_sales_04 = "Tambahkan ke dalam keranjang"; // 장바구니에 담기
$txt_sales_sales_05 = "Keranjang Belanja"; // 장바구니
$txt_sales_sales_06 = "Bayar Sekarang"; // 결 제 하 기
$txt_sales_sales_07 = "Berbelanja"; // 다른 상품 검색
$txt_sales_sales_08 = "Terjual"; // 매 진
$txt_sales_sales_09 = "Harga Satuan"; // 단 가
$txt_sales_sales_10 = "Total"; // 합 계
$txt_sales_sales_11 = "Jumlah Total"; // 총 주문 합계
$txt_sales_sales_12 = "Kasir"; // 계산하기
$txt_sales_sales_13 = "Nama Pelanggan"; // 고객 이름
$txt_sales_sales_14 = "JenPel"; // 고객 분류 Jenis Pelanggan
$txt_sales_sales_14_1 = "Anggota"; // 회 원
$txt_sales_sales_14_2 = "Bukan Anggota"; // 비회원
$txt_sales_sales_15 = "Jenis Produk"; // 상품 유형
$txt_sales_sales_16 = "Jumlah Total"; // 총 판매액
$txt_sales_sales_17 = "Tanggal Jatuh Tempo"; // 수불 기일
$txt_sales_sales_18 = "Model biaya"; // 모델 Fee
$txt_sales_sales_19 = "Catatan"; // 메 모
$txt_sales_sales_20 = "Faktur Terbitan"; // 인보이스 발행
$txt_sales_sales_21 = "Daftar Faktur"; // 인보이스 리스트
$txt_sales_sales_22 = "Cetak Faktur"; // 인보이스 인쇄
$txt_sales_sales_23 = "Dengan Voucher"; // 바우처 결제
$txt_sales_sales_24 = "Potongan Spesial"; // 특별 행사가
$txt_sales_sales_25 = "Termasuk VAT"; // 부가세 포함
$txt_sales_sales_26 = "VAT"; // 부가세
$txt_sales_sales_27 = "Tanggal Pemesanan"; // 주문일
$txt_sales_sales_30 = "Bukan Anggota"; // 비회원
$txt_sales_sales_31 = "Anggota Individu"; // 개인 회원
$txt_sales_sales_32 = "Anggota Perusahaan"; // 기업 회원
$txt_sales_sales_40 = "Pesan"; // 주문하기
$txt_sales_sales_41 = "Pesan sekarang"; // 지금 주문하기
$txt_sales_sales_42 = "No. Pemesanan"; // 주문번호
$txt_sales_sales_43 = "Konfirmasi/Batal Pemesanan"; // 주문 확인/취소
$txt_sales_sales_44 = "Collected"; // 수금 완료

$txt_sales_sales_chk01 = "Pilihan Anda ada dalam Keranjang Belanja."; // 이미 선택하신 상품입니다.
$txt_sales_sales_chk02 = "Silahkan Pilih Nama Pelanggan."; // 고객 이름을 선택하세요.
$txt_sales_sales_chk03 = "Silahkan Pilih Jenis Produk."; // 상품 유형을 선택하세요.
$txt_sales_sales_chk04 = "Silahkan Pilih Jumlah Total."; // 총 판매액을 입력하세요.
$txt_sales_sales_chk05 = "Silahkan plih produk lain di toko yang sama."; // 동일한 Shop의 상품만 선택하실 수 있습니다.


// inventory > stock_in
$txt_invn_stockin_01 = "Inventaris"; // 품목/상품 리스트
$txt_invn_stockin_02 = "Item"; // 품 목
$txt_invn_stockin_03 = "Produk"; // 상 품
$txt_invn_stockin_04 = "Kategori"; // 카테고리
$txt_invn_stockin_05 = "Nama Produk"; // 상품명
$txt_invn_stockin_06 = "Kode Produk"; // 상품 코드
$txt_invn_stockin_051 = "Item/Merek"; // 품목명(브랜드)
$txt_invn_stockin_061 = "Kode Item"; // 품목 코드
$txt_invn_stockin_07 = "Harga Perolehan"; // 매입단가
$txt_invn_stockin_07s = "Perolehan"; // 매입단가
$txt_invn_stockin_08 = "Harga Perolehan"; // 입고단가
$txt_invn_stockin_09 = "Harga Asal"; // 원 가
$txt_invn_stockin_10 = "Harga Pasar"; // 시장가 [Kios Price]
$txt_invn_stockin_11 = "Harga Tag"; // 정 가 [Kios Price]
$txt_invn_stockin_12 = "Harga Jual"; // 판매가
$txt_invn_stockin_13 = "Harga D/C"; // 할인가
$txt_invn_stockin_13i = "Harga Faktur"; // 인보이스 금액
$txt_invn_stockin_14 = "Batas"; // 이 익
$txt_invn_stockin_15 = "Batas"; // 마 진
$txt_invn_stockin_16 = "Batas Unit"; // 개당이익
$txt_invn_stockin_17 = "Kuantiti"; // 수 량
$txt_invn_stockin_18 = "Tgl. Msk"; // 입고일
$txt_invn_stockin_18s= "Tgl. Input Harga";
$txt_invn_stockin_19 = "Tambah Item"; // 품목 추가
$txt_invn_stockin_20 = "Tambah Produk"; // 상품 추가
$txt_invn_stockin_21 = "Pilih Kategori"; // 카테고리 선택
$txt_invn_stockin_22 = "Tambah"; // 추가
$txt_invn_stockin_23 = "Perbarui Produk"; // 상품정보 변경
$txt_invn_stockin_24 = "Perbarui Item"; // 품목정보 수정
$txt_invn_stockin_25 = "Harga Total"; // 총매입액
$txt_invn_stockin_26 = "Harga Total"; // 총출고액
$txt_invn_stockin_27 = "Hapus Produk"; // 상품 삭제하기
$txt_invn_stockin_28 = "Warna"; // 색 상
$txt_invn_stockin_29 = "Ukuran"; // 크 기
$txt_invn_stockin_30 = "Kode Asli"; // 공급자 상품 코드
$txt_invn_stockin_31 = "Stok Masuk"; // 입고 수량
$txt_invn_stockin_32 = "Stok Keluar"; // 출고 수량
$txt_invn_stockin_32s = "Sold"; // 판매 수량
$txt_invn_stockin_33 = "Stok"; // 재고 수량
$txt_invn_stockin_34 = "Stok Expired"; // 유효기간 만료
$txt_invn_stockin_35 = "Stok Sisa"; // 남은 재고
$txt_invn_stockin_36 = "Unit"; // 단위
$txt_invn_stockin_37 = "Unit Name"; // 단위명
$txt_invn_stockin_38 = "Quantity per Unit"; // 단위당 수량
$txt_invn_stockin_40 = "Daftar Unit"; // 단위 추가하기
$txt_invn_stockin_41 = "Perbarui Unit"; // 단위 수정하기
$txt_invn_stockin_42 = "Hapus Unit"; // 단위 삭제하기
$txt_invn_stockin_43 = "Cataan"; // 개요
$txt_invn_stockin_44 = "Unit Produk"; // 상품 단위
$txt_invn_stockin_45 = "Form Pembenaran Pembilan"; // 구매 승인 요청서
$txt_invn_stockin_46 = "Masukkan Pilihan anda didalam Stok"; // 선택한 구매 항목을 입고함
$txt_invn_stockin_47 = "Pembenaran"; // 승인
$txt_invn_stockin_48 = "Approved"; // 승인됨
$txt_invn_stockin_49 = "Kirim PO"; // PO 발송
$txt_invn_stockin_50 = "Cetak PO"; // PO 인쇄
$txt_invn_stockin_60 = "Tanggal Terima"; // 수령확인일
$txt_invn_stockin_61 = "Cek Kwantitas"; // 수량 확인
$txt_invn_stockin_611 = "Pesan"; // 발주시
$txt_invn_stockin_612 = "Terima"; // 수령시
$txt_invn_stockin_613 = "Loss"; // 손실
$txt_invn_stockin_6131 = "Lost"; // 분실
$txt_invn_stockin_6132 = "Broken"; // 파손
$txt_invn_stockin_6133 = "Expired"; // 기한 만료
$txt_invn_stockin_6134 = "Defection"; // 제품 결함
$txt_invn_stockin_6135 = "Msc."; // 기타
$txt_invn_stockin_614 = "Cataan"; // 비고
$txt_invn_stockin_62 = "Sudah Cek"; // 수령 확인
$txt_invn_stockin_63 = "Cek"; // 확인
$txt_invn_stockin_64 = "Priksa Stok"; // 재고 확인
$txt_invn_stockin_65 = "Stok Sudah Diperiksa"; // 재고 확인 완료
$txt_invn_stockin_66 = "Estimated"; // 추정치

$txt_invn_stockin_chk01 = "Masukkan Kode Produk"; // 상품 코드를 입력하세요.
$txt_invn_stockin_chk02 = "Masukkan Nama Produk."; // 상품명을 입력하세요.
$txt_invn_stockin_chk03 = "Silahkan Pilih Toko di atas."; // 좌측 상단에서 Shop을 선택하세요.
$txt_invn_stockin_chk04 = "Silahkan Pilih Kategori."; // 카테고리를 선택하세요.
$txt_invn_stockin_chk05 = "Anda tidak bisa menghapus jenis barang dengan produk"; // 상품이 있는 품목은 삭제할 수 없습니다.
$txt_invn_stockin_chk06 = "Silahkan hapus produk sebelum menghapus jenis barang."; // 먼저 상품 리스트에서 삭제후 다시 품목을 삭제하십시오.
$txt_invn_stockin_chk07 = "Silahkan pilih gudang."; // 창고를 선택하세요.


// inventory > stock_out
$txt_invn_stockout_01 = "Toko"; // 출고지(매장)
$txt_invn_stockout_02 = "Simpan Toko"; // 출고지(매장) 저장
$txt_invn_stockout_03 = "Kembali"; // 반 품
$txt_invn_stockout_04 = "Tentukan Toko"; // 출 고
$txt_invn_stockout_05 = "Shop"; // 출고지
$txt_invn_stockout_06 = "Tidak Ditetapkan"; // 미 정
$txt_invn_stockout_07 = "Tetapkan"; // 지 정
$txt_invn_stockout_08 = "Batal"; // 출고 취소
$txt_invn_stockout_09 = "Konfirmasi"; // 출고 완료
$txt_invn_stockout_10 = "Partial Outlet"; // 일부 출고
$txt_invn_stockout_11 = "Partial Outlet"; // 분할 출고
$txt_invn_stockout_12 = "Outlet update"; // 출고 수정
$txt_invn_stockout_13 = "Konfirmasi Stok"; // 재고 마감
$txt_invn_stockout_14 = "Ganti Stok"; // 재고 수정
$txt_invn_stockout_15 = "Stok Asli"; // 변경전 재고
$txt_invn_stockout_16 = "Proses"; // 처리 구분
$txt_invn_stockout_17 = "Konfirmasi Stok"; // 재고 수정 및 마감
$txt_invn_stockout_18 = "Konfirmasi Pembatalan"; // 재고 마감 취소
$txt_invn_stockout_19 = "Perbarui Inventory"; // 재고 변동 관리
$txt_invn_stockout_20 = "Daftar Pembayaran Kembali"; // 반품 리스트
$txt_invn_stockout_21 = "Ganti Toko"; // 출고지(Shop) 변경
$txt_invn_stockout_22 = "Tambah Stok"; // 재고 추가
$txt_invn_stockout_23 = "Buat Kode Baru"; // 신규 상품 생성
$txt_invn_stockout_24 = "Tanggal Update"; // 재고 변동일
$txt_invn_stockout_24s = "Tgl. Input Produk";
$txt_invn_stockout_25 = "Tidak Ditetapkan"; // 미출고
$txt_invn_stockout_26 = "Toko"; // 출고
$txt_invn_stockout_27 = "Outlet Baru"; // 추가 출고
$txt_invn_stockout_28 = "Pilih Toko"; // 출고지(매장) 선택
$txt_invn_stockout_29 = "Silahkan pilih Toko."; // 매장을 선택하세요.

$txt_invn_stockout_30 = "Cek Delivery"; // 화물 인도 지시 검토 *feelbuy Delivery Check
$txt_invn_stockout_31 = "Surat Jalan"; // 화물 인도 지시서 *feelbuy Delivery Order
$txt_invn_stockout_32 = "Surat Jalan"; // 화물 인도 지시서 양식 *feelbuy Delivery Order Form
$txt_invn_stockout_33 = "Bikin Surat Jalan"; // 선택한 품목에 대하여 화물 인도 지시를 합니다 *feelbuy Make a Delivery Order of your selection
$txt_invn_stockout_34 = "PIC of Delivery"; // 화물 인도 담당자
$txt_invn_stockout_35 = "Order Details"; // 상세 지시서
$txt_invn_stockout_36 = "Ordered"; // 인도 지시일
$txt_invn_stockout_361 = "Sent"; // DO 발송일
$txt_invn_stockout_37 = "Checked"; // 인도 지시 확인일
$txt_invn_stockout_38 = "Done"; // 인도 완료일
$txt_invn_stockout_39 = "Process"; // 처리 상태
$txt_invn_stockout_390 = "Undelivered"; // 미인도
$txt_invn_stockout_391 = "Order Checked"; // 인도 지시중
$txt_invn_stockout_392 = "In Process"; // 인도 처리중
$txt_invn_stockout_393 = "Sudah Terima"; // 인도 완료
$txt_invn_stockout_39x = "Cancel"; // 인도 취소
$txt_invn_stockout_40 = "Recipient"; // 수령자
$txt_invn_stockout_41 = "No Shop Selected"; // 매장 미지정
$txt_invn_stockout_42 = "Departure"; // 출발지
$txt_invn_stockout_421 = "Take-off"; // 출발
$txt_invn_stockout_43 = "Destination"; // 도착지
$txt_invn_stockout_431 = "Arrival"; // 도착
$txt_invn_stockout_44 = "Under Way"; // 인도중
$txt_invn_stockout_45 = "Average Wait"; // 평균 소요 시간
$txt_invn_stockout_46 = "Wait"; // 소요 시간
$txt_invn_stockout_47 = "Handling Charges"; // 소요 비용

$txt_invn_stockout_chk01 = "Silahkan Pilih Toko untuk Stok Keluar."; // 출고지(매장)를 선택하세요.


// inventory > return
$txt_invn_return_01 = "Harga Total"; // 총반품액
$txt_invn_return_02 = "Tanggal Kembali"; // 반품일
$txt_invn_return_02s = "Tgl. Kmbli"; // 반품일
$txt_invn_return_03 = "Proses"; // 처 리
$txt_invn_return_04 = "Dibayar"; // 수금 완료
$txt_invn_return_05 = "Kembali"; // 반 품
$txt_invn_return_06 = "Hilang"; // 분 실
$txt_invn_return_07 = "Rusak"; // 파 손
$txt_invn_return_08 = "Lain-lain"; // 기 타
$txt_invn_return_09 = "Dalam Proses"; // 처리중
$txt_invn_return_09s = "Dl. Prs"; // 처리중
$txt_invn_return_10 = "Belum Dibayar"; // 미 수
$txt_invn_return_11 = "Submit"; // 반품 처리
$txt_invn_return_12 = "Submit"; // 수금 처리
$txt_invn_return_13 = "Tanggal Pembayaran"; // 수금일
$txt_invn_return_14 = "Mengapa"; // 반품 사유
$txt_invn_return_15 = "Konfirmasi"; // 반품 사유
$txt_invn_return_16 = "Sudah dikonfirmasi"; // 반품 사유

// inventory > payment
$txt_invn_payment_01 = "Pembayaran"; // 지불결제 리스트
$txt_invn_payment_02 = "Total"; // 총 결제액
$txt_invn_payment_03 = "Tanggal Pembayaran"; // 결제일
$txt_invn_payment_03s = "Tgl. Byr"; // 결제일
$txt_invn_payment_04 = "Batal"; // 결제 취소
$txt_invn_payment_05 = "Belum Dibayar"; // 미지불
$txt_invn_payment_05s = "Belum"; // 미지불
$txt_invn_payment_06 = "Lunas"; // 지불완료
$txt_invn_payment_07 = "Bayar pilihan Anda"; // 선택한 항목 지불결제하기
$txt_invn_payment_08 = "Pembayaran"; // 지불 처리
$txt_invn_payment_09 = "Pembayaran"; // 지불하기
$txt_invn_payment_10 = "Metode Pembayaran"; // 결제 유형
$txt_invn_payment_10s = "Metode Byr"; // 결제 유형
$txt_invn_payment_10_1 = "Cash"; // 현금
$txt_invn_payment_10_2 = "Transfer Bank"; // 은행 송금
$txt_invn_payment_10_3 = "Akun Bank"; // 계좌 이체
$txt_invn_payment_10_4 = "Kartu Kredit"; // 신용 카드
$txt_invn_payment_10_5 = "Voucher"; // 바우처
$txt_invn_payment_10_6 = "Lain-lain"; // 기 타
$txt_invn_payment_11 = "Bank"; // 결제 은행
$txt_invn_payment_12 = "Cust. Bank"; // 고객 은행
$txt_invn_payment_13 = "Remit. No."; // 송금 번호
$txt_invn_payment_14 = "Perbarui"; // 결제 정보 변경
$txt_invn_payment_15 = "Kode Pembayaran"; // 결제 코드
$txt_invn_payment_16 = "Remit. Bank"; // 송금 은행
$txt_invn_payment_17 = "Pilih Bank"; // 은행 선택
$txt_invn_payment_18 = "Kartu Kredit"; // 카드 선택
$txt_invn_payment_19 = "Submit"; // 수불 처리
$txt_invn_payment_20 = "Pilih Switching"; // 카드 결제기 선택
$txt_invn_payment_21 = "Ke Bank"; // 수신 은행 계좌
$txt_invn_payment_22 = "Dengan Uang"; // 실 결제액
$txt_invn_payment_23 = "Belum Dibayar"; // 미수금
$txt_invn_payment_24 = "Piutang Niaga"; // 미수금
$txt_invn_payment_25 = "Settlement"; // 정산
$txt_invn_payment_26 = "Settled"; // 수금
$txt_invn_payment_27 = "Collected"; // 수금
$txt_invn_payment_28 = "Kirim Uang"; // 송금


// inventory > purchase
$txt_invn_purchase_01 = "Pesanan Pembelian"; // 상품구매 주문 리스트
$txt_invn_purchase_02 = "Tempat Pesanan Pembelian"; // 상품구매 주문 작성
$txt_invn_purchase_03 = "Perbarui Pesanan Pembelian"; // 상품구매 주문 수정
$txt_invn_purchase_04 = "Hapus Pesanan Pembelian"; // 상품구매 주문 삭제
$txt_invn_purchase_05 = "Cetak Pesanan Pembelian"; // 상품구매 주문서 인쇄
$txt_invn_purchase_06 = "No. Pesanan Pembelian"; // 발주 번호
$txt_invn_purchase_06s = "No. PO"; // 발주 번호
$txt_invn_purchase_07 = "Jumlah Total"; // 발주 총액
$txt_invn_purchase_08 = "Tanggal Pemesanan"; // 발주일
$txt_invn_purchase_08s = "Tgl. Pesan"; // 발주일
$txt_invn_purchase_09 = "Pesan"; // 주문하기
$txt_invn_purchase_10 = "Baru"; // 신규 추가
$txt_invn_purchase_11 = "Submit Pesanan Pembelian"; // 상품구매 주문서 발송
$txt_invn_purchase_11pr = "Submit Resanan PR"; // PR 주문서 발송
$txt_invn_purchase_12 = "Tambah Pesanan Pembelian"; // 상품구매 주문 리스트에 추가 // Edit
$txt_invn_purchase_12pr = "Tambah Pesanan PR"; // PR 리스트에 추가
$txt_invn_purchase_13 = "Daftar Pesanan Pembelian"; // 상품구매 주문 리스트
$txt_invn_purchase_13pr = "Daftar PR"; // PR 리스트


// inventory > zone_option
$txt_invn_zonopt_01 = "Opsi Produk"; // 상품 옵션 항목 리스트
$txt_invn_zonopt_02 = "Buat Tabel"; // 테이블 생성
$txt_invn_zonopt_03 = "Opsi Nama"; // 옵션 이름
$txt_invn_zonopt_04 = "Opsi Field"; // 옵션 항목
$txt_invn_zonopt_05 = "Gunakan koma(,) sebagai pemisah."; // 콤마(,)를 구분자로 이용하세요.

$txt_invn_zonopt_chk01 = "Silahkan Buat Tabel."; // 관련 테이블을 생성하셔야 합니다.


// inventory > zone_gudang
$txt_invn_gudang_01 = "Gudang"; // 창고 리스트
$txt_invn_gudang_02 = "Tambah Gudang"; // 창고 등록하기
$txt_invn_gudang_03 = "Perbarui Gudang"; // 창고 수정하기
$txt_invn_gudang_04 = "Hapus Gudang"; // 창고 삭제하기
$txt_invn_gudang_05 = "Kode Gudang"; // 창고 코드
$txt_invn_gudang_06 = "Nama Gudang"; // 창고 이름
$txt_invn_gudang_07 = "Pengelola Gudang"; // 창고 관리자

$txt_invn_gudang_chk01 = "Silahkan Masukkan Nama Gudang."; // 창고 이름을 입력하세요.


// finance > cost
$txt_fin_cost_01 = "Permintaan untuk Pembayaran"; // 지출 결의
$txt_fin_cost_02 = "Pilih Field"; // 계정항목 선택
$txt_fin_cost_03 = "Jumlah"; // 지출 금액
$txt_fin_cost_04 = "Deskripsi"; // 지출 내역
$txt_fin_cost_05 = "Keterangan"; // 참 고
$txt_fin_cost_06 = "Tanggal"; // 날 짜
$txt_fin_cost_07 = "Kode Akun"; // 계정코드

$txt_fin_cost_chk01 = "Silahkan Pilih Field Akun Data"; // 계정항목을 선택하세요.
$txt_fin_cost_chk02 = "Silahkan Masukkan Jumlah."; // 금액을 입력하세요.
$txt_fin_cost_chk03 = "Silahkan Masukkan Defnisi Data Akun."; // 내역을 입력하세요.


// finance > income
$txt_fin_income_01 = "Ke Pendapatan"; // 수익 처리
$txt_fin_income_03 = "Jumlah"; // 수익 금액
$txt_fin_income_04 = "Deskripsi"; // 수익 내역


// finance > balance
$txt_fin_balance_01 = "Credit"; // 수 입
$txt_fin_balance_02 = "Debit"; // 지 출
$txt_fin_balance_03 = "Saldo"; // 잔 액
$txt_fin_balance_04 = "Akumulasi Total"; // 누적 합계
$txt_fin_balance_05 = "Total"; // 합 계
$txt_fin_balance_06 = "Field Data Akuntansi"; // 계정항목


// hr > member (basic)
$txt_hr_member_01 = "Karyawan"; // 사원 리스트
$txt_hr_member_02 = "Daftar Profil Karyawan"; // 사원 등록하기
$txt_hr_member_03 = "Perbarui Profil Karyawan"; // 사원 수정하기
$txt_hr_member_04 = "Hapus Profil Karyawan"; // 사원 삭제하기
$txt_hr_member_05 = "Kode Karyawan"; // 사원 코드
$txt_hr_member_06 = "ID Website"; // 웹사이트 ID
$txt_hr_member_07 = "Level Anggota"; // 사원 등급
$txt_hr_member_08 = "Perusahaan/Organisasi"; // 회사/단체명
$txt_hr_member_09 = "Sinkronisasi ke Website"; // 웹사이트 DB 연동 여부
$txt_hr_member_10 = "Tidak dihubungkan"; // 단 절
$txt_hr_member_11 = "Digandakan"; // 중 복
$txt_hr_member_12 = "Gabung"; // 통 합
$txt_hr_member_13 = "Jarak Point"; // 마일리지 포인트
$txt_hr_member_14 = "Reseller"; // 리셀러
$txt_hr_member_15 = "Non-reseller"; // 일반 사원
$txt_hr_member_16 = "Berita"; // 뉴스 레터
$txt_hr_member_17 = "Join"; // 가 입
$txt_hr_member_18 = "Batal"; // 해 제
$txt_hr_member_31 = "Nama Pangilan"; // 영문 이름
$txt_hr_member_32 = "Marital Status"; // 결혼 여부
$txt_hr_member_321 = "Single"; // 미 혼
$txt_hr_member_322 = "Married"; // 기 혼
$txt_hr_member_323 = "Divorced"; // 이 혼
$txt_hr_member_324 = "Bereaved"; // 사 별
$txt_hr_member_325 = "Remarried"; // 재 혼
$txt_hr_member_3291 = "Retirement Date"; // 퇴사일
$txt_hr_member_3292 = "Remarks"; // 비 고
$txt_hr_member_3293 = "Passed Away"; // 소 천
$txt_hr_member_3294 = "Reason of Retirement"; // 퇴직 사유

$txt_hr_member_33 = "Family Head"; // 세대주 여부
$txt_hr_member_331 = "Head"; // 세대주
$txt_hr_member_332 = "Member"; // 세대원
$txt_hr_member_333 = "Single"; // 단독 세대주
$txt_hr_member_334 = "Another Head"; // 세대 분리
$txt_hr_member_335 = "Berapa"; // 세대원수
$txt_hr_member_336 = "Orang"; // 명
$txt_hr_member_34 = "Department"; // 소 속
$txt_hr_member_341 = "Adult"; // 장년부
$txt_hr_member_342 = "Young"; // 청년부
$txt_hr_member_343 = "Collegeate"; // 대학부
$txt_hr_member_344 = "Schooler"; // 주일학교
$txt_hr_member_345 = "Unknown"; // 기 타
$txt_hr_member_346 = "Undefined"; // 미소속
$txt_hr_member_35 = "Community"; // 공동체 모임
$txt_hr_member_36 = "New Family"; // 새가족 모임
$txt_hr_member_37 = "Faith Level"; // 신 급
$txt_hr_member_371 = "Baptized"; // 세 례
$txt_hr_member_372 = "B. Suckling"; // 영아세례
$txt_hr_member_373 = "B. Infant"; // 유아세례
$txt_hr_member_374 = "Converted"; // 입 교
$txt_hr_member_375 = "B. Immersion"; // 침 례
$txt_hr_member_376 = "Learned"; // 학 습
$txt_hr_member_38 = "Date of Regis."; // 입사 등록일
$txt_hr_member_380 = "Retired"; // 퇴사
$txt_hr_member_381 = "Non-regular"; // 비정규직
$txt_hr_member_382 = "Regular"; // 정규직
$txt_hr_member_39 = "Passport No."; // 여권 번호
$txt_hr_member_40 = "Expiry Date"; // 만료여권 만료일
$txt_hr_member_41 = "Nationality"; // 국 적
$txt_hr_member_42 = "Visa"; // 비자 종류
$txt_hr_member_43 = "Spouse"; // 배우자
$txt_hr_member_44 = "Gambar"; // 사진
$txt_hr_member_45 = "Division"; // 부 서

$txt_hr_member_60 = "Laporan Mingguan"; // 순장 주간 보고서
$txt_hr_member_611 = "Hari Minggu"; // 주일 출석
$txt_hr_member_612 = "Hari Biasa"; // 순예배 출석
$txt_hr_member_621 = "Abs."; // 여부
$txt_hr_member_6211 = "Yes"; // 출석
$txt_hr_member_6212 = "No"; // 결석
$txt_hr_member_622 = "Sebab"; // 사유
$txt_hr_member_63 = "Cataan"; // 조치사항
$txt_hr_member_631 = "oleh Kepala"; // 순장 조치사항
$txt_hr_member_632 = "oleh Pendeta"; // 담당 교역자 조치사항
$txt_hr_member_64 = "Doa"; // 기도 제목
$txt_hr_member_65 = "Kirim"; // 전 송

$txt_hr_member_chk01 = "Pilih Sistem."; // 시스템을 선택하세요.


// hr > member (detail)
$txt_tab_hr_member_01 = "General"; // 일 반
$txt_tab_hr_member_A = "Alamat"; // 주 소
$txt_tab_hr_member_A01 = "Alamat Keluarga"; // 가족단위로 수정

$txt_tab_hr_member_02 = "Keluarga"; // 가 족
$txt_tab_hr_member_0201 = "Rel."; // 관 계
$txt_tab_hr_member_0202 = "Umur"; // 나 이
$txt_tab_hr_member_0203 = "Edu."; // 학 력
$txt_tab_hr_member_0204 = "Agma"; // 종 교
$txt_tab_hr_member_0210 = "Relation"; // 세대주와의 관계
$txt_tab_hr_member_0210M = "Husband"; // 남 편
$txt_tab_hr_member_0210F = "Wife"; // 아 내
$txt_tab_hr_member_0211 = "Parent"; // 부 모
$txt_tab_hr_member_0211M = "Father"; // 부
$txt_tab_hr_member_0211F = "Mother"; // 모
$txt_tab_hr_member_0212 = "Child"; // 자 녀
$txt_tab_hr_member_0212M = "Son"; // 아 들
$txt_tab_hr_member_0212F = "Daughter"; // 딸
$txt_tab_hr_member_0213 = "Relative"; // 친 지
$txt_tab_hr_member_0214 = "Friend"; // 친 구
$txt_tab_hr_member_0219 = "Undefined"; // 기 타
$txt_tab_hr_member_02x = "Enter"; // 직접 입력
$txt_tab_hr_member_03 = "Kerjaan/Study"; // 직장/학교
$txt_tab_hr_member_0301 = "Work"; // 직 장
$txt_tab_hr_member_0302 = "Work Type"; // 직 종
$txt_tab_hr_member_0303 = "Job"; // 직 업
$txt_tab_hr_member_0304 = "Perusahaan"; // 직장명
$txt_tab_hr_member_0305 = "Tentang"; // 회사 소개
$txt_tab_hr_member_0306 = "From"; // 입 사
$txt_tab_hr_member_0307 = "Until"; // 퇴 사

$txt_tab_hr_member_0351 = "Study"; // 학 교
$txt_tab_hr_member_0352 = "School Name"; // 학교명
$txt_tab_hr_member_0353 = "Degree"; // 구 분
$txt_tab_hr_member_03531 = "Kinder G"; // 유치원
$txt_tab_hr_member_03532 = "Primary S"; // 초등학교
$txt_tab_hr_member_03533 = "Middle S"; // 중학교
$txt_tab_hr_member_03534 = "High S"; // 고등학교
$txt_tab_hr_member_03535 = "College (2Y)"; // 대학(2년)
$txt_tab_hr_member_03536 = "College (3Y)"; // 대학(2년)
$txt_tab_hr_member_03537 = "Univ. (Bc)"; // 대학교(학사)
$txt_tab_hr_member_03538 = "Univ. (Ms)"; // 대학원(석사)
$txt_tab_hr_member_03539 = "Univ. (Dr)"; // 대학원(박사)
$txt_tab_hr_member_0354 = "Location"; // 학교소재지
$txt_tab_hr_member_0355 = "Major/Dept"; // 전공/과
$txt_tab_hr_member_0356 = "Entered"; // 입 학
$txt_tab_hr_member_0357 = "Graduated"; // 졸 업
$txt_tab_hr_member_0358 = "Status"; // 졸업 여부
$txt_tab_hr_member_03580 = "Dropout"; // 중 퇴
$txt_tab_hr_member_03581 = "Enrolled"; // 재학중
$txt_tab_hr_member_03582 = "Completed"; // 졸 업

$txt_tab_hr_member_04 = "Agama"; // 종 교
$txt_tab_hr_member_0401 = "Protestan"; // 개신교
$txt_tab_hr_member_0402 = "Katolik"; // 카톨릭
$txt_tab_hr_member_0403 = "Budhism"; // 불 교
$txt_tab_hr_member_0404 = "Islam"; // 이슬람교
$txt_tab_hr_member_0405 = "Hindism"; // 힌두교
$txt_tab_hr_member_0409 = "Lain-lain."; // 기 타
$txt_tab_hr_member_0421 = "Church Name"; // 교회/단체
$txt_tab_hr_member_0422 = "Sect"; // 교파/교단
$txt_tab_hr_member_0423 = "Location"; // 국가/지역
$txt_tab_hr_member_0424 = "Converted"; // 입교년도
$txt_tab_hr_member_0425 = "Baptized"; // 수세년도
$txt_tab_hr_member_0426 = "Expelled"; // 제적년도
$txt_tab_hr_member_0427 = "Expelled Reason"; // 제적사유
$txt_tab_hr_member_0428 = "Church"; // 본교회
$txt_tab_hr_member_0429 = "Title"; // 직 분
$txt_tab_hr_member_0430 = "Senior Pastor"; // 담임목사

$txt_tab_hr_member_05 = "Training"; // 훈련/활동
$txt_tab_hr_member_0501 = "Previous Church"; // 이전 교회
$txt_tab_hr_member_0502 = "Church Name"; // 교회 이름
$txt_tab_hr_member_0503 = "Evaulation"; // 항목별 평가
$txt_tab_hr_member_0504 = "Status"; // 수료 여부
$txt_tab_hr_member_05040 = "Dropout"; // 미수료
$txt_tab_hr_member_05041 = "Enrolled"; // 수료중
$txt_tab_hr_member_05042 = "Completed"; // 수 료
$txt_tab_hr_member_0506 = "Cume"; // 점 수
$txt_tab_hr_member_0507 = "Credit"; // 평 가
$txt_tab_hr_member_0508 = "Remarks"; // 참고 사항
$txt_tab_hr_member_0509 = "Pastor Comments"; // 교역자 견해

$txt_tab_hr_member_06 = "Specifics"; // 특기사항
$txt_tab_hr_member_0601 = "Guide"; // 인도자
$txt_tab_hr_member_0602 = "Blood Type"; // 혈액형
$txt_tab_hr_member_0603 = "Wedding Anniversary"; // 결혼 기념일
$txt_tab_hr_member_0604 = "Financial Status"; // 가정 형편
$txt_tab_hr_member_0605 = "Hobby"; // 취 미
$txt_tab_hr_member_0606 = "Talent"; // 특 기
$txt_tab_hr_member_0607 = "Special Gift"; // 은 사
$txt_tab_hr_member_0608 = "Health"; // 건 강
$txt_tab_hr_member_0609 = "Car Lisence No."; // 차량 번호 
$txt_tab_hr_member_0610 = "Parking Lot No."; // 주차장 번호

$txt_tab_hr_member_07 = "Pengajian"; // 급 여
$txt_tab_hr_member_07s = "Gaji"; // 급여
$txt_tab_hr_member_0701 = "M-Y"; // 연/월
$txt_tab_hr_member_0702 = "Type"; // 급여 구분
$txt_tab_hr_member_07021 = "Salary"; // 정기 급여
$txt_tab_hr_member_07022 = "Incentive"; // 인센티브
$txt_tab_hr_member_0703 = "Payroll Code"; // 임금 코드
$txt_tab_hr_member_0704 = "Avr. Wage"; // 평균 급여
$txt_tab_hr_member_0705 = "Incentive"; // 인센티브
$txt_tab_hr_member_0706 = "Bonus"; // 보너스
$txt_tab_hr_member_0707 = "Deduction"; // 공 제
$txt_tab_hr_member_0708 = "Offset"; // 급여 조정
$txt_tab_hr_member_0709 = "Tax"; // 세금
$txt_tab_hr_member_0710 = "Wage"; // 확정 급여
$txt_tab_hr_member_0711 = "Payment"; // 지급액
$txt_tab_hr_member_0712 = "Diffrence"; // 지급 차액
$txt_tab_hr_member_0713 = "Due Date"; // 급여일
$txt_tab_hr_member_0714 = "Pay Date"; // 지급일

$txt_tab_hr_member_09 = "Updates"; // 변경사항
$txt_tab_hr_member_0901 = "Date"; // 변경일
$txt_tab_hr_member_0902 = "Status"; // 사원 구분
$txt_tab_hr_member_09021 = "New Employee"; // 새가족
$txt_tab_hr_member_09022 = "Employee"; // 사 원
$txt_tab_hr_member_09023 = "Non-employee"; // 퇴 사

$txt_tab_hr_member_chk01 = "Please input Amount."; // 금액을 입력하셔야 합니다.
$txt_tab_hr_member_chk02 = "Please input Name"; // 아래에 이름을 직접 입력하세요.
$txt_tab_hr_member_chk03 = "Do you want to finish calculating?"; // 계수를 완료하시겠습니까?
$txt_tab_hr_member_chk04 = "Do you want to delete this?"; // 삭제하시겠습니까?


// chmember > group, district
$txt_ch_group_01 = "$ch_comm_cug10"." List"; // 구역 리스트
$txt_ch_group_02 = "Add "."$ch_comm_cug10"; // 구역 등록
$txt_ch_group_03 = "Update "."$ch_comm_cug10"; // 구역 정보 수정
$txt_ch_group_04 = "Delete "."$ch_comm_cug10"; // 구역 삭제
$txt_ch_group_05 = "$ch_comm_cug10"." Name"; // 구역 이름
$txt_ch_group_06 = "$ch_comm_cug10"." Category"; // 구역 카테고리
$txt_ch_group_07 = "About"; // 간략 소개
$txt_ch_group_08 = "Details"; // 상세 소개
$txt_ch_group_09 = "Activation"; // 활성화
$txt_ch_group_31 = "$ch_comm_dir20"." List"; // 지역 리스트


// chmember > member (basic)
$txt_ch_member_01 = "Anggota"; // 성도 리스트
$txt_ch_member_02 = "Tambah Profil Anggota"; // 성도 등록하기
$txt_ch_member_03 = "Perbarui Profil Anggota"; // 성도 수정하기
$txt_ch_member_04 = "Hapus Profil Anggota"; // 성도 삭제하기
$txt_ch_member_05 = "Kode Anggota"; // 성도 코드
$txt_ch_member_06 = "ID Website"; // 웹사이트 ID
$txt_ch_member_07 = "Level Anggota"; // 성도 등급
$txt_ch_member_08 = "Perusahaan/Organisasi"; // 회사/단체명
$txt_ch_member_09 = "Sinkronisasi ke Website"; // 웹사이트 DB 연동 여부
$txt_ch_member_10 = "Tidak dihubungkan"; // 단 절
$txt_ch_member_11 = "Digandakan"; // 중 복
$txt_ch_member_12 = "Gabung"; // 통 합
$txt_ch_member_13 = "Jarak Point"; // 마일리지 포인트
$txt_ch_member_14 = "Reseller"; // 리셀러
$txt_ch_member_15 = "Non-reseller"; // 일반 성도
$txt_ch_member_16 = "Berita"; // 뉴스 레터
$txt_ch_member_17 = "Join"; // 가 입
$txt_ch_member_18 = "Batal"; // 해 제
$txt_ch_member_31 = "Nama Pangilan"; // 영문 이름
$txt_ch_member_32 = "Marital Status"; // 결혼 여부
$txt_ch_member_321 = "Single"; // 미 혼
$txt_ch_member_322 = "Married"; // 기 혼
$txt_ch_member_323 = "Divorced"; // 이 혼
$txt_ch_member_324 = "Bereaved"; // 사 별
$txt_ch_member_325 = "Remarried"; // 재 혼
$txt_ch_member_3291 = "Expelled Date"; // 교회 제적일
$txt_ch_member_3292 = "Remarks"; // 비 고
$txt_ch_member_3293 = "Passed Away"; // 소 천
$txt_ch_member_3294 = "Cause of Exp."; // 제적 사유

$txt_ch_member_33 = "Family Head"; // 세대주 여부
$txt_ch_member_331 = "Head"; // 세대주
$txt_ch_member_332 = "Member"; // 세대원
$txt_ch_member_333 = "Single"; // 단독 세대주
$txt_ch_member_334 = "Another Head"; // 세대 분리
$txt_ch_member_335 = "Berapa"; // 세대원수
$txt_ch_member_336 = "Orang"; // 명
$txt_ch_member_34 = "Age Group"; // 소 속
$txt_ch_member_341 = "Adult"; // 장년부
$txt_ch_member_342 = "Young"; // 청년부
$txt_ch_member_343 = "Collegeate"; // 대학부
$txt_ch_member_344 = "Schooler"; // 주일학교
$txt_ch_member_345 = "Unknown"; // 기 타
$txt_ch_member_346 = "Undefined"; // 미소속
$txt_ch_member_35 = "Community"; // 공동체 모임
$txt_ch_member_36 = "New Family"; // 새가족 모임
$txt_ch_member_37 = "Faith Level"; // 신 급
$txt_ch_member_371 = "Baptized"; // 세 례
$txt_ch_member_372 = "B. Suckling"; // 영아세례
$txt_ch_member_373 = "B. Infant"; // 유아세례
$txt_ch_member_374 = "Converted"; // 입 교
$txt_ch_member_375 = "B. Immersion"; // 침 례
$txt_ch_member_376 = "Learned"; // 학 습
$txt_ch_member_38 = "Date of Regis."; // 교회 등록일
$txt_ch_member_380 = "Crossed-out"; // 제적교인
$txt_ch_member_381 = "Non-member"; // 미등록
$txt_ch_member_382 = "Member"; // 등록교인
$txt_ch_member_39 = "Passport No."; // 여권 번호
$txt_ch_member_40 = "Expiry Date"; // 만료여권 만료일
$txt_ch_member_41 = "Nationality"; // 국 적
$txt_ch_member_42 = "Visa"; // 비자 종류
$txt_ch_member_43 = "Spouse"; // 배우자
$txt_ch_member_44 = "Gambar"; // 사진

$txt_ch_member_60 = "Laporan Mingguan"; // 순장 주간 보고서
$txt_ch_member_611 = "Hari Minggu"; // 주일 출석
$txt_ch_member_612 = "Hari Biasa"; // 순예배 출석
$txt_ch_member_621 = "Abs."; // 여부
$txt_ch_member_6211 = "Yes"; // 출석
$txt_ch_member_6212 = "No"; // 결석
$txt_ch_member_622 = "Sebab"; // 사유
$txt_ch_member_63 = "Cataan"; // 조치사항
$txt_ch_member_631 = "oleh Kepala"; // 순장 조치사항
$txt_ch_member_632 = "oleh Pendeta"; // 담당 교역자 조치사항
$txt_ch_member_64 = "Doa"; // 기도 제목
$txt_ch_member_65 = "Kirim"; // 전 송

$txt_ch_member_chk01 = "Pilih Sistem."; // 시스템을 선택하세요.


// chmember > member (detail)
$txt_tab_member_01 = "General"; // 일 반
$txt_tab_member_A = "Alamat"; // 주 소
$txt_tab_member_A01 = "Alamat Keluarga"; // 가족단위로 수정

$txt_tab_member_02 = "Keluarga"; // 가 족
$txt_tab_member_0201 = "Rel."; // 관 계
$txt_tab_member_0202 = "Umur"; // 나 이
$txt_tab_member_0203 = "Edu."; // 학 력
$txt_tab_member_0204 = "Agma"; // 종 교
$txt_tab_member_0210 = "Relation"; // 세대주와의 관계
$txt_tab_member_0210M = "Husband"; // 남 편
$txt_tab_member_0210F = "Wife"; // 아 내
$txt_tab_member_0211 = "Parent"; // 부 모
$txt_tab_member_0211M = "Father"; // 부
$txt_tab_member_0211F = "Mother"; // 모
$txt_tab_member_0212 = "Child"; // 자 녀
$txt_tab_member_0212M = "Son"; // 아 들
$txt_tab_member_0212F = "Daughter"; // 딸
$txt_tab_member_0213 = "Relative"; // 친 지
$txt_tab_member_0214 = "Friend"; // 친 구
$txt_tab_member_0219 = "Undefined"; // 기 타
$txt_tab_member_02x = "Enter"; // 직접 입력
$txt_tab_member_03 = "Kerjaan/Study"; // 직장/학교
$txt_tab_member_0301 = "Work"; // 직 장
$txt_tab_member_0302 = "Work Type"; // 직 종
$txt_tab_member_0303 = "Job"; // 직 업
$txt_tab_member_0304 = "Perusahaan"; // 직장명
$txt_tab_member_0305 = "Tentang"; // 회사 소개
$txt_tab_member_0306 = "From"; // 입 사
$txt_tab_member_0307 = "Until"; // 퇴 사

$txt_tab_member_0351 = "Study"; // 학 교
$txt_tab_member_0352 = "School Name"; // 학교명
$txt_tab_member_0353 = "Degree"; // 구 분
$txt_tab_member_03531 = "Kinder G"; // 유치원
$txt_tab_member_03532 = "Primary S"; // 초등학교
$txt_tab_member_03533 = "Middle S"; // 중학교
$txt_tab_member_03534 = "High S"; // 고등학교
$txt_tab_member_03535 = "College (2Y)"; // 대학(2년)
$txt_tab_member_03536 = "College (3Y)"; // 대학(2년)
$txt_tab_member_03537 = "Univ. (Bc)"; // 대학교(학사)
$txt_tab_member_03538 = "Univ. (Ms)"; // 대학원(석사)
$txt_tab_member_03539 = "Univ. (Dr)"; // 대학원(박사)
$txt_tab_member_0354 = "Location"; // 학교소재지
$txt_tab_member_0355 = "Major/Dept"; // 전공/과
$txt_tab_member_0356 = "Entered"; // 입 학
$txt_tab_member_0357 = "Graduated"; // 졸 업
$txt_tab_member_0358 = "Status"; // 졸업 여부
$txt_tab_member_03580 = "Dropout"; // 중 퇴
$txt_tab_member_03581 = "Enrolled"; // 재학중
$txt_tab_member_03582 = "Completed"; // 졸 업

$txt_tab_member_04 = "Baptism"; // 신 급
$txt_tab_member_0401 = "Protestan"; // 개신교
$txt_tab_member_0402 = "Katolik"; // 카톨릭
$txt_tab_member_0403 = "Budhism"; // 불 교
$txt_tab_member_0404 = "Islam"; // 이슬람교
$txt_tab_member_0405 = "Hindism"; // 힌두교
$txt_tab_member_0409 = "Lain-lain."; // 기 타
$txt_tab_member_0421 = "Church Name"; // 교회/단체
$txt_tab_member_0422 = "Sect"; // 교파/교단
$txt_tab_member_0423 = "Location"; // 국가/지역
$txt_tab_member_0424 = "Converted"; // 입교년도
$txt_tab_member_0425 = "Baptized"; // 수세년도
$txt_tab_member_0426 = "Expelled"; // 제적년도
$txt_tab_member_0427 = "Expelled Reason"; // 제적사유
$txt_tab_member_0428 = "Church"; // 본교회
$txt_tab_member_0429 = "Title"; // 직 분
$txt_tab_member_0430 = "Senior Pastor"; // 담임목사

$txt_tab_member_05 = "Training"; // 훈련/활동
$txt_tab_member_0501 = "Previous Church"; // 이전 교회
$txt_tab_member_0502 = "Church Name"; // 교회 이름
$txt_tab_member_0503 = "Evaulation"; // 항목별 평가
$txt_tab_member_0504 = "Status"; // 수료 여부
$txt_tab_member_05040 = "Dropout"; // 미수료
$txt_tab_member_05041 = "Enrolled"; // 수료중
$txt_tab_member_05042 = "Completed"; // 수 료
$txt_tab_member_0506 = "Cume"; // 점 수
$txt_tab_member_0507 = "Credit"; // 평 가
$txt_tab_member_0508 = "Remarks"; // 참고 사항
$txt_tab_member_0509 = "Pastor Comments"; // 교역자 견해

$txt_tab_member_06 = "Specifics"; // 특기사항
$txt_tab_member_0601 = "Guide"; // 인도자
$txt_tab_member_0602 = "Blood Type"; // 혈액형
$txt_tab_member_0603 = "Wedding Anniversary"; // 결혼 기념일
$txt_tab_member_0604 = "Financial Status"; // 가정 형편
$txt_tab_member_0605 = "Hobby"; // 취 미
$txt_tab_member_0606 = "Talent"; // 특 기
$txt_tab_member_0607 = "Special Gift"; // 은 사
$txt_tab_member_0608 = "Health"; // 건 강
$txt_tab_member_0609 = "Car Lisence No."; // 차량 번호 
$txt_tab_member_0610 = "Parking Lot No."; // 주차장 번호

$txt_tab_member_07 = "Offering"; // 헌 금
$txt_tab_member_07s = "Offering"; // 헌금
$txt_tab_member_0701 = "Type"; // 헌금 구분
$txt_tab_member_0702 = "Select Name"; // 헌금자 선택
$txt_tab_member_0703 = "Name"; // 헌금자 이름
$txt_tab_member_0704 = "Input Name"; // 직접 입력
$txt_tab_member_0705 = "Amount"; // 금 액
$txt_tab_member_0706 = "Enter"; // 입 력
$txt_tab_member_0707 = "Submit"; // 계수 완료
$txt_tab_member_0708 = "Anonymous"; // 무 명
$txt_tab_member_0709 = "Offering List"; // 헌금자 리스트
$txt_tab_member_0710 = "Date of Counting"; // 헌금 계수일
$txt_tab_member_0711 = "Total Amount"; // 총 헌금 합계
$txt_tab_member_0712 = "Report of Offering"; // 헌금 현황 보고
$txt_tab_member_0713 = "Report of Offering"; // 헌금 현황
$txt_tab_member_0714 = "Semua"; // 종합
$txt_tab_member_0715 = "Divisi"; // 구 분
$txt_tab_member_0716 = "Cataan"; // 비 고
$txt_tab_member_0717 = "Periksaan"; // 확 인
$txt_tab_member_0718 = "Tanda-tangan"; // 서명
$txt_tab_member_0719 = "Direktur F."; // 재정부장
$txt_tab_member_0720 = "Account"; // 회 계
$txt_tab_member_0721 = "Kasier"; // 현금담당
$txt_tab_member_0722 = "Sub Total"; // 소 계
$txt_tab_member_0723 = "Total"; // 합 계
$txt_tab_member_0724 = "Date of Offering"; // 헌금일

$txt_tab_member_08 = "Visit"; // 심 방
$txt_tab_member_0801 = "Visit Date"; // 심방 일시
$txt_tab_member_0802 = "Visit Subject"; // 심방 제목/사유
$txt_tab_member_0803 = "Place"; // 심방 장소
$txt_tab_member_0804 = "Visitor(s)"; // 심방자
$txt_tab_member_0805 = "Posting Date"; // 기록일시
$txt_tab_member_0806 = "Writer"; // 기록자
$txt_tab_member_0807 = "Visit Note"; // 심방 메모
$txt_tab_member_0808 = "Hymn"; // 찬 송
$txt_tab_member_0809 = "Prayer"; // 기 도
$txt_tab_member_0810 = "Bible"; // 성 경
$txt_tab_member_0811 = "Worship"; // 인 도

$txt_tab_member_09 = "Updates"; // 변경사항
$txt_tab_member_0901 = "Date"; // 변경일
$txt_tab_member_0902 = "Status"; // 교인 상태
$txt_tab_member_09021 = "New Member"; // 새가족
$txt_tab_member_09022 = "Member"; // 교 인
$txt_tab_member_09023 = "Non-member"; // 제 적

$txt_tab_member_chk01 = "Please input Amount."; // 금액을 입력하셔야 합니다.
$txt_tab_member_chk02 = "Please input Name"; // 아래에 이름을 직접 입력하세요.
$txt_tab_member_chk03 = "Do you want to finish calculating?"; // 계수를 완료하시겠습니까?
$txt_tab_member_chk04 = "Do you want to delete this?"; // 삭제하시겠습니까?


// member > member
$txt_stf_member_01 = "Anggota"; // 회원 리스트
$txt_stf_member_02 = "Tambah Profil Anggota"; // 회원 등록하기
$txt_stf_member_03 = "Perbarui Profil Anggota"; // 회원 수정하기
$txt_stf_member_04 = "Hapus Profil Anggota"; // 회원 삭제하기
$txt_stf_member_05 = "Kode Anggota"; // 회원 코드
$txt_stf_member_06 = "ID Anggota"; // 회원 ID
$txt_stf_member_07 = "Level Anggota"; // 회원 등급
$txt_stf_member_08 = "Perusahaan/Organisasi"; // 회사/단체명
$txt_stf_member_09 = "Sinkronisasi ke Website"; // 웹사이트 DB 연동 여부
$txt_stf_member_10 = "Tidak dihubungkan"; // 단 절
$txt_stf_member_11 = "Digandakan"; // 중 복
$txt_stf_member_12 = "Gabung"; // 통 합
$txt_stf_member_13 = "Jarak Point"; // 마일리지 포인트
$txt_stf_member_14 = "Reseller"; // 리셀러
$txt_stf_member_15 = "Non-reseller"; // 일반 회원
$txt_stf_member_16 = "Berita"; // 뉴스 레터
$txt_stf_member_17 = "Join"; // 가 입
$txt_stf_member_18 = "Batal"; // 해 제
$txt_stf_member_51 = "Distributor"; // 대리점 리스트
$txt_stf_member_52 = "Tambah Profil Distributor"; // 대리점 등록하기
$txt_stf_member_53 = "Perbarui Profil Distributor"; // 대리점 수정하기
$txt_stf_member_54 = "Hapus Profil Distributor"; // 대리점 삭제하기
$txt_stf_member_55 = "Kode D."; // 대리점 코드
$txt_stf_member_57 = "Level D."; // 대리점 등급
$txt_stf_member_60 = "Nama Bank(Cabang)"; // 결제 은행(지점)
$txt_stf_member_61 = "Nama Akun"; // 예금주
$txt_stf_member_62 = "No. Akun"; // 계좌 번호

$txt_stf_member_chk01 = "Pilih Sistem."; // System을 선택하세요.

// member > staff
$txt_stf_staff_01 = "Pegawai"; // 사원 리스트
$txt_stf_staff_02 = "Tambah Profil"; // 사원 등록하기
$txt_stf_staff_03 = "Perbarui Profil"; // 사원 수정하기
$txt_stf_staff_04 = "Hapus Profile"; // 사원 삭제하기
$txt_stf_staff_05 = "Gudang"; // Shop 회원 ID
$txt_stf_staff_06 = "Unknown"; // 해당사항 없음
$txt_stf_staff_07 = "Kode Pegawai"; // 사원 코드
$txt_stf_staff_08 = "Nama"; // 이 름
$txt_stf_staff_09 = "JenKel"; // 성 별 Jenis Kelamin
$txt_stf_staff_10 = "Laki"; // 남 Laki-laki
$txt_stf_staff_11 = "Permp"; // 여 Perempuan
$txt_stf_staff_12 = "Tanggal Lahir"; // 생년월일
$txt_stf_staff_13 = "Tahun"; // 양력
$txt_stf_staff_14 = "Bulan"; // 음력
$txt_stf_staff_15 = "Bagian"; // 부 서
$txt_stf_staff_16 = "Job Title"; // 직 책
$txt_stf_staff_17 = "Level"; // 직 급
$txt_stf_staff_18 = "Pilih Cabang"; // 지사 선택

$txt_stf_staff_chk01 = "Silahkan Masukkan Nama."; // 이름을 입력하세요.
$txt_stf_staff_chk02 = "Data yang Anda submit sudah ada."; // 입력하신 이름과 동일인이 있습니다.
$txt_stf_staff_chk03 = "Silahkan Cek dan masukkan ulang."; // 확인하시고 다시 입력하여 주십시오.
$txt_stf_staff_chk04 = "Silahkan Pilih Perusahaan."; // 회사를 선택하세요.


// member > special
$txt_stf_model_01 = "Model"; // 모델 리스트
$txt_stf_model_02 = "Tambah Model"; // 모델 등록하기
$txt_stf_model_03 = "Perbarui Model"; // 모델 수정하기
$txt_stf_model_04 = "Hapus Model"; // 모델 삭제하기
$txt_stf_model_05 = "User ID Toko"; // Shop 회원 ID
$txt_stf_model_06 = "No"; // 해당사항 없음
$txt_stf_model_07 = "Jenis/Tipe"; // 계약 유형
$txt_stf_model_07_01 = "Kontrak"; // 계약직
$txt_stf_model_07_02 = "Freelancer"; // 프리랜서
$txt_stf_model_08 = "Profil"; // 상세 프로필
$txt_stf_model_09 = "Periode Kontrak"; // 계약 기간
$txt_stf_model_10 = "VISA";
$txt_stf_model_11 = "Diberhentikan"; // 계약 만료일


// system > client
$txt_sys_client_01 = "Nama Sistem"; // System 이름
$txt_sys_client_02 = "Kode"; // 코드
$txt_sys_client_03 = "ID Sistem";
$txt_sys_client_04 = "Level Sistem"; // System 등급
$txt_sys_client_05 = "Website"; // 웹사이트
$txt_sys_client_06 = "Tgl. Msk"; // 등록일 Tanggal Posting
$txt_sys_client_061 = "Tgl. Msk"; // 시스템 등록일 Tanggal Posting
$txt_sys_client_062 = "Last Update"; // 최종 변경일시
$txt_sys_client_07 = "Nama Pengelola"; // 최고관리자 이름
$txt_sys_client_08 = "No.Telp"; // 전화번호
$txt_sys_client_09 = "No.HP"; // 휴대폰
$txt_sys_client_10 = "Sistem-sistem"; // System 리스트
$txt_sys_client_11 = "Tambah Sistem"; // System 등록하기
$txt_sys_client_12 = "Perbarui Sistem"; // System 수정하기
$txt_sys_client_13 = "Hapus Sistem"; // System 삭제하기
$txt_sys_client_14 = "Alamat"; // 주 소
$txt_sys_client_15 = "Kode Pos"; // 우편번호
$txt_sys_client_16 = "Jalan";
$txt_sys_client_17 = "Kota, Provinsi";
$txt_sys_client_18 = "Akun DB"; // DB 계정
$txt_sys_client_19 = "Nama Akun DB"; // DB명,계정명,비밀번호
$txt_sys_client_20 = "Kata Sandi Baru"; // 새 비밀번호
$txt_sys_client_21 = "Masukkan Ulang"; // 재입력
$txt_sys_client_22 = "Perbarui"; // 변경하기
$txt_sys_client_23 = "Profil"; // 프로필
$txt_sys_client_24 = "Kondisi"; // 계약관계
$txt_sys_client_25 = "Kontak Info."; // 연락정보
$txt_sys_client_26 = "Memo"; // 관리자 메모

$txt_sys_client_chk01 = "Silahkan Masukkan ID."; // ID를 입력하세요.
$txt_sys_client_chk02 = "ID harus kombinasi angka dan huruf dengan panjang karakter 4-12."; // ID는 4~12자의 영소문자 또는 영소문자와 숫자의 결합이어야 합니다.
$txt_sys_client_chk03 = "Huruf Pertama ID harus berupa abjad."; // ID의 첫글자는 언제나 영소문자여야 합니다.
$txt_sys_client_chk04 = "Spasi kosong tidak diijinkan."; // 공백이 허용되지 않습니다.
$txt_sys_client_chk05 = "Silahkan Masukkan Kata Sandi."; // 비밀번호를 입력하세요.
$txt_sys_client_chk06 = "Panjang Kata Sandi harus 4 Karakter dan terdiri dari huruf kecil (a-z) atau angka."; // 비밀번호는 4~12자의 영문자와 숫자 또는 영문자와 숫자의 결합이어야 합니다.
$txt_sys_client_chk07 = "Silahkan Masukkan Nama Sistem."; // 시스템의 Client 이름을 입력하세요.
$txt_sys_client_chk08 = "Silahkan Masukkan Alamat Email."; // E-mail 주소를 입력하세요.
$txt_sys_client_chk09 = "Alamat Email yang Anda masukkan invalid."; // E-mail 주소의 형식이 틀렸습니다.
$txt_sys_client_chk10 = "Silahkan Masukkan Kode Sementara."; // 인증번호를 입력하세요.


// system > user
$txt_sys_user_01 = "Pengelola Sistem"; // Shop Manager 리스트
$txt_sys_user_02 = "Tambah Pengelola Sistem"; // Shop Manager 등록하기
$txt_sys_user_03 = "Perbarui Pengelola Sistem"; // Shop Manager 수정하기
$txt_sys_user_04 = "Hapus Pengelola Sistem"; // Shop Manager 삭제하기
$txt_sys_user_05 = "ID Pengelola"; // Manager ID
$txt_sys_user_06 = "Nama Pengelola"; // Manager 이름
$txt_sys_user_07 = "Sistem"; // Shop
$txt_sys_user_08 = "Level"; // Manager 등급
$txt_sys_user_09 = "Terakhir Login"; // 지난 로그인
$txt_sys_user_10 = "Kunjungan"; // 방문수
$txt_sys_user_11 = "Bahasa"; // 사용 언어
$txt_sys_user_12 = "Belum/Tidak Login"; // 로그인 기록 없음

$txt_sys_user_chk01 = "Silahkan Masukkan Nama Pengelola Sistem."; // Shop Manager 이름을 입력하세요.
$txt_sys_user_chk02 = "";
$txt_sys_user_chk03 = "Kata Sandi Anda Tidak Valid."; // 입력하신 두 비밀번호가 일치하지 않습니다.


// system > church_job category
$txt_sys_chjob_01 = "Type"; // 구 분
$txt_sys_chjob_011 = "Clergymen"; // 교역자
$txt_sys_chjob_012 = "Laity"; // 평신도
$txt_sys_chjob_013 = "Non-Kristen"; // 일반인(태신자)
$txt_sys_chjob_02 = "Kode"; // 코 드
$txt_sys_chjob_031 = "Position Name"; // 직위 이름
$txt_sys_chjob_032 = "Post Name"; // 직분 이름
$txt_sys_chjob_033 = "Occupation Jame"; // 직업 이름
$txt_sys_chjob_04 = "Tambah Kode Baru"; // 코드 등록하기
$txt_sys_chjob_05 = "Perbarui Kode"; // 코드 수정하기
$txt_sys_chjob_06 = "Hapus Kode"; // 코드 삭제하기

$txt_sys_chjob_chk01 = "Silahkan Masukkan Kode."; // 코드를 입력하세요.
$txt_sys_chjob_chk02 = "Silahkan Masukkan Kode Nama Kode."; // 분류명을 입력하세요.
$txt_sys_chjob_chk03 = "Your submittion already exists."; // 동일한 코드가 존재합니다.


// system > tarin_course [*]
$txt_sys_tcourse_01 = "Training/Activity"; // 훈련/활동 과정
$txt_sys_tcourse_02 = "Add Training/Activity"; // 훈련/활동 과정 등록
$txt_sys_tcourse_03 = "Update Training/Activity"; // 훈련/활동 과정 수정
$txt_sys_tcourse_04 = "Delete Training/Activity"; // 훈련/활동 과정 삭제
$txt_sys_tcourse_05 = "Course Code"; // 과정 코드
$txt_sys_tcourse_051 = "Course Category"; // 훈련/활동 카테고리
$txt_sys_tcourse_06 = "Course Name"; // 훈련/활동 이름
$txt_sys_tcourse_07 = "Period No."; // 기 수
$txt_sys_tcourse_08 = "Open"; // 시작일
$txt_sys_tcourse_09 = "Close"; // 수료일
$txt_sys_tcourse_10 = "Lecturer"; // 강 사
$txt_sys_tcourse_11 = "Trainee"; // 수강 대상
$txt_sys_tcourse_12 = "Course Terms"; // 과정 기간
$txt_sys_tcourse_13 = "Class Hours"; // 과정 시간
$txt_sys_tcourse_14 = "Course Details"; // 과정 내용
$txt_sys_tcourse_15 = "Evaluation"; // 평가 항목
$txt_sys_tcourse_1501 = "Attendance"; // 출 석
$txt_sys_tcourse_1502 = "Attitude"; // 태 도
$txt_sys_tcourse_1503 = "Achievement"; // 달성도
$txt_sys_tcourse_1504 = "Knowledge"; // 지 식
$txt_sys_tcourse_1505 = "Test"; // 시 험
$txt_sys_tcourse_1506 = "Assignment"; // 과제물
$txt_sys_tcourse_16 = "Tuition"; // 수강료

$txt_sys_tcourse_chk01 = "Please select Course Category."; // 카테고리를 선택하셔야 합니다.


// system > train_course [church]
$txt_sys_chcourse_1501 = "Attendance"; // 출 석
$txt_sys_chcourse_1502 = "Prayer"; // 기 도
$txt_sys_chcourse_1503 = "Q.T."; // 큐 티
$txt_sys_chcourse_1504 = "Bible"; // 성경지식
$txt_sys_chcourse_1505 = "Test"; // 시 험
$txt_sys_chcourse_1506 = "Assignment"; // 과제물


// system > shop
$txt_sys_shop_01 = "Toko"; // 매장 리스트
$txt_sys_shop_02 = "Tambah Toko"; // 매장 등록하기
$txt_sys_shop_03 = "Perbarui Toko"; // 매장 수정하기
$txt_sys_shop_04 = "Hapus Toko"; // 매장 삭제하기
$txt_sys_shop_05 = "Kode Toko"; // 매장 코드
$txt_sys_shop_06 = "Nama Toko"; // 매장 이름
$txt_sys_shop_07 = "Janis Toko"; // 매장 유형
$txt_sys_shop_071 = "Toko Cabang"; // 직영 매장
$txt_sys_shop_072 = "Toko Konsinyasi"; // 위탁판매 매장
$txt_sys_shop_073 = "Toko Asosiasi"; // 협력 매장
$txt_sys_shop_08 = "Pengelola Toko"; // 관리자
$txt_sys_shop_09 = "On"; // 운영
$txt_sys_shop_10 = "Off"; // 중지
$txt_sys_shop_11 = "On"; // 운영
$txt_sys_shop_12 = "On-line"; // 온라인
$txt_sys_shop_13 = "Off-line"; // 오프라인
$txt_sys_shop_14 = "On/Off-line"; // 온/오프라인
$txt_sys_shop_15 = "Skala Toko"; // 매장 규모별 구분
$txt_sys_shop_151 = "Hypermarket"; // 대형 매장
$txt_sys_shop_152 = "Supermarket"; // 수퍼마켓

$txt_sys_shop_chk01 = "Silahkan Masukkan Kode Toko."; // 매장 코드를 입력하세요
$txt_sys_shop_chk02 = "Kode Toko harus kombinasi dari angka dan huruf dengan panjang karakter 4-12."; // 매장 코드는 4~12자의 영소문자 또는 영소문자와 숫자의 결합이어야 합니다.
$txt_sys_shop_chk03 = "Huruf Pertama dari Kode Toko harus berupa Abjad."; // 매장 코드의 첫글자는 언제나 영소문자여야 합니다.
$txt_sys_shop_chk04 = "Spasi tidak diijinkan."; // 공백이 허용되지 않습니다.
$txt_sys_shop_chk05 = "Silahkan Masukkan Nama Toko."; // 매장 이름을 입력하세요.


// system > user2
$txt_sys_user2_01 = "Pengelola Toko"; // Shop Manager 리스트
$txt_sys_user2_02 = "Tambah Pengelola Toko"; // Shop Manager 등록하기
$txt_sys_user2_03 = "Perbarui Pengelola Toko"; // Shop Manager 수정하기
$txt_sys_user2_04 = "Hapus Pengelola Toko"; // Shop Manager 삭제하기
$txt_sys_user2_05 = "ID Pengelola"; // Manager ID
$txt_sys_user2_06 = "Nama Pengelola"; // Manager 이름
$txt_sys_user2_07 = "Toko"; // Shop
$txt_sys_user2_08 = "Level"; // Manager 등급
$txt_sys_user2_09 = "Terakhir Login"; // 지난 로그인
$txt_sys_user2_10 = "Kunjungan"; // 방문수
$txt_sys_user2_11 = "Bahasa"; // 사용 언어
$txt_sys_user2_12 = "Belum/Tidak Login"; // 로그인 기록 없음

$txt_sys_user2_chk01 = "Silahkan Masukkan Nama Pengelola Toko."; // Shop Manager 이름을 입력하세요.
$txt_sys_user2_chk02 = "";
$txt_sys_user2_chk03 = "Kata Sandi Anda Tidak Valid."; // 입력하신 두 비밀번호가 일치하지 않습니다.


// system > supplier
$txt_sys_supplier_01 = "Supplier"; // 공급자 리스트
$txt_sys_supplier_02 = "Tambah Supplier"; // 공급자 등록하기
$txt_sys_supplier_03 = "Perbarui Supplier"; // 공급자 수정하기
$txt_sys_supplier_04 = "Hapus Supplier"; // 공급자 삭제하기
$txt_sys_supplier_05 = "Kode Supplier"; // 공급자 코드
$txt_sys_supplier_06 = "Nama Supplier"; // 공급자 이름
$txt_sys_supplier_07 = "Jenis"; // 공급 유형
$txt_sys_supplier_071 = "Luar Negara (Import)"; // 해외 (수입)
$txt_sys_supplier_072 = "Dalam Negara"; // 국내
$txt_sys_supplier_08 = "Manager"; // 담당자
$txt_sys_supplier_09 = "Status"; // 상태
$txt_sys_supplier_10 = "Hold"; // 보류
$txt_sys_supplier_11 = "Aktif"; // 거래
$txt_sys_supplier_12 = "Pilih Supplier"; // 공급자 선택
$txt_sys_supplier_13 = "Silahkan Pilih Supplier."; // 공급자를 선택하세요.
$txt_sys_supplier_14 = "Supplier"; // 공급자

$txt_sys_supplier_chk01 = "Silahkan Masukkan Nama Provider."; // 공급자 이름을 입력하세요.


// system > brand
$txt_sys_brand_01 = "Brands"; // 브랜드 리스트
$txt_sys_brand_02 = "Tambah Brand"; // 브랜드 등록하기
$txt_sys_brand_03 = "Perbarui Brand"; // 브랜드 수정하기
$txt_sys_brand_04 = "Hapus Brand"; // 브랜드 삭제하기
$txt_sys_brand_05 = "Kode Brand"; // 브랜드 코드
$txt_sys_brand_06 = "Nama Brand"; // 브랜드 이름
$txt_sys_brand_07 = "Asal"; // 원산지
$txt_sys_brand_09 = "Show"; // 상태
$txt_sys_brand_12 = "Pilih Brand"; // 브랜드 선택
$txt_sys_brand_13 = "Silahkan Pilih Brand."; // 브랜드를 선택하세요.
$txt_sys_brand_14 = "Brand"; // 브랜드

$txt_sys_brand_chk01 = "Silahkan Masukkan Nama Brand."; // 브랜드 이름을 입력하세요.


// system > consign
$txt_sys_consign_01 = "Grup "; // 위탁판매 그룹 리스트
$txt_sys_consign_02 = "Tambah Grup Konsinyasi"; // 위탁판매 그룹 등록하기
$txt_sys_consign_03 = "Perbarui Grup Konsinyasi"; // 위탁판매 그룹 수정하기
$txt_sys_consign_04 = "Hapus Grup Konsinyasi"; // 위탁판매 그룹 삭제하기
$txt_sys_consign_05 = "Kode Grup"; // 그룹 코드
$txt_sys_consign_06 = "Nama Grup"; // 그룹 이름
$txt_sys_consign_07 = "Jenis Grup"; // 그룹 유형
$txt_sys_consign_12 = "Pilih Grup Konsinyasi"; // 위탁판매 그룹 선택
$txt_sys_consign_13 = "Silahkan Grup Konsinyasi"; // 위탁판매 그룹을 선택하세요.
$txt_sys_consign_14 = "Grup Konsinyasi"; // 위탁판매 그룹

$txt_sys_consign_chk01 = "Silahkan Masukkan Nama Grup Konsinyasi."; // 위탁판매 그룹 이름을 입력하세요.


// system > category
$txt_sys_category_01 = "Kategori"; // 카테고리
$txt_sys_category_02 = "Tambah Katgeori"; // 카테고리 추가하기
$txt_sys_category_03 = "Update Kategori"; // 카테고리 수정하기
$txt_sys_category_04 = "Hapus Kategori"; // 카테고리 삭제하기
$txt_sys_category_05 = "Main Kategori"; // 대분류
$txt_sys_category_06 = "Sub Kategori"; // 중분류
$txt_sys_category_07 = "Add New Kategori"; // 새 카테고리 추가
$txt_sys_category_08 = "Hapus All Categories"; // 전체 카테고리 삭제
$txt_sys_category_09 = "Tambah"; // 추가

$txt_sys_category_chk01 = "Harus ada 1 Kategori di bawah Main Kategori."; // 1개 이상의 하부 카테고리가 있어야 합니다.
$txt_sys_category_chk02 = "Anda Tidak Dapat Menghapus Main Kategori dengan Sub Kategori di dalamnya."; // 하부 카테고리가 있는 대분류는 삭제할 수 없습니다.
$txt_sys_category_chk03 = "Anda Tidak Dapat Menghapus Sub Kategori dengan Produk di dalamnya."; // 해당 상품이 있으면 중분류를 삭제할 수 없습니다.


// system > mileage
$txt_sys_mileage_01 = "Tabel Jarak"; // 마일리지 현황
$txt_sys_mileage_02 = "Jarak Tempuh"; // 마일리지
$txt_sys_mileage_03 = "Tanggal"; // 수정일
$txt_sys_mileage_04 = "Default"; // 초기값


// system > discount
$txt_sys_discount_01 = "Tarif Diskon"; // 리셀러 할인율 현황
$txt_sys_discount_02 = "Tarif D/C"; // 할인율


// system > voucher
$txt_sys_voucher_01 = "Voucher"; // 바우처 리스트
$txt_sys_voucher_02 = "Penerbitan Voucher"; // 바우처 발행하기
$txt_sys_voucher_03 = "Perbarui Voucher"; // 바우처 수정하기
$txt_sys_voucher_04 = "Hapus Voucher"; // 바우처 삭제하기
$txt_sys_voucher_05 = "Kode Voucher"; // 바우처 코드
$txt_sys_voucher_06 = "Harga Voucher"; // 바우처 액면가
$txt_sys_voucher_07 = "Terbitan"; // 발행수
$txt_sys_voucher_07_1 = "Digunakan"; // 사용수
$txt_sys_voucher_07_2 = "Pengingat"; // 잔여수
$txt_sys_voucher_08 = "Validitas"; // 바우처 효력
$txt_sys_voucher_09 = "Tanggal Terbit/Keluar "; // 바우처 발행일
$txt_sys_voucher_10 = "Tanggal Validitas"; // 바우처 유효기간

$txt_sys_voucher_chk01 = "Silahkan masukkan harga voucher."; // 바우처 액면가를 입력하세요.
$txt_sys_voucher_chk02 = "Silahkan masukkan nomor terbit voucher."; // 바우처 발행수를 입력하세요.


// system > voucher2
$txt_sys_voucher2_01 = "YARNEN (Bayar Panen)"; // YARNEN (수확물 대납)
$txt_sys_voucher2_02 = "Tambah YARNEN Paket"; // YARNEN 옵션 추가
$txt_sys_voucher2_03 = "Perbarui YARNEN Paket"; // YARNEN 옵션 수정하기
$txt_sys_voucher2_04 = "Hapus YARNEN Option"; // YARNEN 옵션 삭제하기
$txt_sys_voucher2_05 = "Kode YARNEN Paket"; // YARNEN 옵션 코드
$txt_sys_voucher2_06 = "Nama YARNEN Paket"; // YARNEN 옵션 이름
$txt_sys_voucher2_07 = "Tarif YARNEN"; // YARNEN 비율
$txt_sys_voucher2_08 = "Deskripsi YARNEN"; // YARNEN 상세 내역
$txt_sys_voucher2_09 = "dari hasil produksi di lapangan"; // 농지의 총수확물 중에서
$txt_sys_voucher2_10 = "Pilihan YARNEN Paket bagi petani."; // 수확물 대납 옵션을 선택하세요.
$txt_sys_voucher2_11 = "Tidak Gunakan Pinjaman Kredit YARNEN"; // YARNEN을 사용하지 않음
$txt_sys_voucher2_12 = "bulan"; // 개월

$txt_sys_voucher2_chk01 = "Silahkan masukkan Kode YARNEN Paket."; // YARNEN 옵션 코드를 입력하세요.
$txt_sys_voucher2_chk02 = "Silahkan masukkan Nama YARNEN Paket."; // YARNEN 옵션 이름을 입력하세요.
$txt_sys_voucher2_chk03 = "Silahkan masukkan Tarif YARNEN Paket."; // YARNEN 비율을 입력하세요.


// system > discount2
$txt_sys_discount2_01 = "Tabel Harga Spesial."; // 특별 행사가 현황


// system > bank
$txt_sys_bank_01 = "Akun Bank"; // 결제은행 계좌 리스트
$txt_sys_bank_02 = "Tambah Bank"; // 결제은행 등록하기
$txt_sys_bank_03 = "Perbarui Bank"; // 결제은행 수정하기
$txt_sys_bank_04 = "Hapus Bank"; // 결제은행 삭제하기
$txt_sys_bank_05 = "Kode Bank"; // 결제은행 코드
$txt_sys_bank_06 = "Nama Bank"; // 결제은행 이름
$txt_sys_bank_07 = "Akun No."; // 계좌번호
$txt_sys_bank_08 = "Nama Akun"; // 예금주
$txt_sys_bank_09 = "Nama Cabang"; // 은행 지점 이름
$txt_sys_bank_10 = "SWIFT Kode";
$txt_sys_bank_11 = "Pengelola"; // 담당자
$txt_sys_bank_12 = "Email"; // 담당자 Email
$txt_sys_bank_13 = "Mata Uang"; // 통 화
$txt_sys_bank_14 = "Saldo Awal"; // 초기 잔액
$txt_sys_bank_15 = "Uncollected"; // 미수금

$txt_sys_bank_chk01 = "Silahkan Masukkan Nama Bank."; // 결제은행 이름을 입력하셔야 합니다.


// system > card
$txt_sys_card_01 = "Mesin Pengganti Kartu"; // 신용카드 결제기 리스트
$txt_sys_card_02 = "Tambah Mesin Pengganti Kartu"; // 신용카드 결제기 등록하기
$txt_sys_card_03 = "Perbarui Mesin Pengganti Kartu"; // 신용카드 결제기 수정하기
$txt_sys_card_04 = "Hapus Mesin Pengganti Kartu"; // 신용카드 결제기 삭제하기
$txt_sys_card_05 = "C. Kode"; // 분류 코드
$txt_sys_card_06 = "Mesin Pengganti"; // 신용카드 결제기
$txt_sys_card_07 = "Billing Bank"; // 신용카드 결제은행
$txt_sys_card_08 = "Rate"; // 카드 수수료

$txt_sys_card_chk01 = "Silahkan Masukkan Nama Kartu Kredit."; // 신용카드 이름을 입력하셔야 합니다.


// system > zone_area
$txt_sys_area_01 = "Daerah-daerah"; // 배송지 리스트
$txt_sys_area_02 = "Tambah Daerah"; // 배송지 정보 등록하기
$txt_sys_area_03 = "Perbarui Daerah"; // 배송지 정보 수정하기
$txt_sys_area_04 = "Hapus Daerah"; // 배송지 정보 삭제하기
$txt_sys_area_05 = "Kode"; // 지역 코드
$txt_sys_area_06 = "Negara"; // 국 가
$txt_sys_area_07 = "Daerah"; // 도시/지역 이름
$txt_sys_area_08 = "Tarif Pengiriman"; // 배송료
$txt_sys_area_09 = "Minimum Wage"; // 최저 임금

$txt_sys_area_chk01 = "Silahkan Masukkan Kode Daerah."; // 지역 코드를 입력하셔야 합니다.
$txt_sys_area_chk02 = "Silahkan Masukkan Nama Daerah."; // 지역 이름을 입력하셔야 합니다.


// system > loan
$txt_sys_loan_01 = "Pinjaman Bank"; // 은행 차입
$txt_sys_loan_02 = "Tambah Pinjaman Bank"; // 은행 차입 등록하기
$txt_sys_loan_03 = "Perbarui Pinjaman Bank"; // 은행 차입 수정하기
$txt_sys_loan_04 = "Hapus Pinjaman Bank"; // 은행 차입 삭제하기
$txt_sys_loan_05 = "Kode Pinjaman"; // 은행대출 코드
$txt_sys_loan_06 = "Penyedia Pinjaman"; // 차입 은행
$txt_sys_loan_07 = "Nama Pinjaman Produk"; // 대출 상품명
$txt_sys_loan_08 = "Total Pinjaman"; // 차입 금액
$txt_sys_loan_09 = "Bunga"; // 차입 이자
$txt_sys_loan_10 = "Tanggal Pinjaman"; // 차입일
$txt_sys_loan_11 = "Tanggal Jatuh Tempo"; // 만기일
$txt_sys_loan_12 = "Gunakan Pinjaman Bank"; // 은행 차입 사용하기
$txt_sys_loan_13 = "Tidak Gunakan Pinjaman"; // 사용하지 않음
$txt_sys_loan_14 = "Tersedia Pinjaman"; // 차입 가능분
$txt_sys_loan_15 = "Permintaan Pinjaman"; // 차입 요청
$txt_sys_loan_16 = "Batas"; // 대출 한도

$txt_sys_loan_chk01 = "Mohon Pilih Penyedia Pinjaman."; // 차입 은행을 선택하세요.
$txt_sys_loan_chk02 = "Mohon Pilih Nama Produk Pinjaman."; // 대출 상품명 선택하세요.
$txt_sys_loan_chk03 = "Mohon Pilih Total Pinjaman."; // 차입 금액을 선택하세요.


// system > account
$txt_sys_account_01 = "Kode Akuntansi"; // 계정항목 리스트
$txt_sys_account_02 = "Tambah Akun Entry"; // 계정항목 등록하기
$txt_sys_account_03 = "Perbarui Akun Entry"; // 계정항목 수정하기
$txt_sys_account_04 = "Hapus Akun Entry"; // 계정항목 삭제하기
$txt_sys_account_05 = "Pendapatan"; // 수 입
$txt_sys_account_05_A1 = "Penjualan"; // 판매 수입
$txt_sys_account_05_A2 = "Skola Hari Minngu"; // 주일 학교
$txt_sys_account_05_A3 = "Offering Hari Minggu"; // 주일 헌금
$txt_sys_account_05_A4 = "Offering"; // 기타 헌금
$txt_sys_account_05_A4051 = "Easter"; // 부활절
$txt_sys_account_05_A4052 = "Thanks-giving"; // 추수감사절
$txt_sys_account_05_A4053 = "Christmas"; // 성탄절
$txt_sys_account_05_A5 = "Lain-lain"; // 기타 수입
$txt_sys_account_06 = "Keluar"; // 지 출
$txt_sys_account_06_B1 = "Biaya Langsung"; // 직접 비용
$txt_sys_account_06_B2 = "Biaya Tidak Langsung"; // 간접 비용
$txt_sys_account_06_B3 = "Gaji"; // 인건비
$txt_sys_account_09 = "Tambah Field"; // 항목 추가
$txt_sys_account_10 = "Kirim"; // 등 록


// user
$txt_user_01 = "Ganti Bahasa"; // 언어 변경하기
$txt_user_02 = "Ubah Kata Sandi"; // 비밀번호 변경하기
$txt_user_03 = "Kata Sandi Lama"; // 현 비밀번호
$txt_user_04 = "Perbarui Profil"; // 개인정보 변경하기
$txt_user_05 = "";




// Website
// website > menu
$txt_web_menu_01 = "Menu List"; // 메뉴 리스트
$txt_web_menu_02 = "Add Menu"; // 메뉴 등록하기
$txt_web_menu_03 = "Update Menu"; // 메뉴 수정하기
$txt_web_menu_04 = "Delete Menu"; // 메뉴 삭제하기
$txt_web_menu_05 = "Menu Title"; // 메뉴 이름
$txt_web_menu_06 = "Menu Format"; // 메뉴 속성
$txt_web_menu_type_news = "News Clip"; // 뉴스 클립
$txt_web_menu_type_emag = "Magazine"; // 매거진
$txt_web_menu_type_hist = "History"; // 연혁
$txt_web_menu_type_serm = "Sermon"; // 설교
$txt_web_menu_type_faq = "FAQ"; // 자주 묻는 질문 (FAQ)
$txt_web_menu_type_qna = "Q&A"; // 묻고 답하기 (Q&A)
$txt_web_menu_type_book = "Guest Book"; // 방명록
$txt_web_menu_type_bbs = "Board"; // 게시판
$txt_web_menu_type_bbsm = "Board (Marketplace)"; // 게시판 (사고팔기)
$txt_web_menu_type_bbsj = "Board (Recruitment)"; // 게시판 (구인구직)
$txt_web_menu_type_alb1 = "Photo Gallery (1 Column)"; // 포토 갤러리 (가로 1칸)
$txt_web_menu_type_alb2 = "Photo Gallery (2 Columns)"; // 포토 갤러리 (가로 2칸)
$txt_web_menu_type_alb4 = "Photo Gallery (4 Columns)"; // 포토 갤러리 (가로 4칸)
$txt_web_menu_type_alb5 = "Photo Gallery (5 Columns)"; // 포토 갤러리 (가로 5칸)
$txt_web_menu_type_albx = "Photo Gallery (Directory)"; // 포토 갤러리 (디렉토리)
$txt_web_menu_type_week = "Weekly Bulletin"; // 주보
$txt_web_menu_type_blnk = "Blank Page"; // 빈 페이지
$txt_web_menu_type_pop = "* Link to Pop-up Page *"; // * 팝업 페이지에 연결 *
$txt_web_menu_type_link = "* Link to URL *"; // * 특정 URL에 연결 *
$txt_web_menu_type_rss = "* Link to RSS *"; // * RSS에 연결 *
$txt_web_menu_type_x = "* Link to Sub Page *"; // * 서브 페이지에 연결 *

$txt_web_menu_07 = "Option"; // 첨부 옵션
$txt_web_menu_opt_0 = "Default"; // 기본
$txt_web_menu_opt_1 = "Attach Image"; // 이미지
$txt_web_menu_opt_2 = "Attach Flash Movie (SWF)"; // Flash 무비 (SWF)
$txt_web_menu_opt_3 = "Attach File (Resource Centre)"; // 일반 파일 (자료실 운영)
$txt_web_menu_opt_4 = "Attach Audio File & MP3"; // 오디오 파일 및 MP3
$txt_web_menu_opt_5 = "Attach Movie Clip"; // 동영상 파일
$txt_web_menu_opt_6 = "Attach Movie Clip (FLV/MP4)"; // 동영상 파일 (FLV/MP4)
$txt_web_menu_opt_8 = "Attach Form Mailer"; // 메일 발송 폼

$txt_web_menu_08 = "Number"; // 개수
$txt_web_menu_08d = "Day"; // 일
$txt_web_menu_08dp = "Days"; // 일
$txt_web_menu_082 = "articles / page"; // 개 / 페이지
$txt_web_menu_09 = "Add+"; // 추가+
$txt_web_menu_10 = "Add Menu"; // 메뉴 추가
$txt_web_menu_11 = "Website URL"; // 홈페이지 주소
$txt_web_menu_12 = "Menu Code"; // 메뉴 코드
$txt_web_menu_13 = "Menu Depth"; // 메뉴 단계 구분
$txt_web_menu_131 = "Main Menu"; // 메인 메뉴
$txt_web_menu_132 = "Sub Menu"; // 서브 메뉴
$txt_web_menu_14 = "In Use"; // 사용하기
$txt_web_menu_15 = "New Article"; // 신규 게시물 표시
$txt_web_menu_16 = "Number of rows"; // 게시물 수
$txt_web_menu_17 = "Permission"; // 게시물 접근허가
$txt_web_menu_permit_0 = "Free Access"; // 제한 없음
$txt_web_menu_permit_1 = "Writeable After Login"; // 로그인 후 쓰기 가능
$txt_web_menu_permit_2 = "Read-Only Before/After Login"; // 언제나 읽기만 가능
$txt_web_menu_permit_3 = "Read-Only After Login"; // 로그인 후 읽기만 가능
$txt_web_menu_permit_4 = "Free Access By Member After Login"; // 로그인한 회원만 이용 가능
$txt_web_menu_permit_5 = "Free Access By Staff After Login"; // 로그인한 직원만 이용 가능
$txt_web_menu_permit_6 = "No Access Permitted Except Admin"; // 관리자 외 사용 금지

$txt_web_menu_18 = "Menu Location"; // 메뉴 위치
$txt_web_menu_loco_intro1 = "Intro Page"; // 인트로 페이지
$txt_web_menu_loco_intro2 = "Dashboard"; // 대쉬보드
$txt_web_menu_loco_head = "Header"; // 상단
$txt_web_menu_loco_foot = "Footer"; // 하단
$txt_web_menu_loco_short = "Short Cut"; // 단축 메뉴

$txt_web_menu_19 = "Order By"; // 정렬 방법
$txt_web_menu_191 = "DESCending"; // 내림차순
$txt_web_menu_192 = "ASCending"; // 오름차순
$txt_web_menu_193 = "RANDOM"; // 무작위
$txt_web_menu_20 = "Connect to Site"; // 특정 사이트에 연결
$txt_web_menu_21 = "Connect to URL"; // 특정 URL에 연결
$txt_web_menu_22 = "Link now"; // 연결 하기
$txt_web_menu_23 = "";
$txt_web_menu_24 = "";
$txt_web_menu_25 = "";


// website > content
$txt_web_content_01 = "Articles"; // 콘텐츠 리스트
$txt_web_content_02 = "Post Article"; // 콘텐츠 등록하기
$txt_web_content_03 = "Edit Article"; // 콘텐츠 수정하기
$txt_web_content_04 = "Delete Article"; // 콘텐츠 삭제하기
$txt_web_content_order0 = "Updated"; // 수정순
$txt_web_content_order1 = "Subject"; // 제목순
$txt_web_content_order2 = "Contents"; // 내용순
$txt_web_content_order3 = "Posting Date"; // 게시일순
$txt_web_content_order4 = "Last Updated"; // 최근수정순

$txt_web_content_05 = "Add Content"; // 콘텐츠 추가
$txt_web_content_06 = "List"; // 리스트
$txt_web_content_07 = "Title"; // 제목
$txt_web_content_08 = "Subtitle"; // 부제목
$txt_web_content_09 = "Content"; // 내용
$txt_web_content_10 = "Image File"; // 이미지 파일
$txt_web_content_10p = "Replace"; // 교체
$txt_web_content_11 = "Image Caption"; // 이미지 설명글
$txt_web_content_12 = "Show"; // 게시
$txt_web_content_121 = "Shown"; // 보여짐
$txt_web_content_122 = "Hidden"; // 숨김
$txt_web_content_13 = "Add Paragraph"; // 단락 추가하기
$txt_web_content_14 = "Select Writer"; // 작가를 선택하세요
$txt_web_content_15 = "Unknown"; // 작가 미지정
$txt_web_content_16 = "Create Contents"; // 콘텐츠 생성하기
$txt_web_content_17 = "Contents Type"; // 콘텐츠 타입
$txt_web_content_18 = "Upload Image File"; // 이미지 파일 올리기


// website > banner1
$txt_web_banner1_01 = "Banner Files"; // 배너 파일 리스트
$txt_web_banner1_02 = "Post Banner File"; // 배너 파일 등록하기
$txt_web_banner1_03 = "Update Banner File"; // 배너 파일 수정하기
$txt_web_banner1_04 = "Delete Banner File"; // 배너 파일 삭제하기
$txt_web_banner1_order0 = "Banner Code"; // 배너 코드순
$txt_web_banner1_order1 = "Upload Date"; // 배너 등록순
$txt_web_banner1_05 = "Banner Code(ID)"; // 배너 코드(ID)
$txt_web_banner1_05s = "Code(ID)"; // 코드(ID)
$txt_web_banner1_06 = "Banner Type"; // 배너 타입
$txt_web_banner1_07 = "File Size"; // 파일 크기
$txt_web_banner1_08 = "Add Banner File"; // 배너 파일 추가
$txt_web_banner1_09 = "Banner File Name"; // 배너 파일명
$txt_web_banner1_10 = "Upload Banner File"; // 배너 파일 올리기
$txt_web_banner1_11 = "Banner Dimension"; // 배너 크기
$txt_web_banner1_111 = "Width"; // 가로
$txt_web_banner1_112 = "Height"; // 세로
$txt_web_banner1_12 = "Pixel"; // 픽셀
$txt_web_banner1_13 = "Replace Banner File"; // 배너 파일 교체
$txt_web_banner1_14 = ""; //
$txt_web_banner1_15 = ""; //


// website > banner2
$txt_web_banner2_01 = "Banner Display List"; // 배너 게시 리스트
$txt_web_banner2_02 = "Add Banner Display"; // 배너 게시 등록하기
$txt_web_banner2_03 = "Update Banner Display"; // 배너 게시 수정하기
$txt_web_banner2_04 = "Delete Banner Display"; // 배너 게시 삭제하기
$txt_web_banner2_05 = "Location"; // 게시 위치
$txt_web_banner2_05b = "Banner Location"; // 배너 게시 위치
$txt_web_banner2_06 = "Account"; // 광고주 계정
$txt_web_banner2_06b = "Banner Account"; // 배너 광고주 계정
$txt_web_banner2_07 = "Add Banner Display"; // 배너 게시 추가
$txt_web_banner2_08 = "Banner URL"; // 배너 연결 URL
$txt_web_banner2_09 = "Bg Color"; // 배경색
$txt_web_banner2_10 = "When 'Custom', input Target name"; // 'Custom' 선택시, Target 이름
$txt_web_banner2_11 = "Banner Display"; // 배너 게시
$txt_web_banner2_12 = "No. of Visitors"; // 방문자 수
$txt_web_banner2_13 = "Date of Posting"; // 등록일
$txt_web_banner2_14 = "Last Update"; // 최근 수정일


// website > stuff
$txt_web_stuff_01 = "Select Location"; // 콘테츠 위치별 종류 선택
$txt_web_stuff_loco_01 = "Welcome Comment [Intro Page]"; // 환영인사 [첫화면]
$txt_web_stuff_loco_02 = "Contact Info [Left]"; // 연락처 [좌측]
$txt_web_stuff_loco_03 = "Guide to Sign-up"; // 회원 가입 안내
$txt_web_stuff_loco_04 = "Terms & Regulations"; // 이용자 약관
$txt_web_stuff_loco_05 = "Reminder [Pop-up Page]"; // 공지 사항 [팝업창]
$txt_web_stuff_loco_06 = "Foot Box"; // 하단 박스
$txt_web_stuff_loco_07 = "Foot Box Small Column"; // 하단 박스 작은 칸
$txt_web_stuff_loco_08 = "Copyrights"; // 하단 저작권 표시
$txt_web_stuff_loco_09 = "Auto Response - Sign-up"; // 자동응답메일 - 회원 가입
$txt_web_stuff_loco_10 = "Auto Response - Find Password"; // 자동응답메일 - 비밀번호 찾기
$txt_web_stuff_loco_11 = "Auto Response - Invoice"; // 자동응답메일 - 인보이스 발행
$txt_web_stuff_loco_12 = "News Letter - Footer"; // 뉴스 레터 - 하단 주소표시 줄
$txt_web_stuff_loco_13 = "Shop - Billing Information"; // 쇼핑몰 - 과금 안내
$txt_web_stuff_loco_14 = "Shop - Shipping"; // 쇼핑몰 - 배송 안내


// website > mailing
$txt_web_mailing_01 = "Agree"; // 수신 동의
$txt_web_mailing_01_yes = "Yes"; // 동의
$txt_web_mailing_01_no = "No"; // 거절
$txt_web_mailing_02 = "List-up"; // 리스트-업
$txt_web_mailing_021 = "Remove"; // 해제하기
$txt_web_mailing_022 = "+ Add"; // + 등록
$txt_web_mailing_03 = "Selected"; // 선택한 메일 수
$txt_web_mailing_04 = "Add All"; // 모두 등록하기
$txt_web_mailing_05 = "Remove All"; // 모두 해제하기
$txt_web_mailing_06 = "Select News Letter"; // 뉴스 레터를 선택하세요
$txt_web_mailing_07 = "Add to Mailing List"; //  메일링 리스트에 등록하기
$txt_web_mailing_08 = "Sent Date"; // 발송일
$txt_web_mailing_08s = "Sent"; // 발송일
$txt_web_mailing_09 = "Count"; // 발송수
$txt_web_mailing_10 = "Mailer"; // 발송하기
$txt_web_mailing_11 = "Re-send"; // 재발송
$txt_web_mailing_12 = "+ Send"; // + 발송
$txt_web_mailing_13 = "Composed"; // 작성일

$txt_web_mailing_chk_01 = "Your submission of Email already exists in the mailing list."; // 입력하신 이메일은 이미 메일링 리스트에 있습니다.


// website > news letter
$txt_web_nletter_01 = "News Letters"; // 뉴스 레터 리스트
$txt_web_nletter_02 = "Compose News Letter"; // 뉴스 레터 등록하기
$txt_web_nletter_03 = "Edit News Letter"; // 뉴스 레터 수정하기
$txt_web_nletter_04 = "Delete News Letter"; // 뉴스 레터 삭제하기
$txt_web_nletter_05 = "Compose News Letter"; // 뉴스 레터 작성하기
$txt_web_nletter_06 = "Issue No."; // 발송 번호
$txt_web_nletter_07 = "Footer"; // 하단 주소표시 부분
$txt_web_nletter_08 = "No. of Recipients"; // 수신자 수
$txt_web_nletter_09 = "Compose"; // 편집창
$txt_web_nletter_10 = "Preview"; // 미리보기
$txt_web_nletter_11 = "Send News Letter"; // 뉴스 레터 발송하기
$txt_web_nletter_12 = "Recipients"; // 수신자
$txt_web_nletter_121 = "All the Mailing List"; // 메일링 리스트에 등록된 전체 수신자
$txt_web_nletter_122 = "All your selections from Mailing List"; // 메일링 리스트에서 선택한 수신자
$txt_web_nletter_123 = "All the List filtered from Mailing List"; // 메일링 리스트에서 검색한 수신자


// website > layout
$txt_web_layout_01 = "Save Website Layout"; // 홈페이지 레이아웃 저장하기
$txt_web_layout_02 = "Create Website Layout Table"; // 홈페이지 레이아웃 테이블 생성하기




// BBS

	// 인사말
	$bbstxt_01 = "Introduction1";
	$bbstxt_02 = "Introduction2";

	// My Members
	$mbdtxt_01 = "Pusat Daftar Anggota";
	$mbdtxt_02 = "Jenis Kelamin";
	$mbdtxt_03 = "Lokasi";
	$mbdtxt_04 = "Pesan";
	$mbdtxt_05 = "Status";
	$mbdtxt_06 = "Tindakan";
	$mbdtxt_07 = "Pria";
	$mbdtxt_08 = "Wanita";
	$mbdtxt_09 = "Terdaftar";
	$mbdtxt_10 = "Tidak Terdaftar";
	$mbdtxt_11 = "Buku Alamat";

	// Bulletin
	$bdtxt_01 = "Nomor.";
	$bdtxt_02 = "Subjek";
	$bdtxt_03 = "Nama";
	$bdtxt_04 = "Tanggal";
	$bdtxt_05 = "Hit";
	$bdtxt_06 = "Pilih";
	$bdtxt_07 = "Nama";
	$bdtxt_08 = "Komentar";
	$bdtxt_09 = "Pasang Artikel";
	$bdtxt_10 = "Situs Web";
	$bdtxt_11 = "Kata Kunci";
	$bdtxt_12 = "(Antara 4~8 huruf)";
	$bdtxt_13 = "Berikan Komentar Balik";
	$bdtxt_14 = "Edit Artikel";
	$bdtxt_151 = "Hapus Artikel";

	// PDS
	$bdtxt_15 = "FILE";
	$bdtxt_16 = "Deskripsi";
	$bdtxt_17 = "Download";
	$bdtxt_18 = " telah dikirimkan.";
	$bdtxt_19 = "Komentar";
	$bdtxt_20 = "Icon Emosi";
	$bdtxt_21 = "Anda Memberikan Komentar !";
	$bdtxt_22 = "Hapus FILE Anda";
	$bdtxt_23 = "Ambil FILE";
	
	$bdtxt_24 = "IP";

	$bdtxt_31 = "Pesanan dari Isi";
	$bdtxt_32 = "Pesanan Ascending";
	$bdtxt_33 = "Pesanan Descending";
	$bdtxt_34 = "Masukkan Gambar";
	$bdtxt_35 = "Nomor Gambar";
	$bdtxt_36 = "GIF";
	$bdtxt_37 = "JPG";
	$bdtxt_38 = "SWF(Flash Movie Clip)";
	$bdtxt_39 = "Garis Batas Gambar";
	$bdtxt_40 = "Batas Vertikal - Atas";
	$bdtxt_41 = "Batas Vertikal - Bawah";
	$bdtxt_42 = "Batas Vertikal - Tengah";
	$bdtxt_43 = "Margin Kiri";
	$bdtxt_44 = "Margin Tengah";
	$bdtxt_45 = "Margin Kanan";

	$bdtxt_51 = "Image Size";
	$bdtxt_52 = "Landscape";
	$bdtxt_53 = "Portrait";
	$bdtxt_54 = "Square";

	$bdtxt_91 = "Pin Key";
	$bdtxt_92 = "Please put the words below in the blank.";
	$bdtxt_93 = "Cari";
	$bdtxt_94 = "This is Confidential Content."; // 비밀글입니다.
	$bdtxt_95 = "Confidential"; // 비밀댓글
	$bdtxt_96 = "Post"; // 댓글쓰기
	$bdtxt_97 = "This is Confidential Foot note."; // 비밀댓글입니다.
	$bdtxt_98 = "Please insert your comment."; // 댓글을 입력하셔야 합니다.
	$bdtxt_99 = "Maximum 200 letters are vailable here."; // 글자수는 한글 100자, 영문 200자로 제한됩니다.
	$bdtxt_901 = "This article has been saved in your library."; // My Library에 저장되었습니다.
	$bdtxt_902 = "This article was already saved in your library"; // 이미 My Library에 저장하셨습니다.
	$bdtxt_903 = "Nick Name"; // 닉네임
	$bdtxt_904 = "Sale"; // 매매
	$bdtxt_905 = "Rent"; // 임대
	$bdtxt_906 = "Lease"; // 재임대
	$bdtxt_907 = "Subtitle"; // 부제목
	$bdtxt_908 = "New line breaks"; // 줄바꿔 쓰기
	$bdtxt_909 = "Non-disclosure"; // 비밀글
	$bdtxt_910 = "Advertising"; // 광고 신청
	$bdtxt_911 = "Box"; // 박스광고
	$bdtxt_912 = "Line"; // 줄광고
	$bdtxt_913 = "No, thanks."; // 신청 않음
	$bdtxt_914 = "Replace Attached File"; // 첨부파일 변경
	$bdtxt_915 = "Cancel"; // 광고 해제
	

	// 방명록
	$buktxt_01 = "Buku Tamu";
	$buktxt_02 = "Tidak Ada Tulisan yang Terkirimkan pada Buku Tamu Sekarang.";
	$buktxt_03 = "Modifikasi";
	$buktxt_04 = "Hapus";
	$buktxt_05 = "Komentar";
	$buktxt_06 = "";
	$buktxt_07 = "";
	$buktxt_08 = "";
	$buktxt_09 = "";
	$buktxt_10 = "";

	// Trade
	$trdtxt_01 = "Judul";
	$trdtxt_02 = "Item";
	$trdtxt_03 = "Perkenalan";
	$trdtxt_04 = "Deskripsi";
	$trdtxt_05 = "Kondisi";
	$trdtxt_06 = "Contact Info";
	$trdtxt_07 = "Gambar1";
	$trdtxt_08 = "Gambar2";
	$trdtxt_09 = "Tidak ada Gambar";
	$trdtxt_10 = "Attached File";
	$trdtxt_11 = "No Attached File";
	$trdtxt_12 = "Ukuran File";
	$trdtxt_13 = "Maksimal kemampuan 100 strings";
	$trdtxt_14 = "Pixel";
	$trdtxt_15 = "Replace Image";
	$trdtxt_16 = "Replace File";
	$trdtxt_17 = "Attach File";
	$trdtxt_18 = "Please enter the Introduction.";
	$trdtxt_19 = "";
	$trdtxt_20 = "";

	// 북마크
	$bmktxt_01 = "Nama Website";
	$bmktxt_02 = "Alamat Website";
	$bmktxt_03 = "Bookmark";
	$bmktxt_04 = "Please enter the Website Name.";
	$bmktxt_05 = "Please enter the Website URL.";

  // 폼메일
  $fmltxt_01 = "Send";
  $fmltxt_02 = "Reset";
  $fmltxt_03 = "Your mail has been delivered successfully ..^^*";
  $fmltxt_04 = "Please enter your name.";
  $fmltxt_05 = "Please enter your Email address.";
  $fmltxt_06 = "Please enter the title.";
  $fmltxt_07 = "Please enter your message.";
  $fmltxt_08 = "Online Order Form";
  $fmltxt_09 = "Product";
  $fmltxt_10 = "";

  $fmltxt_21 = "Invalid Email Adress.";
  $fmltxt_22 = "Please enter a password.";
  $fmltxt_23 = "Please enter the pin key.";
  $fmltxt_24 = "Post";
  $fmltxt_25 = "Reset";
  $fmltxt_26 = "Update";
  $fmltxt_27 = "Delete";
  $fmltxt_28 = "Cancel";
  $fmltxt_29 = "";

	// 마켓플레이스/구인구직 등
	$bmrtxt_01 = "Select";
	$bmrtxt_11 = "Sell";
	$bmrtxt_12 = "Buy";
	$bmrtxt_21 = "Wanted";
	$bmrtxt_22 = "Job Opportunity";
?>

